/* 会来事 · L3/L4 双向核心词库
 * Thai romanization uses a consistent, learner-friendly RTGS-style spelling.
 * Example sentences are expanded from reviewed bilingual patterns at load time.
 */
(function () {
  "use strict";

  const cap = value => value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
  const patterns = {
    place: r => [`请问，${r.zh}在哪里？`, `Qǐngwèn, ${r.py} zài nǎlǐ?`, `ขอโทษค่ะ ${r.th}อยู่ที่ไหน`, `kho thot kha, ${r.ro} yu thi nai`],
    need: r => [`我需要${r.zh}。`, `Wǒ xūyào ${r.py}.`, `ฉันต้องการ${r.th}`, `chan tongkan ${r.ro}`],
    want: r => [`我想要${r.zh}。`, `Wǒ xiǎng yào ${r.py}.`, `ฉันอยากได้${r.th}`, `chan yak dai ${r.ro}`],
    have: r => [`这里有${r.zh}吗？`, `Zhèlǐ yǒu ${r.py} ma?`, `ที่นี่มี${r.th}ไหม`, `thi ni mi ${r.ro} mai`],
    do: r => [`我们可以${r.zh}吗？`, `Wǒmen kěyǐ ${r.py} ma?`, `เรา${r.th}ได้ไหม`, `rao ${r.ro} dai mai`],
    please: r => [`请${r.zh}。`, `Qǐng ${r.py}.`, `กรุณา${r.th}`, `karuna ${r.ro}`],
    daily: r => [`我每天都${r.zh}。`, `Wǒ měitiān dōu ${r.py}.`, `ฉัน${r.th}ทุกวัน`, `chan ${r.ro} thuk wan`],
    food: r => [`我要一份${r.zh}。`, `Wǒ yào yí fèn ${r.py}.`, `ขอ${r.th}หนึ่งที่`, `kho ${r.ro} nueng thi`],
    buy: r => [`我想买${r.zh}。`, `Wǒ xiǎng mǎi ${r.py}.`, `ฉันอยากซื้อ${r.th}`, `chan yak sue ${r.ro}`],
    person: r => [`那位是${r.zh}。`, `Nà wèi shì ${r.py}.`, `คนนั้นคือ${r.th}`, `khon nan khue ${r.ro}`],
    adj: r => [`这里很${r.zh}。`, `Zhèlǐ hěn ${r.py}.`, `ที่นี่${r.th}มาก`, `thi ni ${r.ro} mak`],
    feel: r => [`我觉得很${r.zh}。`, `Wǒ juéde hěn ${r.py}.`, `ฉันรู้สึก${r.th}มาก`, `chan rusuek ${r.ro} mak`],
    time: r => [`我们${r.zh}见。`, `Wǒmen ${r.py} jiàn.`, `เจอกัน${r.th}`, `choe kan ${r.ro}`],
    workdoc: r => [`请把${r.zh}发给我。`, `Qǐng bǎ ${r.py} fā gěi wǒ.`, `กรุณาส่ง${r.th}ให้ฉัน`, `karuna song ${r.ro} hai chan`],
    workdo: r => [`我们今天要${r.zh}。`, `Wǒmen jīntiān yào ${r.py}.`, `วันนี้เราต้อง${r.th}`, `wan ni rao tong ${r.ro}`],
    study: r => [`我正在学${r.zh}。`, `Wǒ zhèngzài xué ${r.py}.`, `ฉันกำลังเรียน${r.th}`, `chan kamlang rian ${r.ro}`],
    health: r => [`我有点${r.zh}。`, `Wǒ yǒudiǎn ${r.py}.`, `ฉันมีอาการ${r.th}นิดหน่อย`, `chan mi akan ${r.ro} nit noi`],
    culture: r => [`我想了解${r.zh}。`, `Wǒ xiǎng liǎojiě ${r.py}.`, `ฉันอยากรู้เรื่อง${r.th}`, `chan yak ru rueang ${r.ro}`],
    lostWay: r => [`我${r.zh}了。`, `Wǒ ${r.py} le.`, `ฉัน${r.th}แล้ว`, `chan ${r.ro} laeo`],
    lostItem: r => [`我的护照${r.zh}了。`, `Wǒ de hùzhào ${r.py} le.`, `หนังสือเดินทางของฉัน${r.th}`, `nangsue doen thang khong chan ${r.ro}`],
    allergy: r => [`我对花生${r.zh}。`, `Wǒ duì huāshēng ${r.py}.`, `ฉัน${r.th}ถั่วลิสง`, `chan ${r.ro} thua lisong`],
    late: r => [`我今天${r.zh}了。`, `Wǒ jīntiān ${r.py} le.`, `วันนี้ฉัน${r.th}`, `wan ni chan ${r.ro}`],
    earlyLeave: r => [`他今天${r.zh}了。`, `Tā jīntiān ${r.py} le.`, `วันนี้เขา${r.th}`, `wan ni khao ${r.ro}`],
    homework: r => [`我正在做${r.zh}。`, `Wǒ zhèngzài zuò ${r.py}.`, `ฉันกำลังทำ${r.th}`, `chan kamlang tham ${r.ro}`],
    cleanRoom: r => [`我每天都${r.zh}房间。`, `Wǒ měitiān dōu ${r.py} fángjiān.`, `ฉัน${r.th}ห้องทุกวัน`, `chan ${r.ro} hong thuk wan`],
    moveNextMonth: r => [`我下个月要${r.zh}。`, `Wǒ xià ge yuè yào ${r.py}.`, `ฉันจะ${r.th}เดือนหน้า`, `chan cha ${r.ro} duean na`],
    importantPlace: r => [`这里很${r.zh}。`, `Zhèlǐ hěn ${r.py}.`, `ที่นี่${r.th}มาก`, `thi ni ${r.ro} mak`],
    say: r => [`${r.zh}。`, `${cap(r.py)}.`, `${r.th}`, `${cap(r.ro)}.`]
  };

  /* row: category, part of speech, Chinese, pinyin, Thai, Thai romanization,
     example pattern, optional Chinese note, optional Thai note */
  const L3 = [
    // 001–025 · travel places
    ['travel','n','机场','jīchǎng','สนามบิน','sanam bin','place'],
    ['travel','n','火车站','huǒchēzhàn','สถานีรถไฟ','sathani rotfai','place'],
    ['travel','n','汽车站','qìchēzhàn','สถานีขนส่ง','sathani khonsong','place'],
    ['travel','n','地铁站','dìtiězhàn','สถานีรถไฟใต้ดิน','sathani rotfai taidin','place'],
    ['travel','n','公交站','gōngjiāozhàn','ป้ายรถเมล์','pai rot me','place'],
    ['travel','n','出租车','chūzūchē','รถแท็กซี่','rot thaeksi','need'],
    ['travel','n','酒店','jiǔdiàn','โรงแรม','rongraem','place'],
    ['travel','n','前台','qiántái','เคาน์เตอร์ต้อนรับ','khaotoe ton rap','place'],
    ['travel','n','房间','fángjiān','ห้องพัก','hong phak','need'],
    ['travel','n','电梯','diàntī','ลิฟต์','lif','place'],
    ['travel','n','洗手间','xǐshǒujiān','ห้องน้ำ','hong nam','place'],
    ['travel','n','出口','chūkǒu','ทางออก','thang ok','place'],
    ['travel','n','入口','rùkǒu','ทางเข้า','thang khao','place'],
    ['travel','n','售票处','shòupiàochù','ห้องจำหน่ายตั๋ว','hong chamnai tua','place'],
    ['travel','n','登机口','dēngjīkǒu','ประตูขึ้นเครื่อง','pratu khuen khrueang','place'],
    ['travel','n','行李领取处','xíngli lǐngqǔchù','จุดรับกระเป๋า','chut rap krapao','place'],
    ['travel','n','安检口','ānjiǎnkǒu','จุดตรวจความปลอดภัย','chut truat khwam plotphai','place'],
    ['travel','n','海关','hǎiguān','ศุลกากร','sunlakakon','place'],
    ['travel','n','领事馆','lǐngshìguǎn','สถานกงสุล','sathan kongsun','place'],
    ['emergency','n','警察局','jǐngchájú','สถานีตำรวจ','sathani tamruat','place'],
    ['health','n','医院','yīyuàn','โรงพยาบาล','rongphayaban','place'],
    ['health','n','药店','yàodiàn','ร้านขายยา','ran khai ya','place'],
    ['travel','n','银行','yínháng','ธนาคาร','thanakhan','place'],
    ['travel','n','兑换处','duìhuànchù','จุดแลกเงิน','chut laek ngoen','place'],
    ['travel','n','旅游中心','lǚyóu zhōngxīn','ศูนย์ข้อมูลนักท่องเที่ยว','sun khomun nak thongthiao','place'],

    // 026–050 · travel essentials
    ['travel','n','护照','hùzhào','หนังสือเดินทาง','nangsue doen thang','need'],
    ['travel','n','签证','qiānzhèng','วีซ่า','wisa','need'],
    ['travel','n','机票','jīpiào','ตั๋วเครื่องบิน','tua khrueang bin','need'],
    ['travel','n','车票','chēpiào','ตั๋วรถ','tua rot','need'],
    ['travel','n','登机牌','dēngjīpái','บัตรขึ้นเครื่อง','bat khuen khrueang','need'],
    ['travel','n','行李','xíngli','สัมภาระ','samphara','have'],
    ['travel','n','行李箱','xínglixiāng','กระเป๋าเดินทาง','krapao doen thang','have'],
    ['travel','n','背包','bēibāo','กระเป๋าเป้','krapao pe','have'],
    ['travel','n','地图','dìtú','แผนที่','phaenthi','need'],
    ['travel','n','地址','dìzhǐ','ที่อยู่','thi yu','need'],
    ['travel','n','目的地','mùdìdì','จุดหมายปลายทาง','chutmai plaithang','need'],
    ['travel','n','预订','yùdìng','การจอง','kan chong','have'],
    ['travel','n','钥匙','yàoshi','กุญแจ','kunchae','need'],
    ['travel','n','房卡','fángkǎ','คีย์การ์ดห้องพัก','khi kat hong phak','need'],
    ['travel','n','押金','yājīn','เงินประกัน','ngoen prakan','need'],
    ['shopping','n','现金','xiànjīn','เงินสด','ngoen sot','have'],
    ['shopping','n','信用卡','xìnyòngkǎ','บัตรเครดิต','bat khredit','have'],
    ['shopping','n','二维码','èrwéimǎ','คิวอาร์โค้ด','khiu a kho','need'],
    ['shopping','n','收据','shōujù','ใบเสร็จ','baiset','need'],
    ['food','n','账单','zhàngdān','บิลค่าอาหาร','bin kha ahan','need'],
    ['daily','n','网络','wǎngluò','อินเทอร์เน็ต','inthanoet','need'],
    ['daily','n','密码','mìmǎ','รหัสผ่าน','rahat phan','need'],
    ['daily','n','充电器','chōngdiànqì','ที่ชาร์จ','thi chat','need'],
    ['daily','n','插座','chāzuò','ปลั๊กไฟ','plak fai','place'],
    ['daily','n','雨伞','yǔsǎn','ร่ม','rom','need'],

    // 051–075 · directions and time
    ['travel','n','左边','zuǒbian','ด้านซ้าย','dan sai','place'],
    ['travel','n','右边','yòubian','ด้านขวา','dan khwa','place'],
    ['travel','n','前面','qiánmiàn','ข้างหน้า','khang na','place'],
    ['travel','n','后面','hòumiàn','ข้างหลัง','khang lang','place'],
    ['travel','n','对面','duìmiàn','ฝั่งตรงข้าม','fang trongkham','place'],
    ['travel','n','附近','fùjìn','บริเวณใกล้เคียง','boriwen klaikhiang','place'],
    ['travel','n','里面','lǐmiàn','ด้านใน','dan nai','place'],
    ['travel','n','外面','wàimiàn','ด้านนอก','dan nok','place'],
    ['travel','n','楼上','lóushàng','ชั้นบน','chan bon','place'],
    ['travel','n','楼下','lóuxià','ชั้นล่าง','chan lang','place'],
    ['travel','v','直走','zhí zǒu','เดินตรงไป','doen trong pai','please'],
    ['travel','v','转弯','zhuǎnwān','เลี้ยว','liao','please'],
    ['travel','v','过马路','guò mǎlù','ข้ามถนน','kham thanon','do'],
    ['travel','v','上车','shàng chē','ขึ้นรถ','khuen rot','do'],
    ['travel','v','下车','xià chē','ลงรถ','long rot','do'],
    ['travel','v','换乘','huànchéng','ต่อรถ','to rot','do'],
    ['travel','v','出发','chūfā','ออกเดินทาง','ok doen thang','do'],
    ['travel','v','到达','dàodá','เดินทางถึง','doen thang thueng','do'],
    ['travel','v','迷路','mílù','หลงทาง','long thang','lostWay'],
    ['time','phrase','赶时间','gǎn shíjiān','กำลังรีบ','kamlang rip','say'],
    ['time','n','现在','xiànzài','ตอนนี้','ton ni','time'],
    ['time','n','今天','jīntiān','วันนี้','wan ni','time'],
    ['time','n','明天','míngtiān','พรุ่งนี้','phrung ni','time'],
    ['time','n','早上','zǎoshang','ตอนเช้า','ton chao','time'],
    ['time','n','晚上','wǎnshang','ตอนเย็น','ton yen','time'],

    // 076–100 · travel actions
    ['travel','v','订票','dìng piào','จองตั๋ว','chong tua','do'],
    ['travel','v','退房','tuì fáng','เช็กเอาต์','chek ao','do'],
    ['travel','v','延长住宿','yáncháng zhùsù','ต่อระยะเวลาพัก','to raya wela phak','do'],
    ['travel','v','取消','qǔxiāo','ยกเลิก','yok loek','do'],
    ['travel','v','确认','quèrèn','ยืนยัน','yuenyan','please'],
    ['travel','v','搭乘','dāchéng','โดยสาร','doisan','do'],
    ['travel','v','驾驶','jiàshǐ','ขับขี่','khap khi','daily'],
    ['travel','v','停车','tíng chē','จอดรถ','chot rot','please'],
    ['travel','v','等候','děnghòu','รอคอย','ro khoi','please'],
    ['travel','v','排队','pái duì','ต่อแถว','to thaeo','daily'],
    ['travel','v','问路','wèn lù','ถามทาง','tham thang','do'],
    ['travel','v','带路','dài lù','นำทาง','nam thang','please'],
    ['travel','v','拍照','pāi zhào','ถ่ายรูป','thai rup','do'],
    ['culture','v','参观','cānguān','เข้าชม','khao chom','do'],
    ['travel','v','游览','yóulǎn','เที่ยวชม','thiao chom','daily'],
    ['travel','v','租用','zūyòng','เช่าใช้','chao chai','do'],
    ['travel','v','归还','guīhuán','คืนของ','khuen khong','please'],
    ['emergency','v','遗失','yíshī','สูญหาย','sunhai','lostItem'],
    ['travel','v','寻找','xúnzhǎo','ตามหา','tam ha','daily'],
    ['travel','v','携带','xiédài','พกติดตัว','phok tittua','daily'],
    ['travel','v','托运','tuōyùn','โหลดสัมภาระ','lot samphara','do'],
    ['shopping','v','取款','qǔ kuǎn','ถอนเงิน','thon ngoen','do'],
    ['shopping','v','换钱','huàn qián','แลกเงิน','laek ngoen','do'],
    ['shopping','v','付款','fù kuǎn','ชำระเงิน','chamra ngoen','do'],
    ['shopping','v','刷卡','shuā kǎ','รูดบัตร','rut bat','do'],

    // 101–125 · food essentials
    ['food','n','菜单','càidān','เมนู','menu','need'],
    ['food','n','饮料','yǐnliào','เครื่องดื่ม','khrueang duem','want'],
    ['food','n','矿泉水','kuàngquánshuǐ','น้ำแร่','nam rae','food'],
    ['food','n','咖啡','kāfēi','กาแฟ','kafae','food'],
    ['food','n','茶','chá','ชา','cha','food'],
    ['food','n','牛奶','niúnǎi','นม','nom','food'],
    ['food','n','果汁','guǒzhī','น้ำผลไม้','nam phonlamai','food'],
    ['food','n','米饭','mǐfàn','ข้าวสวย','khao suai','food'],
    ['food','n','面条','miàntiáo','ก๋วยเตี๋ยว','kuaitiao','food'],
    ['food','n','炒饭','chǎofàn','ข้าวผัด','khao phat','food'],
    ['food','n','汤','tāng','ซุป','sup','food'],
    ['food','n','鸡肉','jīròu','เนื้อไก่','nuea kai','food'],
    ['food','n','猪肉','zhūròu','เนื้อหมู','nuea mu','food'],
    ['food','n','牛肉','niúròu','เนื้อวัว','nuea wua','food'],
    ['food','n','鱼','yú','ปลา','pla','food'],
    ['food','n','虾','xiā','กุ้ง','kung','food'],
    ['food','n','鸡蛋','jīdàn','ไข่ไก่','khai kai','food'],
    ['food','n','蔬菜','shūcài','ผัก','phak','food'],
    ['food','n','水果','shuǐguǒ','ผลไม้','phonlamai','food'],
    ['food','n','甜点','tiándiǎn','ของหวาน','khong wan','food'],
    ['food','n','早餐','zǎocān','อาหารเช้า','ahan chao','food'],
    ['food','n','午餐','wǔcān','อาหารกลางวัน','ahan klangwan','food'],
    ['food','n','晚餐','wǎncān','อาหารเย็น','ahan yen','food'],
    ['food','n','小吃','xiǎochī','ของกินเล่น','khong kin len','food'],
    ['food','n','素食','sùshí','อาหารมังสวิรัติ','ahan mangsawirat','food'],

    // 126–150 · restaurant use
    ['food','v','点菜','diǎn cài','สั่งอาหาร','sang ahan','do'],
    ['food','v','加菜','jiā cài','สั่งเพิ่ม','sang phoem','do'],
    ['food','v','打包','dǎbāo','ห่อกลับบ้าน','ho klap ban','please'],
    ['food','v','结账','jiézhàng','คิดเงิน','khit ngoen','please'],
    ['food','phrase','预约座位','yùyuē zuòwèi','จองโต๊ะล่วงหน้า','chong to luang na','do'],
    ['food','n','空位','kòngwèi','ที่นั่งว่าง','thi nang wang','have'],
    ['food','phrase','靠窗','kào chuāng','ติดหน้าต่าง','tit natang','want'],
    ['food','phrase','少辣','shǎo là','เผ็ดน้อย','phet noi','say'],
    ['food','phrase','不辣','bú là','ไม่เผ็ด','mai phet','say'],
    ['food','phrase','多辣','duō là','เผ็ดมาก','phet mak','say'],
    ['food','phrase','不加糖','bù jiā táng','ไม่ใส่น้ำตาล','mai sai namtan','say'],
    ['food','phrase','少冰','shǎo bīng','น้ำแข็งน้อย','namkhaeng noi','say'],
    ['food','adj','热的','rè de','แบบร้อน','baep ron','want'],
    ['food','adj','冷的','lěng de','แบบเย็น','baep yen','want'],
    ['health','v','过敏','guòmǐn','แพ้','phae','allergy','“过敏”后常接“对……”说明过敏原。','คำว่า แพ้ ควรตามด้วยสิ่งที่แพ้'],
    ['food','adj','好吃','hǎochī','อร่อย','aroi','adj'],
    ['food','adj','太咸','tài xián','เค็มเกินไป','khem koen pai','say'],
    ['food','adj','太甜','tài tián','หวานเกินไป','wan koen pai','say'],
    ['food','adj','新鲜','xīnxiān','สดใหม่','sot mai','adj'],
    ['food','adj','熟了','shú le','สุกแล้ว','suk laeo','say'],
    ['food','n','筷子','kuàizi','ตะเกียบ','takiap','need'],
    ['food','n','勺子','sháozi','ช้อน','chon','need'],
    ['food','n','叉子','chāzi','ส้อม','som','need'],
    ['food','n','盘子','pánzi','จาน','chan','need'],
    ['food','n','杯子','bēizi','แก้วน้ำ','kaeo nam','need'],

    // 151–175 · shopping
    ['shopping','n','价格','jiàgé','ราคา','rakha','need'],
    ['shopping','n','折扣','zhékòu','ส่วนลด','suan lot','have'],
    ['shopping','n','促销','cùxiāo','โปรโมชัน','promotion','have'],
    ['shopping','n','尺寸','chǐcùn','ขนาด','khanat','need'],
    ['shopping','n','颜色','yánsè','สี','si','need'],
    ['shopping','n','款式','kuǎnshì','แบบสินค้า','baep sinkha','need'],
    ['shopping','n','质量','zhìliàng','คุณภาพ','khunnaphap','need'],
    ['shopping','n','保修','bǎoxiū','การรับประกัน','kan rapprakan','have'],
    ['shopping','v','退货','tuì huò','คืนสินค้า','khuen sinkha','do'],
    ['shopping','v','换货','huàn huò','เปลี่ยนสินค้า','plian sinkha','do'],
    ['shopping','v','试穿','shì chuān','ลองสวม','long suam','do'],
    ['shopping','adj','合适','héshì','พอดี','phodi','feel'],
    ['shopping','adj','太大','tài dà','ใหญ่เกินไป','yai koen pai','say'],
    ['shopping','adj','太小','tài xiǎo','เล็กเกินไป','lek koen pai','say'],
    ['shopping','adj','便宜','piányi','ราคาถูก','rakha thuk','adj','“便宜”读轻声 yi。','พยางค์ท้ายของ 便宜 เป็นเสียงเบา'],
    ['shopping','adj','昂贵','ángguì','ราคาแพง','rakha phaeng','adj'],
    ['shopping','n','零钱','língqián','เงินทอน','ngoen thon','need'],
    ['shopping','n','购物袋','gòuwùdài','ถุงช้อปปิ้ง','thung shopping','need'],
    ['shopping','n','纪念品','jìniànpǐn','ของที่ระลึก','khong thiraluek','buy'],
    ['shopping','n','衣服','yīfu','เสื้อผ้า','sueapha','buy'],
    ['shopping','n','鞋子','xiézi','รองเท้า','rongthao','buy'],
    ['shopping','n','帽子','màozi','หมวก','muak','buy'],
    ['travel','n','手机卡','shǒujīkǎ','ซิมการ์ด','sim kat','buy'],
    ['travel','n','流量套餐','liúliàng tàocān','แพ็กเกจอินเทอร์เน็ต','phaekket inthanoet','buy'],
    ['shopping','n','商场','shāngchǎng','ศูนย์การค้า','sun kankha','place'],

    // 176–200 · people and social actions
    ['people','n','朋友','péngyou','เพื่อน','phuean','person'],
    ['people','n','同学','tóngxué','เพื่อนร่วมชั้น','phuean ruam chan','person'],
    ['people','n','同事','tóngshì','เพื่อนร่วมงาน','phuean ruam ngan','person'],
    ['people','n','邻居','línjū','เพื่อนบ้าน','phuean ban','person'],
    ['people','n','家人','jiārén','ครอบครัว','khropkhrua','person'],
    ['people','n','男朋友','nánpéngyou','แฟนผู้ชาย','faen phuchai','person'],
    ['people','n','女朋友','nǚpéngyou','แฟนผู้หญิง','faen phuying','person'],
    ['social','n','名字','míngzi','ชื่อ','chue','need'],
    ['social','n','国家','guójiā','ประเทศ','prathet','culture'],
    ['social','n','家乡','jiāxiāng','บ้านเกิด','ban koet','culture'],
    ['social','n','爱好','àihào','งานอดิเรก','ngan adirek','culture'],
    ['social','n','职业','zhíyè','อาชีพ','achip','culture'],
    ['social','n','年龄','niánlíng','อายุ','ayu','need'],
    ['social','n','联系方式','liánxì fāngshì','ช่องทางติดต่อ','chongthang titto','need'],
    ['social','n','微信','Wēixìn','วีแชต','wichat','have'],
    ['social','v','认识','rènshi','รู้จัก','ruchak','do'],
    ['social','v','介绍','jièshào','แนะนำตัว','naenam tua','do'],
    ['social','v','聊天','liáotiān','พูดคุย','phutkhui','do'],
    ['social','v','邀请','yāoqǐng','เชิญชวน','choenchuan','do'],
    ['social','v','见面','jiànmiàn','พบกัน','phop kan','do'],
    ['social','adv','一起','yìqǐ','ด้วยกัน','duai kan','say'],
    ['social','phrase','欢迎','huānyíng','ยินดีต้อนรับ','yindi tonrap','say'],
    ['social','phrase','恭喜','gōngxǐ','ยินดีด้วย','yindi duai','say'],
    ['social','phrase','保重','bǎozhòng','ดูแลตัวเองด้วย','dulae tuaeng duai','say'],
    ['travel','phrase','一路顺风','yí lù shùnfēng','เดินทางโดยสวัสดิภาพ','doen thang doi sawatdiphap','say'],

    // 201–225 · ready-to-use social phrases
    ['social','phrase','你好','nǐ hǎo','สวัสดี','sawatdi','say'],
    ['social','phrase','早上好','zǎoshang hǎo','สวัสดีตอนเช้า','sawatdi ton chao','say'],
    ['social','phrase','晚上好','wǎnshang hǎo','สวัสดีตอนเย็น','sawatdi ton yen','say'],
    ['social','phrase','再见','zàijiàn','ลาก่อน','la kon','say'],
    ['social','phrase','谢谢','xièxie','ขอบคุณ','khopkhun','say'],
    ['social','phrase','不客气','bú kèqi','ไม่เป็นไร','mai pen rai','say'],
    ['social','phrase','对不起','duìbuqǐ','ขอโทษ','kho thot','say'],
    ['social','phrase','没关系','méi guānxi','ไม่เป็นอะไร','mai pen arai','say'],
    ['social','phrase','请问','qǐngwèn','ขอถามหน่อย','kho tham noi','say','“请问”常用于礼貌地开启问题。','请问 ใช้เปิดคำถามอย่างสุภาพ'],
    ['social','phrase','麻烦你了','máfan nǐ le','รบกวนคุณด้วย','ropkuan khun duai','say'],
    ['social','phrase','很高兴认识你','hěn gāoxìng rènshi nǐ','ยินดีที่ได้รู้จัก','yindi thi dai ruchak','say'],
    ['social','phrase','你叫什么名字','nǐ jiào shénme míngzi','คุณชื่ออะไร','khun chue arai','say'],
    ['social','phrase','你从哪里来','nǐ cóng nǎlǐ lái','คุณมาจากที่ไหน','khun ma chak thi nai','say'],
    ['social','phrase','我来自泰国','wǒ láizì Tàiguó','ฉันมาจากประเทศไทย','chan ma chak prathet thai','say'],
    ['study','phrase','你会说中文吗','nǐ huì shuō Zhōngwén ma','คุณพูดภาษาจีนได้ไหม','khun phut phasa chin dai mai','say'],
    ['study','phrase','请说慢一点','qǐng shuō màn yìdiǎn','กรุณาพูดช้าลงหน่อย','karuna phut cha long noi','say'],
    ['study','phrase','请再说一遍','qǐng zài shuō yí biàn','กรุณาพูดอีกครั้ง','karuna phut ik khrang','say'],
    ['study','phrase','我没听懂','wǒ méi tīng dǒng','ฉันฟังไม่เข้าใจ','chan fang mai khaochai','say'],
    ['study','phrase','这是什么意思','zhè shì shénme yìsi','นี่หมายความว่าอะไร','ni maikhwam wa arai','say'],
    ['study','phrase','怎么说','zěnme shuō','พูดว่าอย่างไร','phut wa yangrai','say'],
    ['social','phrase','我可以加你微信吗','wǒ kěyǐ jiā nǐ Wēixìn ma','ขอแอดวีแชตคุณได้ไหม','kho aet wichat khun dai mai','say'],
    ['social','phrase','有空一起吃饭吗','yǒu kòng yìqǐ chīfàn ma','ว่างไปกินข้าวด้วยกันไหม','wang pai kin khao duai kan mai','say'],
    ['social','phrase','下次见','xià cì jiàn','เจอกันครั้งหน้า','choe kan khrang na','say'],
    ['social','phrase','祝你玩得开心','zhù nǐ wán de kāixīn','ขอให้เที่ยวให้สนุก','kho hai thiao hai sanuk','say'],
    ['social','phrase','保持联系','bǎochí liánxì','ติดต่อกันไว้นะ','titto kan wai na','say'],

    // 226–250 · emergency and culture
    ['emergency','phrase','救命','jiùmìng','ช่วยด้วย','chuai duai','say'],
    ['emergency','v','报警','bào jǐng','แจ้งตำรวจ','chaeng tamruat','please'],
    ['emergency','phrase','叫救护车','jiào jiùhùchē','เรียกรถพยาบาล','riak rot phayaban','please'],
    ['emergency','phrase','我受伤了','wǒ shòushāng le','ฉันได้รับบาดเจ็บ','chan dai rap batchaep','say'],
    ['emergency','phrase','有人晕倒了','yǒu rén yūndǎo le','มีคนเป็นลม','mi khon pen lom','say'],
    ['emergency','phrase','呼吸困难','hūxī kùnnan','หายใจลำบาก','haichai lambak','say'],
    ['emergency','phrase','过敏反应','guòmǐn fǎnyìng','อาการแพ้รุนแรง','akan phae runraeng','say'],
    ['emergency','phrase','丢了护照','diū le hùzhào','ทำหนังสือเดินทางหาย','tham nangsue doen thang hai','say'],
    ['emergency','phrase','钱包被偷了','qiánbāo bèi tōu le','กระเป๋าสตางค์ถูกขโมย','krapao satang thuk khamoi','say'],
    ['emergency','phrase','我找不到路','wǒ zhǎo bú dào lù','ฉันหาทางไม่เจอ','chan ha thang mai choe','say'],
    ['emergency','phrase','请帮帮我','qǐng bāngbang wǒ','กรุณาช่วยฉันด้วย','karuna chuai chan duai','say'],
    ['emergency','phrase','这里危险','zhèlǐ wēixiǎn','ตรงนี้อันตราย','trong ni antarai','say'],
    ['emergency','phrase','发生火灾','fāshēng huǒzāi','เกิดเพลิงไหม้','koet phloeng mai','say'],
    ['emergency','phrase','马上离开','mǎshàng líkāi','ออกไปทันที','ok pai thanthi','say'],
    ['emergency','phrase','不要动','bú yào dòng','อย่าขยับ','ya khayap','say'],
    ['emergency','phrase','小心','xiǎoxīn','ระวัง','rawang','say'],
    ['emergency','n','紧急出口','jǐnjí chūkǒu','ทางออกฉุกเฉิน','thang ok chukchoen','place'],
    ['emergency','n','事故','shìgù','อุบัติเหตุ','ubattihet','have'],
    ['emergency','phrase','地址是','dìzhǐ shì','ที่อยู่คือ','thi yu khue','say'],
    ['emergency','phrase','我不会游泳','wǒ bú huì yóuyǒng','ฉันว่ายน้ำไม่เป็น','chan wai nam mai pen','say'],
    ['culture','n','传统','chuántǒng','ประเพณี','prapheni','culture'],
    ['culture','n','节日','jiérì','เทศกาล','thetsakan','culture'],
    ['culture','n','寺庙','sìmiào','วัด','wat','culture'],
    ['culture','n','礼貌','lǐmào','มารยาท','marayat','culture'],
    ['culture','n','禁忌','jìnjì','ข้อห้ามทางสังคม','kho ham thang sangkhom','culture']
  ];

  const L4 = [
    // 001–025 · workplace people and places
    ['work','n','公司','gōngsī','บริษัท','borisat','culture'],
    ['work','n','办公室','bàngōngshì','สำนักงาน','samnakngan','place'],
    ['work','n','会议室','huìyìshì','ห้องประชุม','hong prachum','place'],
    ['work','n','接待处','jiēdàichù','จุดประชาสัมพันธ์','chut prachasamphan','place'],
    ['people','n','经理','jīnglǐ','ผู้จัดการ','phuchatkan','person'],
    ['people','n','主管','zhǔguǎn','หัวหน้างาน','huana ngan','person'],
    ['people','n','客户','kèhù','ลูกค้า','lukkha','person'],
    ['people','n','供应商','gōngyìngshāng','ผู้จัดจำหน่าย','phuchat chamnai','person'],
    ['people','n','合作伙伴','hézuò huǒbàn','พันธมิตรทางธุรกิจ','phanthamit thang thurakit','person'],
    ['work','n','团队','tuánduì','ทีมงาน','thim ngan','culture'],
    ['work','n','部门','bùmén','แผนก','phanaek','culture'],
    ['work','n','人力资源','rénlì zīyuán','ฝ่ายทรัพยากรบุคคล','fai sapphayakon bukkhon','culture'],
    ['work','n','财务部','cáiwùbù','ฝ่ายการเงิน','fai kanngoen','culture'],
    ['work','n','市场部','shìchǎngbù','ฝ่ายการตลาด','fai kantalat','culture'],
    ['work','n','技术部','jìshùbù','ฝ่ายเทคนิค','fai theknik','culture'],
    ['work','n','销售部','xiāoshòubù','ฝ่ายขาย','fai khai','culture'],
    ['work','n','行政部','xíngzhèngbù','ฝ่ายธุรการ','fai thurakan','culture'],
    ['people','n','实习生','shíxíshēng','นักศึกษาฝึกงาน','naksueksa fuekngan','person'],
    ['people','n','负责人','fùzérén','ผู้รับผิดชอบ','phurapphitchop','person'],
    ['people','n','董事','dǒngshì','กรรมการบริษัท','kammakan borisat','person'],
    ['people','n','助理','zhùlǐ','ผู้ช่วย','phuchuai','person'],
    ['people','n','秘书','mìshū','เลขานุการ','lekhanuakan','person'],
    ['people','n','顾问','gùwèn','ที่ปรึกษา','thi prueksa','person'],
    ['people','n','面试官','miànshìguān','ผู้สัมภาษณ์','phusamphat','person'],
    ['people','n','候选人','hòuxuǎnrén','ผู้สมัครที่ได้รับคัดเลือก','phusamak thi dai rap khat lueak','person'],

    // 026–050 · work documents and deliverables
    ['work','n','文件','wénjiàn','เอกสาร','ekasan','workdoc'],
    ['work','n','报告','bàogào','รายงาน','raingan','workdoc'],
    ['work','n','合同','hétong','สัญญา','sanya','workdoc'],
    ['work','n','发票','fāpiào','ใบกำกับภาษี','bai kamkap phasi','workdoc','中国的“发票”通常指正式税务凭证。','发票 ในจีนมักหมายถึงเอกสารภาษีอย่างเป็นทางการ'],
    ['work','n','预算','yùsuàn','งบประมาณ','ngoppraman','workdoc'],
    ['work','n','报价','bàojià','ใบเสนอราคา','bai sanoe rakha','workdoc'],
    ['work','n','订单','dìngdān','คำสั่งซื้อ','khamsang sue','workdoc'],
    ['work','n','数据','shùjù','ข้อมูล','khomun','workdoc'],
    ['work','n','表格','biǎogé','แบบฟอร์ม','baep fom','workdoc'],
    ['work','n','附件','fùjiàn','ไฟล์แนบ','fai naep','workdoc'],
    ['work','n','邮件','yóujiàn','อีเมล','imel','workdoc'],
    ['time','n','日程','rìchéng','ตารางเวลา','tarang wela','workdoc'],
    ['work','n','议程','yìchéng','ระเบียบวาระ','rabiap wara','workdoc'],
    ['work','n','会议纪要','huìyì jìyào','บันทึกการประชุม','banthuek kan prachum','workdoc'],
    ['work','n','方案','fāngàn','แนวทางดำเนินงาน','naeo thang damnoen ngan','workdoc'],
    ['work','n','计划','jìhuà','แผนงาน','phaen ngan','workdoc'],
    ['work','n','目标','mùbiāo','เป้าหมาย','paomai','workdoc'],
    ['work','n','任务','rènwu','ภารกิจงาน','pharakit ngan','workdoc'],
    ['work','n','项目','xiàngmù','โครงการ','khrongkan','workdoc'],
    ['work','n','进度','jìndù','ความคืบหน้า','khwam khuepna','workdoc'],
    ['time','n','截止日期','jiézhǐ rìqī','วันกำหนดส่ง','wan kamnot song','workdoc'],
    ['work','n','版本','bǎnběn','เวอร์ชัน','woechan','workdoc'],
    ['work','n','模板','múbǎn','แม่แบบ','mae baep','workdoc'],
    ['work','n','签名','qiānmíng','ลายเซ็น','lai sen','need'],
    ['work','n','印章','yìnzhāng','ตราประทับ','tra prathap','need'],

    // 051–075 · work actions
    ['work','v','安排','ānpái','จัดเตรียม','chat triam','workdo'],
    ['work','v','核实','héshí','ตรวจยืนยัน','truat yuenyan','workdo'],
    ['work','v','通知','tōngzhī','แจ้งให้ทราบ','chaeng hai sap','workdo'],
    ['work','v','回复','huífù','ตอบกลับ','top klap','workdo'],
    ['work','v','转发','zhuǎnfā','ส่งต่อ','song to','workdo'],
    ['work','v','提交','tíjiāo','ยื่นส่ง','yuen song','workdo'],
    ['work','v','批准','pīzhǔn','อนุมัติ','anumat','workdo'],
    ['work','v','拒绝','jùjué','ปฏิเสธ','patiset','workdo'],
    ['work','v','修改','xiūgǎi','แก้ไข','kaekhai','workdo'],
    ['work','v','更新','gēngxīn','อัปเดต','apdet','workdo'],
    ['work','v','检查','jiǎnchá','ตรวจสอบ','truatsop','workdo'],
    ['work','v','核对','héduì','ตรวจเทียบ','truat thiap','workdo'],
    ['work','v','打印','dǎyìn','พิมพ์เอกสาร','phim ekasan','workdo'],
    ['work','v','复印','fùyìn','ถ่ายสำเนา','thai samnao','workdo'],
    ['work','v','扫描','sǎomiáo','สแกน','sakaen','workdo'],
    ['work','v','签署','qiānshǔ','ลงนาม','long nam','workdo'],
    ['work','v','讨论','tǎolùn','หารือ','harue','workdo'],
    ['work','v','汇报','huìbào','รายงานต่อ','raingan to','workdo'],
    ['work','v','总结','zǒngjié','สรุปผล','sarup phon','workdo'],
    ['work','v','分析','fēnxī','วิเคราะห์','wikhro','workdo'],
    ['work','v','比较','bǐjiào','เปรียบเทียบ','priapthiap','workdo'],
    ['work','v','解决','jiějué','แก้ปัญหา','kae panha','workdo'],
    ['work','v','跟进','gēnjìn','ติดตามงาน','tittam ngan','workdo'],
    ['work','v','协调','xiétiáo','ประสานงาน','prasan ngan','workdo'],
    ['work','v','推迟','tuīchí','เลื่อนออกไป','luean ok pai','workdo'],

    // 076–100 · workplace routines
    ['work','v','开会','kāi huì','ประชุม','prachum','workdo'],
    ['work','v','出差','chū chāi','เดินทางไปทำงานต่างพื้นที่','doen thang pai thamngan tang phuenthi','workdo'],
    ['work','v','加班','jiā bān','ทำงานล่วงเวลา','thamngan luang wela','workdo'],
    ['work','v','请假','qǐng jià','ขอลางาน','kho la ngan','workdo'],
    ['work','v','迟到','chídào','มาสาย','ma sai','late'],
    ['work','v','早退','zǎotuì','กลับก่อนเวลา','klap kon wela','earlyLeave'],
    ['work','v','入职','rùzhí','เริ่มงาน','roem ngan','workdo'],
    ['work','v','离职','lízhí','ออกจากงาน','ok chak ngan','workdo'],
    ['work','n','培训','péixùn','การอบรม','kan oprom','have'],
    ['work','n','招聘','zhāopìn','การรับสมัครงาน','kan rap samak ngan','culture'],
    ['work','n','面试','miànshì','การสัมภาษณ์งาน','kan samphat ngan','have'],
    ['work','n','试用期','shìyòngqī','ช่วงทดลองงาน','chuang thotlong ngan','culture'],
    ['work','n','工资','gōngzī','เงินเดือน','ngoen duean','need'],
    ['work','n','奖金','jiǎngjīn','เงินโบนัส','ngoen bonus','have'],
    ['work','n','福利','fúlì','สวัสดิการพนักงาน','sawatdikan phanakngan','culture'],
    ['time','n','假期','jiàqī','วันหยุดพักผ่อน','wan yut phakphon','need'],
    ['work','v','值班','zhí bān','เข้าเวร','khao wen','workdo'],
    ['work','v','轮班','lún bān','ทำงานเป็นกะ','thamngan pen ka','daily'],
    ['work','phrase','远程办公','yuǎnchéng bàngōng','ทำงานทางไกล','thamngan thang klai','say'],
    ['work','n','工作量','gōngzuòliàng','ปริมาณงาน','pariman ngan','need'],
    ['work','n','优先级','yōuxiānjí','ระดับความสำคัญ','radap khwam samkhan','need'],
    ['work','n','责任','zérèn','ความรับผิดชอบ','khwam rapphitchop','culture'],
    ['work','n','权限','quánxiàn','สิทธิ์การเข้าถึง','sit kan khaothueng','need'],
    ['work','n','流程','liúchéng','ขั้นตอนการทำงาน','khanton kan thamngan','culture'],
    ['work','n','效率','xiàolǜ','ประสิทธิภาพ','prasitthiphap','culture'],

    // 101–125 · study and professional learning
    ['study','n','课程','kèchéng','หลักสูตร','laksut','study'],
    ['study','n','教材','jiàocái','ตำราเรียน','tamra rian','study'],
    ['study','n','作业','zuòyè','การบ้าน','kanban','homework'],
    ['study','n','考试','kǎoshì','การสอบ','kan sop','study'],
    ['study','n','成绩','chéngjì','ผลการเรียน','phon kan rian','need'],
    ['study','n','证书','zhèngshū','ใบรับรอง','bai raprong','need'],
    ['study','n','学期','xuéqī','ภาคการศึกษา','phak kansueksa','culture'],
    ['study','n','主修科目','zhǔxiū kēmù','วิชาเอก','wicha ek','study'],
    ['people','n','老师','lǎoshī','อาจารย์','achan','person'],
    ['people','n','学生','xuésheng','ผู้เรียน','phurian','person'],
    ['study','n','教室','jiàoshì','ห้องเรียน','hong rian','place'],
    ['study','n','图书馆','túshūguǎn','หอสมุด','ho samut','place'],
    ['study','n','实验室','shíyànshì','ห้องปฏิบัติการ','hong patibatkan','place'],
    ['study','n','讲座','jiǎngzuò','การบรรยาย','kan banyai','have'],
    ['study','n','笔记','bǐjì','บันทึกย่อ','banthuek yo','need'],
    ['study','n','词汇','cíhuì','คำศัพท์','kham sap','study'],
    ['study','n','语法','yǔfǎ','ไวยากรณ์','waiyakon','study'],
    ['study','n','发音','fāyīn','การออกเสียง','kan ok siang','study'],
    ['study','n','听力','tīnglì','ทักษะการฟัง','thaksa kan fang','study'],
    ['study','n','口语','kǒuyǔ','ภาษาพูด','phasa phut','study'],
    ['study','n','阅读','yuèdú','การอ่าน','kan an','study'],
    ['study','n','写作','xiězuò','การเขียน','kan khian','study'],
    ['study','n','翻译','fānyì','การแปล','kan plae','study'],
    ['study','n','练习','liànxí','แบบฝึกหัด','baep fuekhat','study'],
    ['study','v','复习','fùxí','ทบทวนบทเรียน','thopthuan botrian','daily'],

    // 126–150 · home and daily life
    ['daily','n','公寓','gōngyù','อพาร์ตเมนต์','aphatmen','place'],
    ['daily','n','房租','fángzū','ค่าเช่า','kha chao','need'],
    ['people','n','房东','fángdōng','เจ้าของห้องเช่า','chaokhong hong chao','person'],
    ['people','n','室友','shìyǒu','เพื่อนร่วมห้อง','phuean ruam hong','person'],
    ['daily','n','家具','jiājù','เครื่องเรือน','khrueang ruean','need'],
    ['daily','n','厨房','chúfáng','ห้องครัว','hong khrua','place'],
    ['daily','n','卧室','wòshì','ห้องนอน','hong non','place'],
    ['daily','n','客厅','kètīng','ห้องนั่งเล่น','hong nang len','place'],
    ['daily','n','阳台','yángtái','ระเบียง','rabiang','place'],
    ['daily','n','空调','kōngtiáo','เครื่องปรับอากาศ','khrueang prap akat','need'],
    ['daily','n','冰箱','bīngxiāng','ตู้เย็น','tu yen','need'],
    ['daily','n','洗衣机','xǐyījī','เครื่องซักผ้า','khrueang sak pha','need'],
    ['daily','n','热水器','rèshuǐqì','เครื่องทำน้ำอุ่น','khrueang tham nam un','need'],
    ['daily','n','水费','shuǐfèi','ค่าน้ำ','kha nam','need'],
    ['daily','n','电费','diànfèi','ค่าไฟ','kha fai','need'],
    ['daily','n','维修','wéixiū','บริการซ่อม','borikan som','need'],
    ['daily','v','清洁','qīngjié','ทำความสะอาด','tham khwam sa-at','cleanRoom'],
    ['daily','n','垃圾','lājī','ขยะ','khaya','have'],
    ['daily','n','快递','kuàidì','บริการส่งด่วน','borikan song duan','have'],
    ['daily','n','包裹','bāoguǒ','พัสดุ','phatsadu','have'],
    ['daily','n','门禁','ménjìn','ระบบควบคุมทางเข้า','rabop khuapkhum thang khao','need'],
    ['daily','n','社区','shèqū','ชุมชนที่พักอาศัย','chumchon thi phak asai','culture'],
    ['daily','n','便利','biànlì','ความสะดวกสบาย','khwam saduak sabai','culture'],
    ['daily','n','噪音','zàoyīn','เสียงรบกวน','siang ropkuan','have'],
    ['daily','v','搬家','bān jiā','ย้ายบ้าน','yai ban','moveNextMonth'],

    // 151–175 · health and wellbeing
    ['health','n','症状','zhèngzhuàng','อาการเจ็บป่วย','akan chep puai','need'],
    ['health','n','发烧','fāshāo','มีไข้','mi khai','health'],
    ['health','n','咳嗽','késou','ไอ','ai','health'],
    ['health','n','头痛','tóutòng','ปวดศีรษะ','puat sisa','health'],
    ['health','n','肚子痛','dùzi tòng','ปวดท้อง','puat thong','health'],
    ['health','n','喉咙痛','hóulong tòng','เจ็บคอ','chep kho','health'],
    ['health','n','感冒','gǎnmào','เป็นหวัด','pen wat','health'],
    ['health','n','药物','yàowù','ยารักษาโรค','ya raksa rok','need'],
    ['health','n','处方','chǔfāng','ใบสั่งยา','bai sang ya','need'],
    ['people','n','医生','yīshēng','แพทย์','phaet','person'],
    ['people','n','护士','hùshi','พยาบาล','phayaban','person'],
    ['health','phrase','预约医生','yùyuē yīshēng','นัดพบแพทย์','nat phop phaet','say'],
    ['health','n','体温','tǐwēn','อุณหภูมิร่างกาย','unhaphum rangkai','need'],
    ['health','n','血压','xuèyā','ความดันโลหิต','khwam dan lohit','need'],
    ['health','v','休息','xiūxi','พักผ่อน','phakphon','daily'],
    ['health','n','睡眠','shuìmián','การนอนหลับ','kan non lap','culture'],
    ['health','v','锻炼','duànliàn','ออกกำลังกาย','ok kamlangkai','daily'],
    ['health','n','健康','jiànkāng','สุขภาพแข็งแรง','sukkhaphap khaengraeng','culture'],
    ['health','n','保险','bǎoxiǎn','ประกันสุขภาพ','prakan sukkhaphap','need'],
    ['health','n','医疗费','yīliáofèi','ค่ารักษาพยาบาล','kha raksa phayaban','need'],
    ['health','n','慢性病','mànxìngbìng','โรคเรื้อรัง','rok ruearang','have'],
    ['people','n','牙医','yáyī','ทันตแพทย์','thantaphaet','person'],
    ['health','phrase','检查身体','jiǎnchá shēntǐ','ตรวจสุขภาพประจำปี','truat sukkhaphap pracham pi','say'],
    ['health','n','康复','kāngfù','การฟื้นฟูร่างกาย','kan fuenfu rangkai','culture'],
    ['health','n','压力','yālì','ความเครียด','khwam khriat','have'],

    // 176–200 · useful time phrases
    ['time','phrase','十分钟','shí fēnzhōng','สิบนาที','sip nathi','say'],
    ['time','phrase','一个小时','yí ge xiǎoshí','หนึ่งชั่วโมง','nueng chuamong','say'],
    ['time','phrase','确认日期','quèrèn rìqī','ยืนยันวันที่','yuenyan wanthi','say'],
    ['time','phrase','这个星期','zhège xīngqī','สัปดาห์นี้','sapda ni','say'],
    ['time','phrase','下个月','xià ge yuè','เดือนหน้า','duean na','say'],
    ['time','phrase','本季度','běn jìdù','ไตรมาสนี้','traimat ni','say'],
    ['time','phrase','今年内','jīnnián nèi','ภายในปีนี้','phainai pi ni','say'],
    ['time','phrase','上午见','shàngwǔ jiàn','พบกันช่วงสาย','phop kan chuang sai','say'],
    ['time','phrase','下午开会','xiàwǔ kāi huì','ประชุมช่วงบ่าย','prachum chuang bai','say'],
    ['time','phrase','中午休息','zhōngwǔ xiūxi','พักเที่ยง','phak thiang','say'],
    ['time','phrase','凌晨到达','língchén dàodá','ถึงช่วงเช้ามืด','thueng chuang chao muet','say'],
    ['time','phrase','以前见过','yǐqián jiàn guo','เคยพบกันมาก่อน','khoei phop kan ma kon','say'],
    ['time','phrase','以后再说','yǐhòu zài shuō','ไว้ค่อยคุยกัน','wai khoi khui kan','say'],
    ['time','phrase','最近很忙','zuìjìn hěn máng','ช่วงนี้ยุ่งมาก','chuang ni yung mak','say'],
    ['time','phrase','通常如此','tōngcháng rúcǐ','โดยปกติเป็นแบบนี้','doi pokkati pen baep ni','say'],
    ['time','phrase','偶尔一次',"ǒu'ěr yí cì",'เป็นครั้งคราว','pen khrang khrao','say'],
    ['time','phrase','已经完成','yǐjīng wánchéng','เสร็จเรียบร้อยแล้ว','set riaproi laeo','say'],
    ['time','phrase','还没开始','hái méi kāishǐ','ยังไม่ได้เริ่ม','yang mai dai roem','say'],
    ['time','phrase','按时到达','ànshí dàodá','มาถึงตรงเวลา','ma thueng trong wela','say'],
    ['time','phrase','提前通知','tíqián tōngzhī','แจ้งล่วงหน้า','chaeng luang na','say'],
    ['time','phrase','暂时关闭','zànshí guānbì','ปิดชั่วคราว','pit chuakhrao','say'],
    ['time','phrase','长期合作','chángqī hézuò','ร่วมงานระยะยาว','ruam ngan raya yao','say'],
    ['time','phrase','短期计划','duǎnqī jìhuà','แผนระยะสั้น','phaen raya san','say'],
    ['time','phrase','按顺序','àn shùnxù','ตามลำดับ','tam lamdap','say'],
    ['time','phrase','同时进行','tóngshí jìnxíng','ดำเนินพร้อมกัน','damnoen phrom kan','say'],

    // 201–225 · work-ready qualities
    ['work','adj','重要','zhòngyào','สำคัญ','samkhan','importantPlace'],
    ['work','adj','紧急','jǐnjí','เร่งด่วน','rengduan','adj'],
    ['work','adj','准确','zhǔnquè','ถูกต้องแม่นยำ','thuktong maenyam','adj'],
    ['work','adj','清楚','qīngchu','ชัดเจน','chatchen','adj'],
    ['work','adj','完整','wánzhěng','ครบถ้วน','khropthuan','adj'],
    ['work','adj','详细','xiángxì','ละเอียด','laiat','adj'],
    ['work','adj','简单','jiǎndān','เรียบง่าย','riap ngai','adj'],
    ['work','adj','复杂','fùzá','ซับซ้อน','sapsorn','adj'],
    ['work','adj','有效','yǒuxiào','มีประสิทธิผล','mi prasitthiphon','adj'],
    ['work','adj','无效','wúxiào','ใช้ไม่ได้ผล','chai mai dai phon','adj'],
    ['work','adj','正式','zhèngshì','เป็นทางการ','pen thangkan','adj'],
    ['work','adj','灵活','línghuó','ยืดหยุ่น','yuetyun','adj'],
    ['work','adj','稳定','wěndìng','มั่นคง','mankhong','adj'],
    ['work','adj','安全','ānquán','ปลอดภัย','plotphai','adj'],
    ['work','adj','方便','fāngbiàn','สะดวก','saduak','adj'],
    ['work','adj','困难','kùnnan','ยากลำบาก','yak lambak','adj'],
    ['work','adj','顺利','shùnlì','ราบรื่น','rapruen','adj'],
    ['work','adj','及时','jíshí','ทันท่วงที','thanthuangthi','adj'],
    ['work','adj','主动','zhǔdòng','เชิงรุก','choeng ruk','adj'],
    ['work','adj','专业','zhuānyè','เป็นมืออาชีพ','pen mue achip','adj','作形容词时表示“专业、内行”。','เมื่อเป็นคำคุณศัพท์หมายถึงเป็นมืออาชีพ'],
    ['work','adj','负责','fùzé','มีความรับผิดชอบ','mi khwam rapphitchop','adj'],
    ['work','adj','耐心','nàixīn','ใจเย็นอดทน','chai yen otthon','adj'],
    ['work','adj','认真','rènzhēn','ตั้งใจจริง','tangchai ching','adj'],
    ['work','adj','公平','gōngpíng','เป็นธรรม','pen tham','adj'],
    ['work','adj','透明','tòumíng','โปร่งใส','prongsai','adj'],

    // 226–250 · culture and nuanced communication
    ['culture','n','文化差异','wénhuà chāyì','ความแตกต่างทางวัฒนธรรม','khwam taektang thang watthanatham','culture'],
    ['culture','n','称呼','chēnghu','คำเรียกบุคคล','kham riak bukkhon','culture'],
    ['culture','n','尊重','zūnzhòng','การให้เกียรติ','kan hai kiat','culture'],
    ['culture','n','面子','miànzi','การรักษาหน้า','kan raksa na','culture','“面子”指社会评价、体面和尊严，不只是字面的“脸”。','面子 หมายถึงภาพลักษณ์ ศักดิ์ศรี และการยอมรับทางสังคม'],
    ['culture','n','关系','guānxi','สายสัมพันธ์','sai samphan','culture','“关系”既可指一般关系，也可指人脉。','关系 อาจหมายถึงความสัมพันธ์ทั่วไปหรือเครือข่ายคนรู้จัก'],
    ['culture','n','习惯','xíguàn','ความเคยชิน','khwam khoei chin','culture'],
    ['culture','n','规矩','guīju','กติกาทางสังคม','katika thang sangkhom','culture'],
    ['social','n','寒暄','hánxuān','การทักทายตามมารยาท','kan thakthai tam marayat','culture'],
    ['culture','n','客气','kèqi','ความเกรงใจ','khwam krengchai','culture','“别客气”是“别见外、不用谢”，不是叫人不礼貌。','别客气 หมายถึงไม่ต้องเกรงใจ ไม่ได้แปลว่าไม่ต้องสุภาพ'],
    ['social','adj','直接','zhíjiē','พูดตรงประเด็น','phut trong praden','adj'],
    ['social','adj','含蓄','hánxù','พูดอ้อมอย่างนุ่มนวล','phut om yang num nuan','adj'],
    ['social','n','赞美','zànměi','การชมเชย','kan chomchoei','culture'],
    ['social','n','道歉','dàoqiàn','การกล่าวขอโทษ','kan klao kho thot','culture'],
    ['social','n','拒绝方式','jùjué fāngshì','วิธีปฏิเสธ','withi patiset','culture'],
    ['culture','n','敬语','jìngyǔ','คำสุภาพยกย่อง','kham suphap yokyong','culture','中文敬语常通过“您、请、麻烦”等表达。','ภาษาจีนมักแสดงความยกย่องด้วย 您 请 และ 麻烦'],
    ['social','n','语气','yǔqì','น้ำเสียง','namsiang','culture','同一句话换语气，礼貌程度可能完全不同。','ประโยคเดิมเมื่อน้ำเสียงเปลี่ยน ระดับความสุภาพก็เปลี่ยนได้'],
    ['social','n','场合','chǎnghé','กาลเทศะ','kalathesa','culture'],
    ['social','n','误会','wùhuì','ความเข้าใจผิด','khwam khaochai phit','have'],
    ['work','n','共识','gòngshí','ฉันทามติ','chanthamati','culture'],
    ['work','n','反馈','fǎnkuì','ความคิดเห็นสะท้อนกลับ','khwam khithen sathon klap','need'],
    ['work','n','建议','jiànyì','คำเสนอแนะ','kham sanoenae','need'],
    ['work','n','决定','juédìng','การตัดสินใจ','kan tatsinchai','need'],
    ['daily','n','选择','xuǎnzé','ทางเลือก','thang lueak','have'],
    ['social','n','信任','xìnrèn','ความไว้วางใจ','khwam waiwangchai','culture'],
    ['social','n','隐私','yǐnsī','ความเป็นส่วนตัว','khwam pen suantua','culture']
  ];

  function expand(rows, level) {
    return rows.map((row, index) => {
      const [cat, pos, zh, py, th, ro, pattern, noteZh = '', noteTh = ''] = row;
      const raw = { zh, py, th, ro };
      const [exZh, exPy, exTh, exRo] = patterns[pattern](raw);
      return {
        id: `l${level}-${String(index + 1).padStart(3, '0')}`,
        level, cat, pos, zh, py, th, ro, exZh, exPy, exTh, exRo, noteZh, noteTh
      };
    });
  }

  window.HUILAISHI_VOCAB_L34 = [...expand(L3, 3), ...expand(L4, 4)];
})();
