(function () {
  "use strict";

  // Compact authoring rows are expanded below into the public, fully keyed records.
  // Row schema: [cat, pos, zh, py, th, ro, noteZh?, noteTh?]
  const L1 = [
    // L1: survival essentials (250 records)
    ["people","pron","我","wǒ","ฉัน","chan","女性常用；男性礼貌自称常用ผม","ผู้หญิงใช้ ฉัน บ่อย ผู้ชายใช้ ผม เมื่อต้องการความสุภาพ"],
    ["people","pron","你","nǐ","คุณ","khun"],
    ["people","pron","他","tā","เขา","khao","泰语เขา也可指“她”","เขา ใช้ได้ทั้งเขาและเธอ"],
    ["people","pron","我们","wǒmen","พวกเรา","phuak rao"],
    ["people","pron","大家","dàjiā","ทุกคน","thuk khon"],
    ["people","n","人","rén","คน","khon"],
    ["people","n","男人","nánrén","ผู้ชาย","phu chai"],
    ["people","n","女人","nǚrén","ผู้หญิง","phu ying"],
    ["people","n","孩子","háizi","เด็ก","dek"],
    ["people","n","朋友","péngyou","เพื่อน","phuean"],
    ["people","n","家人","jiārén","คนในครอบครัว","khon nai khropkhrua"],
    ["people","n","爸爸","bàba","พ่อ","pho"],
    ["people","n","妈妈","māma","แม่","mae"],
    ["people","n","哥哥","gēge","พี่ชาย","phi chai"],
    ["people","n","姐姐","jiějie","พี่สาว","phi sao"],
    ["people","n","弟弟","dìdi","น้องชาย","nong chai"],
    ["people","n","妹妹","mèimei","น้องสาว","nong sao"],
    ["people","n","丈夫","zhàngfu","สามี","sami"],
    ["people","n","妻子","qīzi","ภรรยา","phanraya"],
    ["people","n","老师","lǎoshī","ครู","khru"],
    ["people","n","学生","xuésheng","นักเรียน","nak rian"],
    ["people","n","医生","yīshēng","หมอ","mo"],
    ["people","n","警察","jǐngchá","ตำรวจ","tamruat"],
    ["people","n","客人","kèrén","แขก","khaek"],
    ["people","n","名字","míngzi","ชื่อ","chue"],
    ["daily","n","家","jiā","บ้าน","ban"],
    ["daily","n","房间","fángjiān","ห้อง","hong"],
    ["daily","n","厕所","cèsuǒ","ห้องน้ำ","hong nam"],
    ["daily","n","门","mén","ประตู","pratu"],
    ["daily","n","钥匙","yàoshi","กุญแจ","kunchae"],
    ["daily","n","手机","shǒujī","มือถือ","mue thue"],
    ["daily","n","电话","diànhuà","โทรศัพท์","thorasap"],
    ["daily","n","钱","qián","เงิน","ngoen"],
    ["daily","n","水","shuǐ","น้ำ","nam"],
    ["daily","n","衣服","yīfu","เสื้อผ้า","suea pha"],
    ["daily","n","鞋","xié","รองเท้า","rong thao"],
    ["daily","n","包","bāo","กระเป๋า","krapao"],
    ["daily","v","睡觉","shuìjiào","นอน","non"],
    ["daily","v","起床","qǐchuáng","ตื่น","tuen"],
    ["daily","v","洗澡","xǐzǎo","อาบน้ำ","ap nam"],
    ["daily","v","吃","chī","กิน","kin"],
    ["daily","v","喝","hē","ดื่ม","duem"],
    ["daily","v","去","qù","ไป","pai"],
    ["daily","v","来","lái","มา","ma"],
    ["daily","v","回去","huíqu","กลับ","klap"],
    ["daily","v","坐","zuò","นั่ง","nang"],
    ["daily","v","站","zhàn","ยืน","yuen"],
    ["daily","v","走","zǒu","เดิน","doen"],
    ["daily","v","开","kāi","เปิด","poet"],
    ["daily","v","关","guān","ปิด","pit"],
    ["daily","v","看","kàn","ดู","du"],
    ["daily","v","听","tīng","ฟัง","fang"],
    ["daily","v","说","shuō","พูด","phut"],
    ["daily","v","拿","ná","เอา","ao"],
    ["daily","v","用","yòng","ใช้","chai"],
    ["daily","v","给","gěi","ให้","hai"],
    ["daily","v","想要","xiǎngyào","ต้องการ","tongkan"],
    ["daily","v","有","yǒu","มี","mi"],
    ["daily","v","没有","méiyǒu","ไม่มี","mai mi"],
    ["daily","adj","好","hǎo","ดี","di"],
    ["daily","adj","不好","bùhǎo","ไม่ดี","mai di"],
    ["daily","adj","热","rè","ร้อน","ron"],
    ["daily","adj","冷","lěng","หนาว","nao","泰语หนาว常指天气冷；物品冷常用เย็น","หนาว มักใช้กับอากาศ สิ่งของเย็นใช้ เย็น"],
    ["daily","adj","快","kuài","เร็ว","reo"],
    ["daily","adj","慢","màn","ช้า","cha"],
    ["daily","prep","在","zài","อยู่","yu"],
    ["daily","prep","从","cóng","จาก","chak"],
    ["daily","prep","跟","gēn","กับ","kap"],
    ["daily","conj","和","hé","และ","lae"],
    ["daily","conj","或者","huòzhě","หรือ","rue"],
    ["food","n","饭","fàn","ข้าว","khao"],
    ["food","n","早餐","zǎocān","อาหารเช้า","ahan chao"],
    ["food","n","午饭","wǔfàn","อาหารกลางวัน","ahan klang wan"],
    ["food","n","晚饭","wǎnfàn","อาหารเย็น","ahan yen"],
    ["food","n","菜","cài","กับข้าว","kap khao"],
    ["food","n","水果","shuǐguǒ","ผลไม้","phonlamai"],
    ["food","n","蔬菜","shūcài","ผัก","phak"],
    ["food","n","肉","ròu","เนื้อ","nuea"],
    ["food","n","鸡肉","jīròu","ไก่","kai"],
    ["food","n","猪肉","zhūròu","หมู","mu"],
    ["food","n","鱼","yú","ปลา","pla"],
    ["food","n","鸡蛋","jīdàn","ไข่","khai"],
    ["food","n","面条","miàntiáo","ก๋วยเตี๋ยว","kuaitiao"],
    ["food","n","汤","tāng","ซุป","sup"],
    ["food","n","咖啡","kāfēi","กาแฟ","kafae"],
    ["food","n","茶","chá","ชา","cha"],
    ["food","n","牛奶","niúnǎi","นม","nom"],
    ["food","n","啤酒","píjiǔ","เบียร์","bia"],
    ["food","adj","甜","tián","หวาน","wan"],
    ["food","adj","辣","là","เผ็ด","phet"],
    ["food","adj","咸","xián","เค็ม","khem"],
    ["food","adj","好吃","hǎochī","อร่อย","aroi"],
    ["food","adj","饿","è","หิว","hiu"],
    ["food","adj","渴","kě","กระหายน้ำ","krahai nam"],
    ["food","n","菜单","càidān","เมนู","menu"],
    ["food","v","点菜","diǎncài","สั่งอาหาร","sang ahan"],
    ["food","n","账单","zhàngdān","บิล","bin"],
    ["food","n","餐馆","cānguǎn","ร้านอาหาร","ran ahan"],
    ["food","phrase","不加辣","bù jiā là","ไม่ใส่พริก","mai sai phrik"],
    ["food","n","冰","bīng","น้ำแข็ง","nam khaeng"],
    ["travel","n","车","chē","รถ","rot"],
    ["travel","n","出租车","chūzūchē","แท็กซี่","thaeksi"],
    ["travel","n","公交车","gōngjiāochē","รถเมล์","rot me"],
    ["travel","n","火车","huǒchē","รถไฟ","rot fai"],
    ["travel","n","飞机","fēijī","เครื่องบิน","khrueang bin"],
    ["travel","n","船","chuán","เรือ","ruea"],
    ["travel","n","摩托车","mótuōchē","มอเตอร์ไซค์","motoesai"],
    ["travel","n","自行车","zìxíngchē","จักรยาน","chakkayan"],
    ["travel","n","车站","chēzhàn","สถานี","sathani"],
    ["travel","n","机场","jīchǎng","สนามบิน","sanam bin"],
    ["travel","n","酒店","jiǔdiàn","โรงแรม","rongraem"],
    ["travel","n","路","lù","ถนน","thanon"],
    ["travel","n","地图","dìtú","แผนที่","phaen thi"],
    ["travel","adv","这里","zhèlǐ","ที่นี่","thi ni"],
    ["travel","adv","那里","nàlǐ","ที่นั่น","thi nan"],
    ["travel","pron","哪里","nǎlǐ","ที่ไหน","thi nai"],
    ["travel","n","左边","zuǒbian","ซ้าย","sai"],
    ["travel","n","右边","yòubian","ขวา","khwa"],
    ["travel","phrase","直走","zhízǒu","ตรงไป","trong pai"],
    ["travel","adj","附近","fùjìn","ใกล้","klai"],
    ["travel","adj","远","yuǎn","ไกล","klai"],
    ["travel","v","到","dào","ถึง","thueng"],
    ["travel","v","出发","chūfā","ออกเดินทาง","ok doen thang"],
    ["travel","v","下车","xiàchē","ลงรถ","long rot"],
    ["travel","v","上车","shàngchē","ขึ้นรถ","khuen rot"],
    ["travel","n","票","piào","ตั๋ว","tua"],
    ["travel","n","护照","hùzhào","หนังสือเดินทาง","nangsue doen thang"],
    ["travel","n","行李","xíngli","สัมภาระ","samphara"],
    ["travel","v","预约","yùyuē","จอง","chong"],
    ["travel","v","迷路","mílù","หลงทาง","long thang"],
    ["travel","n","入口","rùkǒu","ทางเข้า","thang khao"],
    ["travel","n","出口","chūkǒu","ทางออก","thang ok"],
    ["travel","v","停车","tíngchē","จอด","chot"],
    ["travel","n","海滩","hǎitān","ชายหาด","chai hat"],
    ["travel","n","寺庙","sìmiào","วัด","wat"],
    ["shopping","v","买","mǎi","ซื้อ","sue"],
    ["shopping","v","卖","mài","ขาย","khai"],
    ["shopping","n","商店","shāngdiàn","ร้านค้า","ran kha"],
    ["shopping","n","市场","shìchǎng","ตลาด","talat"],
    ["shopping","n","超市","chāoshì","ซูเปอร์มาร์เก็ต","supermaket"],
    ["shopping","n","价格","jiàgé","ราคา","rakha"],
    ["shopping","phrase","多少钱","duōshao qián","เท่าไหร่","thao rai"],
    ["shopping","adj","贵","guì","แพง","phaeng"],
    ["shopping","adj","便宜","piányi","ถูก","thuk"],
    ["shopping","adj","大","dà","ใหญ่","yai"],
    ["shopping","adj","小","xiǎo","เล็ก","lek"],
    ["shopping","pron","这个","zhège","อันนี้","an ni"],
    ["shopping","pron","那个","nàge","อันนั้น","an nan"],
    ["shopping","pron","哪个","nǎge","อันไหน","an nai"],
    ["shopping","phrase","一个","yí ge","หนึ่งอัน","nueng an"],
    ["shopping","v","试穿","shìchuān","ลองใส่","long sai"],
    ["shopping","n","颜色","yánsè","สี","si"],
    ["shopping","n","红色","hóngsè","สีแดง","si daeng"],
    ["shopping","n","蓝色","lánsè","สีน้ำเงิน","si nam ngoen"],
    ["shopping","n","黑色","hēisè","สีดำ","si dam"],
    ["shopping","n","白色","báisè","สีขาว","si khao"],
    ["shopping","n","尺寸","chǐcùn","ขนาด","khanat"],
    ["shopping","n","现金","xiànjīn","เงินสด","ngoen sot"],
    ["shopping","n","信用卡","xìnyòngkǎ","บัตรเครดิต","bat khredit"],
    ["shopping","n","收据","shōujù","ใบเสร็จ","bai set"],
    ["time","num","零","líng","ศูนย์","sun"],
    ["time","num","一","yī","หนึ่ง","nueng"],
    ["time","num","二","èr","สอง","song"],
    ["time","num","三","sān","สาม","sam"],
    ["time","num","四","sì","สี่","si"],
    ["time","num","五","wǔ","ห้า","ha"],
    ["time","num","六","liù","หก","hok"],
    ["time","num","七","qī","เจ็ด","chet"],
    ["time","num","八","bā","แปด","paet"],
    ["time","num","九","jiǔ","เก้า","kao"],
    ["time","num","十","shí","สิบ","sip"],
    ["time","num","百","bǎi","ร้อย","roi"],
    ["time","num","千","qiān","พัน","phan"],
    ["time","n","今天","jīntiān","วันนี้","wan ni"],
    ["time","n","明天","míngtiān","พรุ่งนี้","phrung ni"],
    ["time","n","昨天","zuótiān","เมื่อวาน","muea wan"],
    ["time","adv","现在","xiànzài","ตอนนี้","ton ni"],
    ["time","n","早上","zǎoshang","ตอนเช้า","ton chao"],
    ["time","n","中午","zhōngwǔ","เที่ยง","thiang"],
    ["time","n","下午","xiàwǔ","ตอนบ่าย","ton bai"],
    ["time","n","晚上","wǎnshang","ตอนเย็น","ton yen"],
    ["time","phrase","几点","jǐ diǎn","กี่โมง","ki mong"],
    ["time","n","时间","shíjiān","เวลา","wela"],
    ["time","n","小时","xiǎoshí","ชั่วโมง","chua mong"],
    ["time","n","分钟","fēnzhōng","นาที","nathi"],
    ["time","n","星期","xīngqī","สัปดาห์","sapda"],
    ["time","adv","每天","měitiān","ทุกวัน","thuk wan"],
    ["time","adv","以前","yǐqián","ก่อน","kon"],
    ["time","adv","以后","yǐhòu","ทีหลัง","thi lang"],
    ["time","phrase","等一下","děng yíxià","รอสักครู่","ro sak khru"],
    ["work","v","工作","gōngzuò","ทำงาน","tham ngan"],
    ["work","n","公司","gōngsī","บริษัท","borisat"],
    ["work","n","办公室","bàngōngshì","สำนักงาน","samnak ngan"],
    ["work","n","同事","tóngshì","เพื่อนร่วมงาน","phuean ruam ngan"],
    ["work","n","老板","lǎobǎn","เจ้านาย","chao nai"],
    ["work","n","会议","huìyì","ประชุม","prachum"],
    ["work","n","电脑","diànnǎo","คอมพิวเตอร์","khomphiotoe"],
    ["work","n","文件","wénjiàn","เอกสาร","ekkasan"],
    ["study","n","学校","xuéxiào","โรงเรียน","rong rian"],
    ["study","n","教室","jiàoshì","ห้องเรียน","hong rian"],
    ["study","n","书","shū","หนังสือ","nangsue"],
    ["study","n","笔","bǐ","ปากกา","pakka"],
    ["study","n","问题","wèntí","คำถาม","kham tham"],
    ["study","v","学习","xuéxí","เรียน","rian"],
    ["study","v","懂","dǒng","เข้าใจ","khao chai"],
    ["social","phrase","你好","nǐ hǎo","สวัสดี","sawatdi"],
    ["social","phrase","谢谢","xièxie","ขอบคุณ","khop khun"],
    ["social","phrase","不客气","bú kèqi","ด้วยความยินดี","duai khwam yindi"],
    ["social","phrase","对不起","duìbuqǐ","ขอโทษ","kho thot"],
    ["social","phrase","没关系","méi guānxi","ไม่เป็นไร","mai pen rai"],
    ["social","phrase","再见","zàijiàn","ลาก่อน","la kon"],
    ["social","v","是","shì","ใช่","chai"],
    ["social","v","不是","bú shì","ไม่ใช่","mai chai"],
    ["social","phrase","好的","hǎo de","โอเค","okhe"],
    ["social","particle","请","qǐng","กรุณา","karuna"],
    ["social","phrase","请问","qǐngwèn","ขอถามหน่อย","kho tham noi"],
    ["social","pron","什么","shénme","อะไร","arai"],
    ["social","pron","谁","shéi","ใคร","khrai"],
    ["social","adv","为什么","wèishénme","ทำไม","thammai"],
    ["social","adv","怎么","zěnme","อย่างไร","yang rai"],
    ["social","v","可以","kěyǐ","ได้","dai"],
    ["social","v","不可以","bù kěyǐ","ไม่ได้","mai dai"],
    ["social","v","喜欢","xǐhuan","ชอบ","chop"],
    ["social","v","不喜欢","bù xǐhuan","ไม่ชอบ","mai chop"],
    ["social","phrase","很高兴认识你","hěn gāoxìng rènshi nǐ","ยินดีที่ได้รู้จัก","yindi thi dai ruchak"],
    ["health","n","医院","yīyuàn","โรงพยาบาล","rong phayaban"],
    ["health","n","药店","yàodiàn","ร้านขายยา","ran khai ya"],
    ["health","n","药","yào","ยา","ya"],
    ["health","adj","疼","téng","เจ็บ","chep"],
    ["health","adj","生病","shēngbìng","ป่วย","puai"],
    ["health","phrase","发烧","fāshāo","เป็นไข้","pen khai"],
    ["health","n","头痛","tóutòng","ปวดหัว","puat hua"],
    ["health","n","肚子痛","dùzi tòng","ปวดท้อง","puat thong"],
    ["health","adj","过敏","guòmǐn","แพ้","phae"],
    ["emergency","v","帮助","bāngzhù","ช่วย","chuai"],
    ["emergency","phrase","救命","jiùmìng","ช่วยด้วย","chuai duai"],
    ["emergency","phrase","小心","xiǎoxīn","ระวัง","rawang"],
    ["emergency","n","危险","wēixiǎn","อันตราย","antarai"],
    ["emergency","n","紧急情况","jǐnjí qíngkuàng","เหตุฉุกเฉิน","het chukchoen"],
    ["emergency","v","报警","bàojǐng","แจ้งตำรวจ","chaeng tamruat"],
    ["emergency","phrase","叫救护车","jiào jiùhùchē","เรียกรถพยาบาล","riak rot phayaban"],
    ["emergency","adj","丢了","diū le","หาย","hai"],
    ["emergency","phrase","被偷了","bèi tōu le","ถูกขโมย","thuk khamoi"],
    ["emergency","n","火灾","huǒzāi","ไฟไหม้","fai mai"],
    ["emergency","v","停","tíng","หยุด","yut"],
    ["culture","n","泰国","Tàiguó","ประเทศไทย","prathet thai"],
    ["culture","n","泰国人","Tàiguó rén","คนไทย","khon thai"],
    ["culture","n","泰语","Tàiyǔ","ภาษาไทย","phasa thai"],
    ["culture","n","合十礼","héshí lǐ","การไหว้","kan wai"],
    ["culture","v","微笑","wēixiào","ยิ้ม","yim"]
  ];

  const L2 = [
    // people (20)
    ["people","n","顾问","gùwèn","ที่ปรึกษา","thi prueksa"],
    ["people","n","邻居","línjū","เพื่อนบ้าน","phuean ban"],
    ["people","n","顾客","gùkè","ลูกค้า","luk-kha"],
    ["people","n","秘书","mìshū","เลขานุการ","lekhanu-kan"],
    ["people","n","经理","jīnglǐ","ผู้จัดการ","phu chat-kan"],
    ["people","n","司机","sījī","คนขับรถ","khon khap rot"],
    ["people","n","导游","dǎoyóu","มัคคุเทศก์","mak-khu-thet"],
    ["people","n","工程师","gōngchéngshī","วิศวกร","witsawakon"],
    ["people","n","护士","hùshi","พยาบาล","phayaban"],
    ["people","n","律师","lǜshī","ทนายความ","thanai-khwam"],
    ["people","n","服务员","fúwùyuán","พนักงานเสิร์ฟ","phanak-ngan soep"],
    ["people","n","房东","fángdōng","เจ้าของบ้าน","chao-khong ban"],
    ["people","n","室友","shìyǒu","เพื่อนร่วมห้อง","phuean ruam hong"],
    ["people","n","男朋友","nánpéngyou","แฟนผู้ชาย","faen phu-chai"],
    ["people","n","女朋友","nǚpéngyou","แฟนผู้หญิง","faen phu-ying"],
    ["people","n","夫妻","fūqī","คู่สามีภรรยา","khu sami phanraya"],
    ["people","n","成年人","chéngniánrén","ผู้ใหญ่","phu-yai"],
    ["people","n","年轻人","niánqīngrén","คนหนุ่มสาว","khon num-sao"],
    ["people","n","外国人","wàiguórén","ชาวต่างชาติ","chao tang-chat"],
    ["people","n","本地人","běndìrén","คนท้องถิ่น","khon thong-thin"],

    // daily (25)
    ["daily","v","搬家","bānjiā","ย้ายบ้าน","yai ban"],
    ["daily","v","刷牙","shuāyá","แปรงฟัน","praeng fan"],
    ["daily","v","洗脸","xǐliǎn","ล้างหน้า","lang na"],
    ["daily","v","做家务","zuò jiāwù","ทำงานบ้าน","tham ngan-ban"],
    ["daily","v","穿衣服","chuān yīfu","แต่งตัว","taeng tua"],
    ["daily","v","做饭","zuòfàn","ทำอาหาร","tham ahan"],
    ["daily","v","洗碗","xǐwǎn","ล้างจาน","lang chan"],
    ["daily","v","洗衣服","xǐ yīfu","ซักผ้า","sak pha"],
    ["daily","v","打扫","dǎsǎo","ทำความสะอาด","tham khwam sa-at"],
    ["daily","v","开门","kāimén","เปิดประตู","poet pratu"],
    ["daily","v","关门","guānmén","ปิดประตู","pit pratu"],
    ["daily","v","开灯","kāidēng","เปิดไฟ","poet fai"],
    ["daily","v","关灯","guāndēng","ปิดไฟ","pit fai"],
    ["daily","v","充电","chōngdiàn","ชาร์จแบต","chat baet"],
    ["daily","v","上网","shàngwǎng","ใช้อินเทอร์เน็ต","chai internet"],
    ["daily","v","拍照","pāizhào","ถ่ายรูป","thai rup"],
    ["daily","v","看电视","kàn diànshì","ดูโทรทัศน์","du thorathat"],
    ["daily","v","听音乐","tīng yīnyuè","ฟังเพลง","fang phleng"],
    ["daily","v","散步","sànbù","เดินเล่น","doen len"],
    ["daily","v","锻炼","duànliàn","ออกกำลังกาย","ok kamlang-kai"],
    ["daily","v","睡过头","shuìguòtóu","ตื่นสาย","tuen sai"],
    ["daily","v","忘记","wàngjì","ลืม","luem"],
    ["daily","v","记得","jìde","จำได้","cham dai"],
    ["daily","v","准备","zhǔnbèi","เตรียมตัว","triam tua"],
    ["daily","v","休息","xiūxi","พักผ่อน","phak-phon"],

    // food (25)
    ["food","n","主食","zhǔshí","อาหารจานหลัก","ahan chan lak"],
    ["food","n","自助餐","zìzhùcān","บุฟเฟต์","buffet"],
    ["food","n","宵夜","xiāoyè","อาหารมื้อดึก","ahan mue duek"],
    ["food","n","零食","língshí","ของกินเล่น","khong kin len"],
    ["food","n","甜点","tiándiǎn","ของหวาน","khong wan"],
    ["food","n","辣椒","làjiāo","พริก","phrik"],
    ["food","n","酱油","jiàngyóu","ซีอิ๊ว","si-io"],
    ["food","n","鱼露","yúlù","น้ำปลา","nam pla"],
    ["food","n","椰奶","yēnǎi","กะทิ","kathi"],
    ["food","n","火锅","huǒguō","หม้อไฟ","mo fai"],
    ["food","n","炒饭","chǎofàn","ข้าวผัด","khao phat"],
    ["food","n","炒面","chǎomiàn","ผัดหมี่","phat mi"],
    ["food","n","烤鸡","kǎojī","ไก่ย่าง","kai yang"],
    ["food","n","猪肝","zhūgān","ตับหมู","tap mu"],
    ["food","n","牛肉","niúròu","เนื้อวัว","nuea wua"],
    ["food","n","海鲜","hǎixiān","อาหารทะเล","ahan thale"],
    ["food","n","素食","sùshí","อาหารมังสวิรัติ","ahan mangsawirat"],
    ["food","n","矿泉水","kuàngquánshuǐ","น้ำแร่","nam rae"],
    ["food","n","吸管","xīguǎn","หลอด","lot"],
    ["food","n","餐具","cānjù","ช้อนส้อม","chon som"],
    ["food","phrase","打包","dǎbāo","ใส่กล่องกลับบ้าน","sai klong klap ban"],
    ["food","n","外卖","wàimài","อาหารส่งถึงบ้าน","ahan song thueng ban"],
    ["food","phrase","不加糖","bù jiā táng","ไม่ใส่น้ำตาล","mai sai namtan"],
    ["food","phrase","少冰","shǎo bīng","ใส่น้ำแข็งน้อย","sai nam-khaeng noi"],
    ["food","phrase","太辣","tài là","เผ็ดเกินไป","phet koen pai"],

    // travel (25)
    ["travel","n","签证","qiānzhèng","วีซ่า","wisa"],
    ["travel","n","行李箱","xínglixiāng","กระเป๋าเดินทาง","krapao doen-thang"],
    ["travel","n","登机牌","dēngjīpái","บัตรขึ้นเครื่อง","bat khuen khrueang"],
    ["travel","n","航班","hángbān","เที่ยวบิน","thiao-bin"],
    ["travel","v","换乘","huànchéng","ต่อรถ","to rot"],
    ["travel","n","单程票","dānchéngpiào","ตั๋วเที่ยวเดียว","tua thiao diao"],
    ["travel","n","往返票","wǎngfǎnpiào","ตั๋วไปกลับ","tua pai-klap"],
    ["travel","v","延误","yánwù","ล่าช้า","la-cha"],
    ["travel","v","取消","qǔxiāo","ยกเลิก","yok-loek"],
    ["travel","n","安检","ānjiǎn","จุดตรวจความปลอดภัย","chut truat khwam plotphai"],
    ["travel","n","海关","hǎiguān","ศุลกากร","sunlakakon"],
    ["travel","n","座位","zuòwèi","ที่นั่ง","thi nang"],
    ["travel","phrase","靠窗","kàochuāng","ริมหน้าต่าง","rim na-tang"],
    ["travel","n","走道","zǒudào","ทางเดิน","thang doen"],
    ["travel","n","民宿","mínsù","โฮมสเตย์","homstay"],
    ["travel","n","前台","qiántái","แผนกต้อนรับ","phanaek ton-rap"],
    ["travel","n","站台","zhàntái","ชานชาลา","chan-chala"],
    ["travel","n","登机口","dēngjīkǒu","ประตูขึ้นเครื่อง","pratu khuen khrueang"],
    ["travel","n","自动扶梯","zìdòng fútī","บันไดเลื่อน","bandai luean"],
    ["travel","n","红绿灯","hónglǜdēng","สัญญาณไฟจราจร","sanyan fai charachon"],
    ["travel","n","十字路口","shízìlùkǒu","สี่แยก","si yaek"],
    ["travel","v","过马路","guò mǎlù","ข้ามถนน","kham thanon"],
    ["travel","phrase","堵车","dǔchē","รถติด","rot tit"],
    ["travel","v","入住","rùzhù","เช็กอิน","check-in"],
    ["travel","v","退房","tuìfáng","เช็กเอาต์","check-out"],

    // shopping (20)
    ["shopping","n","尺码","chǐmǎ","ไซซ์","sai"],
    ["shopping","v","试用","shìyòng","ทดลองใช้","thotlong chai"],
    ["shopping","v","打折","dǎzhé","ลดราคา","lot rakha"],
    ["shopping","n","原价","yuánjià","ราคาเต็ม","rakha tem"],
    ["shopping","n","借记卡","jièjìkǎ","บัตรเดบิต","bat debit"],
    ["shopping","v","扫码","sǎomǎ","สแกนจ่าย","sakaen chai"],
    ["shopping","n","订单","dìngdān","คำสั่งซื้อ","kham sang sue"],
    ["shopping","n","发票","fāpiào","ใบกำกับภาษี","bai kamkap phasi"],
    ["shopping","v","退货","tuìhuò","คืนสินค้า","khuen sinkha"],
    ["shopping","v","换货","huànhuò","เปลี่ยนสินค้า","plian sinkha"],
    ["shopping","phrase","缺货","quēhuò","สินค้าหมด","sinkha mot"],
    ["shopping","n","库存","kùcún","สินค้าคงคลัง","sinkha khong-khlang"],
    ["shopping","n","保修","bǎoxiū","การรับประกัน","kan rap-prakan"],
    ["shopping","n","质量","zhìliàng","คุณภาพ","khunnaphap"],
    ["shopping","n","品牌","pǐnpái","ยี่ห้อ","yiho"],
    ["shopping","n","赠品","zèngpǐn","ของแถม","khong thaem"],
    ["shopping","phrase","第二件","dì èr jiàn","ชิ้นที่สอง","chin thi song"],
    ["shopping","adj","合适","héshì","พอดี","phodi"],
    ["shopping","v","付款","fùkuǎn","ชำระเงิน","chamra ngoen"],
    ["shopping","n","找零","zhǎolíng","เงินทอน","ngoen thon"],

    // time (20)
    ["time","n","前天","qiántiān","เมื่อวานซืน","muea-wan-suen"],
    ["time","n","后天","hòutiān","มะรืน","maruen"],
    ["time","n","上周","shàngzhōu","สัปดาห์ที่แล้ว","sapda thi laeo"],
    ["time","n","下周","xiàzhōu","สัปดาห์หน้า","sapda na"],
    ["time","n","周末","zhōumò","วันหยุดสุดสัปดาห์","wan yut sut sapda"],
    ["time","n","工作日","gōngzuòrì","วันทำงาน","wan tham-ngan"],
    ["time","n","月底","yuèdǐ","สิ้นเดือน","sin duean"],
    ["time","n","年初","niánchū","ต้นปี","ton pi"],
    ["time","adv","最近","zuìjìn","ช่วงนี้","chuang ni"],
    ["time","adv","当时","dāngshí","ตอนนั้น","ton nan"],
    ["time","adv","从现在起","cóng xiànzài qǐ","ตั้งแต่นี้ไป","tangtae ni pai"],
    ["time","adv","刚才","gāngcái","เมื่อกี้","muea-ki"],
    ["time","adv","马上","mǎshàng","เดี๋ยวนี้","diao ni"],
    ["time","adv","按时","ànshí","ตรงเวลา","trong wela"],
    ["time","v","迟到","chídào","มาสาย","ma sai"],
    ["time","adv","提前","tíqián","ก่อนเวลา","kon wela"],
    ["time","v","推迟","tuīchí","เลื่อนออกไป","luean ok pai"],
    ["time","prep","期间","qījiān","ในช่วง","nai chuang"],
    ["time","adj","有空","yǒukòng","ว่าง","wang"],
    ["time","adv","偶尔","ǒu'ěr","นานๆ ครั้ง","nan nan khrang"],

    // work (20)
    ["work","n","企业","qǐyè","องค์กรธุรกิจ","ongkon thurakit"],
    ["work","n","工位","gōngwèi","โต๊ะทำงาน","to tham-ngan"],
    ["work","n","议程","yìchéng","กำหนดการประชุม","kamnotkan prachum"],
    ["work","n","项目","xiàngmù","โครงการ","khrongkan"],
    ["work","n","任务","rènwu","งานที่ได้รับมอบหมาย","ngan thi dai-rap mopmai"],
    ["work","n","表格","biǎogé","แบบฟอร์ม","baep fom"],
    ["work","n","邮件","yóujiàn","อีเมล","email"],
    ["work","n","合同","hétong","สัญญา","sanya"],
    ["work","n","工资","gōngzī","เงินเดือน","ngoen duean"],
    ["work","v","加班","jiābān","ทำงานล่วงเวลา","tham-ngan luang wela"],
    ["work","v","请假","qǐngjià","ลางาน","la ngan"],
    ["work","v","出差","chūchāi","ไปทำงานต่างจังหวัด","pai tham-ngan tang changwat"],
    ["work","v","面试","miànshì","สัมภาษณ์งาน","samphat ngan"],
    ["work","n","简历","jiǎnlì","ประวัติย่อ","prawat yo"],
    ["work","n","截止日期","jiézhǐ rìqī","กำหนดส่ง","kamnot song"],
    ["work","n","报告","bàogào","รายงาน","raingan"],
    ["work","n","合作伙伴","hézuò huǒbàn","หุ้นส่วน","hun-suan"],
    ["work","n","部门","bùmén","แผนก","phanaek"],
    ["work","n","职位","zhíwèi","ตำแหน่งงาน","tamnaeng ngan"],
    ["work","n","培训","péixùn","การอบรม","kan oprom"],

    // study (20)
    ["study","n","大学","dàxué","มหาวิทยาลัย","mahawitthayalai"],
    ["study","n","课程","kèchéng","หลักสูตร","laksut"],
    ["study","n","作业","zuòyè","การบ้าน","kan ban"],
    ["study","n","考试","kǎoshì","การสอบ","kan sop"],
    ["study","n","成绩","chéngjì","คะแนนสอบ","khanaen sop"],
    ["study","n","答案","dá'àn","คำตอบ","kham top"],
    ["study","n","语法","yǔfǎ","ไวยากรณ์","waiyakon"],
    ["study","n","发音","fāyīn","การออกเสียง","kan ok siang"],
    ["study","n","声调","shēngdiào","วรรณยุกต์","wannayuk"],
    ["study","n","汉字","Hànzì","ตัวอักษรจีน","tua akson Chin"],
    ["study","n","泰文","Tàiwén","ตัวอักษรไทย","tua akson Thai"],
    ["study","n","词典","cídiǎn","พจนานุกรม","photchananukrom"],
    ["study","n","笔记","bǐjì","สมุดจด","samut chot"],
    ["study","n","奖学金","jiǎngxuéjīn","ทุนการศึกษา","thun kan sueksa"],
    ["study","n","专业","zhuānyè","สาขาวิชา","sakha wicha"],
    ["study","n","学期","xuéqī","ภาคเรียน","phak rian"],
    ["study","v","报名","bàomíng","สมัครเรียน","samak rian"],
    ["study","v","毕业","bìyè","เรียนจบ","rian chop"],
    ["study","v","留学","liúxué","เรียนต่อต่างประเทศ","rian to tang prathet"],
    ["study","v","复习","fùxí","ทบทวนบทเรียน","thopthuan botrian"],

    // social (25)
    ["social","v","认识","rènshi","รู้จัก","ru-chak"],
    ["social","v","介绍","jièshào","แนะนำตัว","nae-nam tua"],
    ["social","v","邀请","yāoqǐng","เชิญ","choen"],
    ["social","v","约会","yuēhuì","นัดเดต","nat det"],
    ["social","n","聚会","jùhuì","งานสังสรรค์","ngan sangsan"],
    ["social","v","聊天","liáotiān","พูดคุย","phut-khui"],
    ["social","v","联系","liánxì","ติดต่อ","tit-to"],
    ["social","n","消息","xiāoxi","ข้อความ","kho-khwam"],
    ["social","v","视频通话","shìpín tōnghuà","วิดีโอคอล","wideo khon"],
    ["social","v","关注","guānzhù","ติดตาม","tit-tam"],
    ["social","v","点赞","diǎnzàn","กดถูกใจ","kot thuk-chai"],
    ["social","v","评论","pínglùn","แสดงความคิดเห็น","sadaeng khwam khit-hen"],
    ["social","v","分享","fēnxiǎng","แบ่งปัน","baeng-pan"],
    ["social","v","开玩笑","kāi wánxiào","ล้อเล่น","lo-len"],
    ["social","v","相信","xiāngxìn","เชื่อใจ","chuea-chai"],
    ["social","v","同意","tóngyì","เห็นด้วย","hen duai"],
    ["social","v","反对","fǎnduì","คัดค้าน","khat-khan"],
    ["social","v","答应","dāying","รับปาก","rap-pak"],
    ["social","v","拒绝","jùjué","ปฏิเสธ","pati-set"],
    ["social","v","道歉","dàoqiàn","กล่าวขอโทษ","klao kho-thot"],
    ["social","v","祝贺","zhùhè","แสดงความยินดี","sadaeng khwam yin-di"],
    ["social","v","想念","xiǎngniàn","คิดถึง","khit-thueng"],
    ["social","v","见面","jiànmiàn","พบกัน","phop-kan"],
    ["social","phrase","保持联系","bǎochí liánxì","ติดต่อกัน","tit-to kan"],
    ["social","v","保密","bǎomì","เก็บเป็นความลับ","kep pen khwam-lap"],

    // health (20)
    ["health","phrase","发冷","fālěng","หนาวสั่น","nao san"],
    ["health","v","咳嗽","késou","ไอ","ai"],
    ["health","phrase","流鼻涕","liú bítì","น้ำมูกไหล","nam-muk lai"],
    ["health","phrase","偏头痛","piāntóutòng","ไมเกรน","mai-kren"],
    ["health","phrase","恶心","ěxin","คลื่นไส้","khluen-sai"],
    ["health","phrase","喉咙痛","hóulong tòng","เจ็บคอ","chep kho"],
    ["health","phrase","牙痛","yátòng","ปวดฟัน","puat fan"],
    ["health","n","皮疹","pízhěn","ผื่น","phuen"],
    ["health","v","受伤","shòushāng","บาดเจ็บ","bat-chep"],
    ["health","v","流血","liúxuè","เลือดออก","lueat ok"],
    ["health","n","药品","yàopǐn","ยารักษาโรค","ya raksa rok"],
    ["health","n","药剂师","yàojìshī","เภสัชกร","phesatchakon"],
    ["health","n","处方","chǔfāng","ใบสั่งยา","bai sang ya"],
    ["health","n","急诊室","jízhěnshì","ห้องฉุกเฉิน","hong chukchoen"],
    ["health","n","诊所","zhěnsuǒ","คลินิก","khlinik"],
    ["health","v","检查","jiǎnchá","ตรวจร่างกาย","truat rang-kai"],
    ["health","v","打针","dǎzhēn","ฉีดยา","chit ya"],
    ["health","adj","严重","yánzhòng","รุนแรง","run-raeng"],
    ["health","phrase","好一点","hǎo yìdiǎn","ดีขึ้น","di khuen"],
    ["health","n","保险","bǎoxiǎn","ประกันภัย","prakan-phai"],

    // emergency (15)
    ["emergency","phrase","快跑","kuài pǎo","รีบหนี","rip ni"],
    ["emergency","phrase","联系警察","liánxì jǐngchá","ติดต่อเจ้าหน้าที่ตำรวจ","tit-to chao-nathi tamruat"],
    ["emergency","n","烟雾","yānwù","ควัน","khwan"],
    ["emergency","n","事故","shìgù","อุบัติเหตุ","ubattihet"],
    ["emergency","phrase","禁止入内","jìnzhǐ rùnèi","ห้ามเข้า","ham khao"],
    ["emergency","phrase","当心脚下","dāngxīn jiǎoxià","ระวังพื้นต่างระดับ","rawang phuen tang radap"],
    ["emergency","v","丢失","diūshī","สูญหาย","sun-hai"],
    ["emergency","phrase","财物失窃","cáiwù shīqiè","ทรัพย์สินถูกขโมย","sapsin thuk khamoi"],
    ["emergency","adj","紧急","jǐnjí","ฉุกเฉิน","chuk-choen"],
    ["emergency","phrase","别动","bié dòng","อย่าขยับ","ya khayap"],
    ["emergency","phrase","离开","líkāi","ออกไป","ok pai"],
    ["emergency","phrase","不要碰","bú yào pèng","ห้ามแตะ","ham tae"],
    ["emergency","n","急救","jíjiù","ปฐมพยาบาล","pathom-phayaban"],
    ["emergency","n","大使馆","dàshǐguǎn","สถานทูต","sathan-thut"],
    ["emergency","v","求助","qiúzhù","ขอความช่วยเหลือ","kho khwam chuai-luea"],

    // culture (15)
    ["culture","n","宫殿","gōngdiàn","พระราชวัง","phra ratchawang"],
    ["culture","n","佛像","fóxiàng","พระพุทธรูป","phra phuttha-rup"],
    ["culture","v","脱鞋","tuōxié","ถอดรองเท้า","thot rong-thao"],
    ["culture","n","佛教","Fójiào","พุทธศาสนา","phuttha satsana"],
    ["culture","n","筷子","kuàizi","ตะเกียบ","takiap"],
    ["culture","n","春节","Chūnjié","ตรุษจีน","Trut Chin"],
    ["culture","n","泼水节","Pōshuǐjié","สงกรานต์","Songkran"],
    ["culture","n","红包","hóngbāo","อั่งเปา","ang-pao"],
    ["culture","n","夜市","yèshì","ตลาดกลางคืน","talat klang-khuen"],
    ["culture","n","小费","xiǎofèi","เงินทิป","ngoen thip"],
    ["culture","n","礼貌","lǐmào","ความสุภาพ","khwam suphap"],
    ["culture","v","尊重","zūnzhòng","ให้เกียรติ","hai kiat"],
    ["culture","n","禁忌","jìnjì","ข้อห้าม","kho ham"],
    ["culture","n","节日","jiérì","เทศกาล","thetsakan"],
    ["culture","n","面子","miànzi","การรักษาหน้า","kan raksa na"]
  ];

  const phraseLike = new Set(["phrase", "prep", "conj", "particle"]);
  const SPECIAL_EXAMPLES = {
    "家人": ["他是我的家人。", "Tā shì wǒ de jiārén.", "เขาเป็นคนในครอบครัวของฉัน", "khao pen khon nai khropkhrua khong chan"],
    "名字": ["我的名字叫小林。", "Wǒ de míngzi jiào Xiǎolín.", "ฉันชื่อเสี่ยวหลิน", "chan chue Xiao Lin"],
    "想要": ["我想要一杯水。", "Wǒ xiǎngyào yì bēi shuǐ.", "ฉันต้องการน้ำหนึ่งแก้ว", "chan tongkan nam nueng kaeo"],
    "有": ["我有时间。", "Wǒ yǒu shíjiān.", "ฉันมีเวลา", "chan mi wela"],
    "没有": ["我没有现金。", "Wǒ méiyǒu xiànjīn.", "ฉันไม่มีเงินสด", "chan mai mi ngoen sot"],
    "在": ["我在这里。", "Wǒ zài zhèlǐ.", "ฉันอยู่ที่นี่", "chan yu thi ni"],
    "从": ["我从泰国来。", "Wǒ cóng Tàiguó lái.", "ฉันมาจากประเทศไทย", "chan ma chak prathet thai"],
    "跟": ["我跟朋友去。", "Wǒ gēn péngyou qù.", "ฉันไปกับเพื่อน", "chan pai kap phuean"],
    "和": ["我和他认识。", "Wǒ hé tā rènshi.", "ฉันและเขารู้จักกัน", "chan lae khao ru-chak kan"],
    "或者": ["茶或者咖啡？", "Chá huòzhě kāfēi?", "ชาหรือกาแฟ", "cha rue kafae"],
    "哪里": ["洗手间在哪里？", "Xǐshǒujiān zài nǎlǐ?", "ห้องน้ำอยู่ที่ไหน", "hong nam yu thi nai"],
    "左边": ["厕所在左边。", "Cèsuǒ zài zuǒbian.", "ห้องน้ำอยู่ทางซ้าย", "hong nam yu thang sai"],
    "右边": ["出口在右边。", "Chūkǒu zài yòubian.", "ทางออกอยู่ทางขวา", "thang ok yu thang khwa"],
    "附近": ["酒店在附近。", "Jiǔdiàn zài fùjìn.", "โรงแรมอยู่ใกล้", "rongraem yu klai"],
    "以前": ["我以前住这里。", "Wǒ yǐqián zhù zhèlǐ.", "ฉันเคยอยู่ที่นี่มาก่อน", "chan khoei yu thi ni ma kon"],
    "以后": ["我以后再来。", "Wǒ yǐhòu zài lái.", "ฉันจะมาทีหลัง", "chan cha ma thi lang"],
    "什么": ["这是什么？", "Zhè shì shénme?", "นี่คืออะไร", "ni khue arai"],
    "谁": ["他是谁？", "Tā shì shéi?", "เขาคือใคร", "khao khue khrai"],
    "为什么": ["你为什么走？", "Nǐ wèishénme zǒu?", "คุณไปทำไม", "khun pai thammai"],
    "怎么": ["这个怎么用？", "Zhège zěnme yòng?", "อันนี้ใช้อย่างไร", "an ni chai yang rai"],
    "是": ["是，我知道。", "Shì, wǒ zhīdào.", "ใช่ ฉันรู้", "chai chan ru"],
    "不是": ["这不是水。", "Zhè bú shì shuǐ.", "นี่ไม่ใช่น้ำ", "ni mai chai nam"],
    "请": ["请进。", "Qǐng jìn.", "กรุณาเข้ามา", "karuna khao ma"],
    "可以": ["我可以进去吗？", "Wǒ kěyǐ jìnqù ma?", "ฉันเข้าไปได้ไหม", "chan khao pai dai mai"],
    "不可以": ["这里不可以停车。", "Zhèlǐ bù kěyǐ tíngchē.", "ที่นี่จอดรถไม่ได้", "thi ni chot rot mai dai"],
    "喜欢": ["我喜欢咖啡。", "Wǒ xǐhuan kāfēi.", "ฉันชอบกาแฟ", "chan chop kafae"],
    "不喜欢": ["我不喜欢辣。", "Wǒ bù xǐhuan là.", "ฉันไม่ชอบเผ็ด", "chan mai chop phet"],
    "不好": ["这里很不好。", "Zhèlǐ hěn bùhǎo.", "ที่นี่ไม่ดีเลย", "thi ni mai di loei"],
    "饿": ["我很饿。", "Wǒ hěn è.", "ฉันหิวมาก", "chan hiu mak"],
    "渴": ["我很渴。", "Wǒ hěn kě.", "ฉันกระหายน้ำมาก", "chan krahai nam mak"],
    "餐馆": ["附近有餐馆吗？", "Fùjìn yǒu cānguǎn ma?", "แถวนี้มีร้านอาหารไหม", "thaeo ni mi ran ahan mai"],
    "这里": ["我在这里。", "Wǒ zài zhèlǐ.", "ฉันอยู่ที่นี่", "chan yu thi ni"],
    "到": ["我们到了。", "Wǒmen dào le.", "เราถึงแล้ว", "rao thueng laeo"],
    "迷路": ["我迷路了。", "Wǒ mílù le.", "ฉันหลงทางแล้ว", "chan long thang laeo"],
    "帮助": ["请帮助我。", "Qǐng bāngzhù wǒ.", "ช่วยฉันด้วย", "chuai chan duai"],
    "危险": ["这里有危险。", "Zhèlǐ yǒu wēixiǎn.", "ที่นี่มีอันตราย", "thi ni mi antarai"],
    "火灾": ["那里发生了火灾。", "Nàlǐ fāshēng le huǒzāi.", "ที่นั่นเกิดไฟไหม้", "thi nan koet fai mai"],
    "停": ["请停一下。", "Qǐng tíng yíxià.", "กรุณาหยุดสักครู่", "karuna yut sak khru"],
    "医院": ["附近有医院吗？", "Fùjìn yǒu yīyuàn ma?", "แถวนี้มีโรงพยาบาลไหม", "thaeo ni mi rong phayaban mai"],
    "药店": ["附近有药店吗？", "Fùjìn yǒu yàodiàn ma?", "แถวนี้มีร้านขายยาไหม", "thaeo ni mi ran khai ya mai"],
    "疼": ["我这里疼。", "Wǒ zhèlǐ téng.", "ฉันเจ็บตรงนี้", "chan chep trong ni"],
    "生病": ["我生病了。", "Wǒ shēngbìng le.", "ฉันป่วย", "chan puai"],
    "发烧": ["我发烧了。", "Wǒ fāshāo le.", "ฉันเป็นไข้", "chan pen khai"],
    "头痛": ["我头痛。", "Wǒ tóutòng.", "ฉันปวดหัว", "chan puat hua"],
    "肚子痛": ["我肚子痛。", "Wǒ dùzi tòng.", "ฉันปวดท้อง", "chan puat thong"],
    "过敏": ["我对花生过敏。", "Wǒ duì huāshēng guòmǐn.", "ฉันแพ้ถั่วลิสง", "chan phae thua lisong"],
    "丢了": ["我的包丢了。", "Wǒ de bāo diū le.", "กระเป๋าของฉันหาย", "krapao khong chan hai"],
    "顾问": ["她是我们的顾问。", "Tā shì wǒmen de gùwèn.", "เธอเป็นที่ปรึกษาของเรา", "thoe pen thi prueksa khong rao"],
    "成年人": ["他是成年人。", "Tā shì chéngniánrén.", "เขาเป็นผู้ใหญ่แล้ว", "khao pen phu-yai laeo"],
    "年轻人": ["这里有很多年轻人。", "Zhèlǐ yǒu hěn duō niánqīngrén.", "ที่นี่มีคนหนุ่มสาวเยอะ", "thi ni mi khon num-sao yoe"],
    "外国人": ["我是外国人。", "Wǒ shì wàiguórén.", "ฉันเป็นชาวต่างชาติ", "chan pen chao tang-chat"],
    "本地人": ["他是本地人。", "Tā shì běndìrén.", "เขาเป็นคนท้องถิ่น", "khao pen khon thong-thin"],
    "忘记": ["我忘记带钥匙了。", "Wǒ wàngjì dài yàoshi le.", "ฉันลืมเอากุญแจมา", "chan luem ao kunchae ma"],
    "记得": ["我记得你的名字。", "Wǒ jìde nǐ de míngzi.", "ฉันจำได้ว่าคุณชื่ออะไร", "chan cham dai wa khun chue arai"],
    "睡过头": ["我今天睡过头了。", "Wǒ jīntiān shuìguòtóu le.", "วันนี้ฉันตื่นสาย", "wan ni chan tuen sai"],
    "延误": ["航班延误了。", "Hángbān yánwù le.", "เที่ยวบินล่าช้า", "thiao-bin la-cha"],
    "取消": ["航班取消了。", "Hángbān qǔxiāo le.", "เที่ยวบินถูกยกเลิก", "thiao-bin thuk yok-loek"],
    "靠窗": ["我要靠窗的座位。", "Wǒ yào kàochuāng de zuòwèi.", "ฉันเอาที่นั่งริมหน้าต่าง", "chan ao thi nang rim na-tang"],
    "堵车": ["路上堵车。", "Lùshang dǔchē.", "ถนนเส้นนี้รถติด", "thanon sen ni rot tit"],
    "打折": ["这件衣服打折吗？", "Zhè jiàn yīfu dǎzhé ma?", "เสื้อตัวนี้ลดราคาไหม", "suea tua ni lot rakha mai"],
    "第二件": ["第二件半价。", "Dì èr jiàn bànjià.", "ชิ้นที่สองลดครึ่งราคา", "chin thi song lot khrueng rakha"],
    "期间": ["假期期间很热。", "Jiàqī qījiān hěn rè.", "ในช่วงวันหยุดอากาศร้อน", "nai chuang wan-yut akat ron"],
    "有空": ["我今天有空。", "Wǒ jīntiān yǒukòng.", "วันนี้ฉันว่าง", "wan ni chan wang"],
    "迟到": ["我今天迟到了。", "Wǒ jīntiān chídào le.", "วันนี้ฉันมาสาย", "wan ni chan ma sai"],
    "推迟": ["会议推迟了。", "Huìyì tuīchí le.", "การประชุมเลื่อนออกไป", "kan prachum luean ok pai"],
    "企业": ["我在这家企业工作。", "Wǒ zài zhè jiā qǐyè gōngzuò.", "ฉันทำงานที่องค์กรธุรกิจนี้", "chan tham-ngan thi ongkon thurakit ni"],
    "想念": ["我很想念你。", "Wǒ hěn xiǎngniàn nǐ.", "ฉันคิดถึงคุณมาก", "chan khit-thueng khun mak"],
    "咳嗽": ["我一直咳嗽。", "Wǒ yìzhí késou.", "ฉันไอไม่หยุด", "chan ai mai yut"],
    "受伤": ["他的手受伤了。", "Tā de shǒu shòushāng le.", "มือของเขาบาดเจ็บ", "mue khong khao bat-chep"],
    "流血": ["我的手在流血。", "Wǒ de shǒu zài liúxuè.", "มือของฉันเลือดออก", "mue khong chan lueat ok"],
    "检查": ["医生正在检查。", "Yīshēng zhèngzài jiǎnchá.", "หมอกำลังตรวจร่างกาย", "mo kamlang truat rang-kai"],
    "打针": ["我不怕打针。", "Wǒ bú pà dǎzhēn.", "ฉันไม่กลัวฉีดยา", "chan mai klua chit ya"],
    "皮疹": ["我起了皮疹。", "Wǒ qǐ le pízhěn.", "ฉันมีผื่นขึ้น", "chan mi phuen khuen"],
    "烟雾": ["这里有很多烟雾。", "Zhèlǐ yǒu hěn duō yānwù.", "ที่นี่มีควันมาก", "thi ni mi khwan mak"],
    "事故": ["这里发生了事故。", "Zhèlǐ fāshēng le shìgù.", "เกิดอุบัติเหตุที่นี่", "koet ubattihet thi ni"],
    "财物失窃": ["财物失窃了。", "Cáiwù shīqiè le.", "ทรัพย์สินถูกขโมย", "sapsin thuk khamoi"],
    "丢失": ["我的护照丢失了。", "Wǒ de hùzhào diūshī le.", "หนังสือเดินทางของฉันสูญหาย", "nangsue doen-thang khong chan sun-hai"],
    "礼貌": ["说话要有礼貌。", "Shuōhuà yào yǒu lǐmào.", "พูดจาด้วยความสุภาพ", "phut-cha duai khwam suphap"],
    "面子": ["他很在意面子。", "Tā hěn zàiyì miànzi.", "เขาใส่ใจเรื่องการรักษาหน้า", "khao sai-chai rueang kan raksa na"]
  };

  function makeExample(cat, pos, zh, py, th, ro) {
    if (SPECIAL_EXAMPLES[zh]) {
      const [exZh, exPy, exTh, exRo] = SPECIAL_EXAMPLES[zh];
      return { exZh, exPy, exTh, exRo };
    }
    if (phraseLike.has(pos)) {
      return { exZh: zh + "。", exPy: py + ".", exTh: th, exRo: ro };
    }
    if (pos === "pron") {
      return { exZh: zh + "也去。", exPy: py + " yě qù.", exTh: th + "ก็ไปด้วย", exRo: ro + " ko pai duai" };
    }
    if (pos === "v") {
      return { exZh: "我想" + zh + "。", exPy: "Wǒ xiǎng " + py + ".", exTh: "ฉันอยาก" + th, exRo: "chan yak " + ro };
    }
    if (pos === "adj") {
      return { exZh: "这里很" + zh + "。", exPy: "Zhèlǐ hěn " + py + ".", exTh: "ที่นี่" + th + "มาก", exRo: "thi-ni " + ro + " mak" };
    }
    if (pos === "adv") {
      return { exZh: "我" + zh + "去。", exPy: "Wǒ " + py + " qù.", exTh: "ฉันไป" + th, exRo: "chan pai " + ro };
    }
    if (pos === "num" || pos === "clf") {
      return { exZh: "这个数字是" + zh + "。", exPy: "Zhège shùzì shì " + py + ".", exTh: "ตัวเลขนี้คือ" + th, exRo: "tua-lek ni khue " + ro };
    }
    if (cat === "people") {
      return { exZh: "他是我的" + zh + "。", exPy: "Tā shì wǒ de " + py + ".", exTh: "เขาเป็น" + th + "ของฉัน", exRo: "khao pen " + ro + " khong chan" };
    }
    if (cat === "food") {
      return { exZh: "我要" + zh + "。", exPy: "Wǒ yào " + py + ".", exTh: "ฉันเอา" + th, exRo: "chan ao " + ro };
    }
    if (cat === "travel") {
      return { exZh: "我在找" + zh + "。", exPy: "Wǒ zài zhǎo " + py + ".", exTh: "ฉันกำลังหา" + th, exRo: "chan kamlang ha " + ro };
    }
    if (cat === "shopping") {
      return { exZh: "有" + zh + "吗？", exPy: "Yǒu " + py + " ma?", exTh: "มี" + th + "ไหม", exRo: "mi " + ro + " mai" };
    }
    if (cat === "work" || cat === "study") {
      return { exZh: "这是我的" + zh + "。", exPy: "Zhè shì wǒ de " + py + ".", exTh: "นี่คือ" + th + "ของฉัน", exRo: "ni khue " + ro + " khong chan" };
    }
    if (cat === "health" || cat === "emergency") {
      return { exZh: "我需要" + zh + "。", exPy: "Wǒ xūyào " + py + ".", exTh: "ฉันต้องการ" + th, exRo: "chan tongkan " + ro };
    }
    if (cat === "culture") {
      return { exZh: "我知道" + zh + "。", exPy: "Wǒ zhīdào " + py + ".", exTh: "ฉันรู้จัก" + th, exRo: "chan ru-chak " + ro };
    }
    return { exZh: "这是" + zh + "。", exPy: "Zhè shì " + py + ".", exTh: "นี่คือ" + th, exRo: "ni khue " + ro };
  }

  function expand(rows, level) {
    return rows.map((row, index) => {
      const [cat, pos, zh, py, th, ro, noteZh = "", noteTh = ""] = row;
      return {
        id: `l${level}-${String(index + 1).padStart(3, "0")}`,
        level,
        cat,
        pos,
        zh,
        py,
        th,
        ro,
        ...makeExample(cat, pos, zh, py, th, ro),
        noteZh,
        noteTh
      };
    });
  }

  window.HUILAISHI_VOCAB_L12 = [...expand(L1, 1), ...expand(L2, 2)];
})();
