/* 会来事 · L5/L6 双向核心词库
 * Chinese pinyin uses tone marks. Thai romanization follows one consistent,
 * learner-friendly RTGS-style convention. Every runtime entry is fully expanded.
 */
(function () {
  "use strict";

  const cap = s => s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
  const patterns = {
    discuss: r => [`我们需要讨论${r.zh}。`, `Wǒmen xūyào tǎolùn ${r.py}.`, `เราต้องหารือเรื่อง${r.th}`, `rao tong harue rueang ${r.ro}`],
    opinion: r => [`我想听听你的${r.zh}。`, `Wǒ xiǎng tīngting nǐ de ${r.py}.`, `ฉันอยากฟัง${r.th}ของคุณ`, `chan yak fang ${r.ro} khong khun`],
    consider: r => [`我们也要考虑${r.zh}。`, `Wǒmen yě yào kǎolǜ ${r.py}.`, `เราต้องคำนึงถึง${r.th}ด้วย`, `rao tong khamnueng thueng ${r.ro} duai`],
    important: r => [`${r.zh}很重要。`, `${cap(r.py)} hěn zhòngyào.`, `${r.th}สำคัญมาก`, `${cap(r.ro)} samkhan mak`],
    affect: r => [`${r.zh}会影响结果。`, `${cap(r.py)} huì yǐngxiǎng jiéguǒ.`, `${r.th}จะส่งผลต่อผลลัพธ์`, `${cap(r.ro)} cha song phon to phonlap`],
    need: r => [`这个项目需要${r.zh}。`, `Zhège xiàngmù xūyào ${r.py}.`, `โครงการนี้ต้องการ${r.th}`, `khrongkan ni tongkan ${r.ro}`],
    do: r => [`项目推进时常会用到“${r.zh}”这个词。`, `Xiàngmù tuījìn shí cháng huì yòngdào “${r.py}” zhège cí.`, `ระหว่างดำเนินโครงการมักใช้คำว่า “${r.th}”`, `rawang damnoen khrongkan mak chai kham wa “${r.ro}”`],
    today: r => [`今天的任务包括“${r.zh}”。`, `Jīntiān de rènwu bāokuò “${r.py}”.`, `งานวันนี้รวมถึงการ “${r.th}”`, `ngan wan ni ruam thueng kan “${r.ro}”`],
    meeting: r => [`会议中常会听到“${r.zh}”这个词。`, `Huìyì zhōng cháng huì tīngdào “${r.py}” zhège cí.`, `ในที่ประชุมมักได้ยินคำว่า “${r.th}”`, `nai thi prachum mak dai yin kham wa “${r.ro}”`],
    career: r => [`我想了解${r.zh}。`, `Wǒ xiǎng liǎojiě ${r.py}.`, `ฉันอยากทราบเรื่อง${r.th}`, `chan yak sap rueang ${r.ro}`],
    person: r => [`那位是${r.zh}。`, `Nà wèi shì ${r.py}.`, `คนนั้นคือ${r.th}`, `khon nan khue ${r.ro}`],
    personquality: r => [`她在工作中很${r.zh}。`, `Tā zài gōngzuò zhōng hěn ${r.py}.`, `เธอ${r.th}มากในการทำงาน`, `thoe ${r.ro} mak nai kan thamngan`],
    quality: r => [`大家认为这个方案${r.zh}。`, `Dàjiā rènwéi zhège fāng'àn ${r.py}.`, `ทุกคนเห็นว่าแนวทางนี้${r.th}`, `thuk khon hen wa naeo thang ni ${r.ro}`],
    system: r => [`请检查${r.zh}。`, `Qǐng jiǎnchá ${r.py}.`, `กรุณาตรวจสอบ${r.th}`, `karuna truatsop ${r.ro}`],
    techdo: r => [`请先${r.zh}。`, `Qǐng xiān ${r.py}.`, `กรุณา${r.th}ก่อน`, `karuna ${r.ro} kon`],
    techcheck: r => [`请确认${r.zh}是否正常。`, `Qǐng quèrèn ${r.py} shìfǒu zhèngcháng.`, `กรุณาตรวจสอบว่า${r.th}ทำงานปกติหรือไม่`, `karuna truatsop wa ${r.ro} thamngan pokkati rue mai`],
    techissue: r => [`${r.zh}已经报告给技术团队。`, `${cap(r.py)} yǐjīng bàogào gěi jìshù tuánduì.`, `ได้รายงาน${r.th}ให้ทีมเทคนิคแล้ว`, `dai raingan ${r.ro} hai thim theknik laeo`],
    society: r => [`${r.zh}是常见的社会议题。`, `${cap(r.py)} shì chángjiàn de shèhuì yìtí.`, `${r.th}เป็นประเด็นสังคมที่พบได้บ่อย`, `${cap(r.ro)} pen praden sangkhom thi phop dai boi`],
    culture: r => [`我想进一步了解${r.zh}。`, `Wǒ xiǎng jìnyíbù liǎojiě ${r.py}.`, `ฉันอยากเข้าใจ${r.th}ให้มากขึ้น`, `chan yak khaochai ${r.ro} hai mak khuen`],
    trend: r => [`${r.zh}正在发生变化。`, `${cap(r.py)} zhèngzài fāshēng biànhuà.`, `${r.th}กำลังเปลี่ยนแปลง`, `${cap(r.ro)} kamlang plianplaeng`],
    public: r => [`我们应该关注${r.zh}。`, `Wǒmen yīnggāi guānzhù ${r.py}.`, `เราควรใส่ใจ${r.th}`, `rao khuan saichai ${r.ro}`],
    abstract: r => [`理解${r.zh}并不容易。`, `Lǐjiě ${r.py} bìng bù róngyì.`, `การเข้าใจ${r.th}ไม่ใช่เรื่องง่าย`, `kan khaochai ${r.ro} mai chai rueang ngai`],
    view: r => [`“${r.zh}”是讨论中的关键词。`, `“${cap(r.py)}” shì tǎolùn zhōng de guānjiàncí.`, `“${r.th}” เป็นคำสำคัญในการหารือ`, `“${r.ro}” pen kham samkhan nai kan harue`],
    mainPoint: r => [`我们先说${r.zh}。`, `Wǒmen xiān shuō ${r.py}.`, `เรามาพูดถึง${r.th}ก่อน`, `rao ma phut thueng ${r.ro} kon`],
    confidentPerson: r => [`她在会上表现得很${r.zh}。`, `Tā zài huì shàng biǎoxiàn de hěn ${r.py}.`, `เธอดู${r.th}มากในที่ประชุม`, `thoe du ${r.ro} mak nai thi prachum`],
    youthGroup: r => [`${r.zh}群体值得关注。`, `${cap(r.py)} qúntǐ zhídé guānzhù.`, `กลุ่ม${r.th}ควรได้รับความสนใจ`, `klum ${r.ro} khuan dai rap khwam sonchai`],
    directAffect: r => [`这项政策会${r.zh}青年。`, `Zhè xiàng zhèngcè huì ${r.py} qīngnián.`, `นโยบายนี้จะ${r.th}ต่อเยาวชน`, `nayobai ni cha ${r.ro} to yaowachon`],
    say: r => [`${r.zh}。`, `${cap(r.py)}.`, `${r.th}`, `${cap(r.ro)}.`]
  };

  /* row: cat, pos, zh, pinyin, Thai, Thai romanization, pattern,
     optional noteZh, optional noteTh */
  const L5 = [
    // 001–025 · viewpoints and decision factors
    ['work','n','意见','yìjiàn','ความคิดเห็น','khwam khithen','opinion'],
    ['work','n','看法','kànfǎ','มุมมอง','mum mong','discuss'],
    ['work','n','观点','guāndiǎn','ทัศนะ','thatsana','discuss'],
    ['work','n','立场','lìchǎng','จุดยืน','chutyuen','consider'],
    ['work','n','原因','yuányīn','สาเหตุ','sahet','discuss'],
    ['work','n','结果','jiéguǒ','ผลลัพธ์','phonlap','consider'],
    ['work','n','影响','yǐngxiǎng','ผลกระทบ','phonkathop','consider'],
    ['work','n','问题','wèntí','ปัญหา','panha','discuss'],
    ['work','n','方法','fāngfǎ','วิธีการ','withikan','discuss'],
    ['work','n','重点','zhòngdiǎn','ประเด็นหลัก','praden lak','mainPoint'],
    ['work','n','细节','xìjié','รายละเอียด','ra-iat','consider'],
    ['work','n','条件','tiáojiàn','เงื่อนไข','ngueankhai','consider'],
    ['work','n','要求','yāoqiú','ข้อกำหนด','kho kamnot','consider'],
    ['work','n','标准','biāozhǔn','มาตรฐาน','mattrathan','important'],
    ['work','n','原则','yuánzé','หลักการ','lakkan','important'],
    ['work','n','范围','fànwéi','ขอบเขต','khopkhet','discuss'],
    ['work','n','方向','fāngxiàng','ทิศทาง','thitthang','important'],
    ['work','n','机会','jīhuì','โอกาส','okat','consider'],
    ['work','n','风险','fēngxiǎn','ความเสี่ยง','khwam siang','consider'],
    ['work','n','挑战','tiǎozhàn','ความท้าทาย','khwam thathai','consider'],
    ['work','n','优势','yōushì','จุดแข็ง','chut khaeng','discuss'],
    ['work','n','劣势','lièshì','จุดอ่อน','chut on','discuss'],
    ['work','n','可能性','kěnéngxìng','ความเป็นไปได้','khwam pen pai dai','consider'],
    ['work','n','必要性','bìyàoxìng','ความจำเป็น','khwam champen','consider'],
    ['work','n','可行性','kěxíngxìng','ความเป็นไปได้ในการดำเนินการ','khwam pen pai dai nai kan damnoenkan','discuss'],

    // 026–050 · expressing and evaluating views
    ['work','v','表达','biǎodá','แสดงความคิดเห็น','sadaeng khwam khithen','meeting'],
    ['work','v','说明','shuōmíng','ชี้แจง','chichaeng','meeting'],
    ['work','v','解释','jiěshì','อธิบาย','athibai','meeting'],
    ['work','v','强调','qiángdiào','เน้นย้ำ','nen yam','meeting'],
    ['work','v','补充','bǔchōng','เสริมข้อมูล','soem khomun','meeting'],
    ['work','v','提出','tíchū','เสนอประเด็น','sanoe praden','meeting'],
    ['work','v','支持','zhīchí','สนับสนุน','sanapsanun','do'],
    ['work','v','反对','fǎnduì','คัดค้าน','khatkhan','meeting'],
    ['work','v','同意','tóngyì','เห็นด้วย','hen duai','meeting'],
    ['work','v','不同意','bù tóngyì','ไม่เห็นด้วย','mai hen duai','meeting'],
    ['work','v','接受','jiēshòu','ยอมรับ','yomrap','do'],
    ['work','v','考虑','kǎolǜ','พิจารณา','phicharana','today'],
    ['work','v','评估','pínggū','ประเมิน','pramoen','today'],
    ['work','v','判断','pànduàn','ตัดสินเชิงเหตุผล','tatsin choeng hetphon','today'],
    ['work','v','预测','yùcè','คาดการณ์','khatkan','today'],
    ['work','v','证明','zhèngmíng','พิสูจน์','phisut','meeting'],
    ['work','v','质疑','zhìyí','ตั้งข้อสงสัย','tang kho songsai','meeting'],
    ['work','v','澄清','chéngqīng','ทำให้กระจ่าง','tham hai krachang','meeting'],
    ['work','v','提醒','tíxǐng','เตือนให้ทราบ','tuean hai sap','do'],
    ['work','v','承认','chéngrèn','ยอมรับข้อเท็จจริง','yomrap kho thetching','meeting'],
    ['work','v','否认','fǒurèn','ปฏิเสธข้อกล่าว','patiset kho klao','meeting'],
    ['work','v','保证','bǎozhèng','รับรอง','raprong','do'],
    ['work','v','承诺','chéngnuò','ให้คำมั่น','hai khamman','do'],
    ['work','v','询问','xúnwèn','สอบถาม','soptham','meeting'],
    ['work','v','回应','huíyìng','ตอบสนอง','topsanong','meeting'],

    // 051–075 · negotiation and management actions
    ['work','v','达成','dáchéng','บรรลุร่วมกัน','banlu ruam kan','do'],
    ['work','v','谈判','tánpàn','เจรจาต่อรอง','cheracha torong','today'],
    ['work','v','协商','xiéshāng','ปรึกษาหารือ','prueksa harue','today'],
    ['work','v','妥协','tuǒxié','ประนีประนอม','pranipranom','today'],
    ['work','v','争取','zhēngqǔ','พยายามให้ได้มา','phayayam hai dai ma','do'],
    ['work','v','调整','tiáozhěng','ปรับให้เหมาะสม','prap hai mosom','do'],
    ['work','v','优化','yōuhuà','ปรับให้มีประสิทธิภาพ','prap hai mi prasitthiphap','do'],
    ['work','v','改进','gǎijìn','ปรับปรุงให้ดีขึ้น','prapprung hai di khuen','do'],
    ['work','v','控制','kòngzhì','ควบคุม','khuapkhum','do'],
    ['work','v','管理','guǎnlǐ','บริหารจัดการ','borihan chatkan','do'],
    ['work','v','分配','fēnpèi','จัดสรร','chatsan','do'],
    ['work','v','承担','chéngdān','รับภาระ','rap phara','do'],
    ['work','v','避免','bìmiǎn','หลีกเลี่ยง','likliang','do'],
    ['work','v','减少','jiǎnshǎo','ลดจำนวน','lot chamnuan','do'],
    ['work','v','增加','zēngjiā','เพิ่มจำนวน','phoem chamnuan','do'],
    ['work','v','扩大','kuòdà','ขยายให้กว้างขึ้น','khayai hai kwang khuen','do'],
    ['work','v','缩小','suōxiǎo','ลดขนาดลง','lot khanat long','do'],
    ['work','v','保持','bǎochí','รักษาไว้','raksa wai','do'],
    ['work','v','促进','cùjìn','ส่งเสริม','songsoem','do'],
    ['work','v','推动','tuīdòng','ผลักดัน','phlakdan','do'],
    ['work','v','建立','jiànlì','จัดตั้ง','chattang','do'],
    ['work','v','实施','shíshī','นำไปใช้','nam pai chai','do'],
    ['work','v','执行','zhíxíng','ดำเนินการ','damnoenkan','do'],
    ['work','v','监督','jiāndū','กำกับดูแล','kamkap dulae','do'],
    ['work','v','衡量','héngliáng','วัดผล','wat phon','do'],

    // 076–100 · meeting discourse
    ['work','phrase','我同意这个看法','wǒ tóngyì zhège kànfǎ','ฉันเห็นด้วยกับมุมมองนี้','chan hen duai kap mum mong ni','say'],
    ['work','phrase','我有不同意见','wǒ yǒu bùtóng yìjiàn','ฉันมีความคิดเห็นต่าง','chan mi khwam khithen tang','say'],
    ['work','phrase','从我的角度看','cóng wǒ de jiǎodù kàn','จากมุมของฉัน','chak mum khong chan','say'],
    ['work','phrase','换句话说','huàn jù huà shuō','พูดอีกอย่างหนึ่ง','phut ik yang nueng','say'],
    ['work','phrase','具体来说','jùtǐ lái shuō','กล่าวให้เจาะจง','klao hai chochong','say'],
    ['work','phrase','总的来说','zǒng de lái shuō','กล่าวโดยรวม','klao doi ruam','say'],
    ['work','phrase','简单来说','jiǎndān lái shuō','พูดง่าย ๆ','phut ngai ngai','say'],
    ['work','phrase','举个例子','jǔ ge lìzi','ขอยกตัวอย่าง','kho yok tuayang','say'],
    ['work','phrase','一方面','yì fāngmiàn','ในด้านหนึ่ง','nai dan nueng','say'],
    ['work','phrase','另一方面','lìng yì fāngmiàn','ในอีกด้านหนึ่ง','nai ik dan nueng','say'],
    ['work','adv','首先','shǒuxiān','ประการแรก','prakan raek','say'],
    ['work','adv','其次','qícì','ประการถัดมา','prakan that ma','say'],
    ['work','adv','最后','zuìhòu','ประการสุดท้าย','prakan sutthai','say'],
    ['work','conj','因此','yīncǐ','ดังนั้น','dangnan','say'],
    ['work','conj','不过','búguò','อย่างไรก็ตาม','yangraikotam','say'],
    ['work','conj','与此同时','yǔ cǐ tóngshí','ในขณะเดียวกัน','nai khana diao kan','say'],
    ['work','phrase','据我了解','jù wǒ liǎojiě','เท่าที่ฉันทราบ','thao thi chan sap','say'],
    ['work','phrase','目前看来','mùqián kànlái','เท่าที่เห็นในขณะนี้','thao thi hen nai khana ni','say'],
    ['work','phrase','如果没问题','rúguǒ méi wèntí','หากไม่มีปัญหา','hak maimi panha','say'],
    ['work','phrase','我想补充一点','wǒ xiǎng bǔchōng yìdiǎn','ฉันขอเสริมอีกนิด','chan kho soem ik nit','say'],
    ['work','phrase','能否解释一下','néngfǒu jiěshì yíxià','ช่วยอธิบายสักหน่อยได้ไหม','chuai athibai sak noi dai mai','say'],
    ['work','phrase','请继续','qǐng jìxù','เชิญพูดต่อ','choen phut to','say'],
    ['work','phrase','让我们回到主题','ràng wǒmen huí dào zhǔtí','กลับมาที่หัวข้อกันเถอะ','klap ma thi huakho kan thoe','say'],
    ['work','phrase','这个问题稍后再谈','zhège wèntí shāohòu zài tán','เรื่องนี้ไว้คุยภายหลัง','rueang ni wai khui phailang','say'],
    ['work','phrase','我们达成共识了吗','wǒmen dáchéng gòngshí le ma','เรามีข้อสรุปร่วมกันแล้วใช่ไหม','rao mi kho sarup ruam kan laeo chai mai','say'],

    // 101–125 · business essentials
    ['work','n','成本','chéngběn','ต้นทุน','tonthun','consider'],
    ['work','n','收入','shōurù','รายได้','raidai','consider'],
    ['work','n','利润','lìrùn','กำไร','kamrai','important'],
    ['work','n','损失','sǔnshī','ความสูญเสีย','khwam sunsia','consider'],
    ['work','n','销量','xiāoliàng','ยอดขาย','yot khai','affect'],
    ['work','n','市场份额',"shìchǎng fèn'é",'ส่วนแบ่งตลาด','suan baeng talat','important'],
    ['work','n','需求','xūqiú','ความต้องการของตลาด','khwam tongkan khong talat','consider'],
    ['work','n','供给','gōngjǐ','อุปทาน','uppathan','consider'],
    ['work','n','资源','zīyuán','ทรัพยากร','sapphayakon','need'],
    ['work','n','产能','chǎnnéng','กำลังการผลิต','kamlang kan phalit','consider'],
    ['work','n','库存','kùcún','สินค้าคงคลัง','sinkha khongkhlang','consider'],
    ['work','n','质量控制','zhìliàng kòngzhì','การควบคุมคุณภาพ','kan khuapkhum khunnaphap','important'],
    ['work','n','客户体验','kèhù tǐyàn','ประสบการณ์ลูกค้า','prasopkan lukkha','important'],
    ['work','n','用户需求','yònghù xūqiú','ความต้องการของผู้ใช้','khwam tongkan khong phuchai','consider'],
    ['work','n','品牌','pǐnpái','แบรนด์','braen','important'],
    ['work','n','竞争','jìngzhēng','การแข่งขัน','kan khaengkhan','affect'],
    ['work','n','趋势','qūshì','แนวโน้ม','naewnom','affect'],
    ['work','n','策略','cèlüè','กลยุทธ์','konlayut','discuss'],
    ['work','n','渠道','qúdào','ช่องทางการขาย','chongthang kan khai','discuss'],
    ['work','n','服务','fúwù','การบริการ','kan borikan','important'],
    ['work','n','产品','chǎnpǐn','ผลิตภัณฑ์','phalittaphan','discuss'],
    ['work','n','功能','gōngnéng','ฟังก์ชันการใช้งาน','fangchan kan chaingan','discuss'],
    ['work','n','设计','shèjì','งานออกแบบ','ngan okbaep','discuss'],
    ['work','n','技术','jìshù','เทคโนโลยี','theknoloyi','important'],
    ['work','n','系统','xìtǒng','ระบบ','rabop','important'],

    // 126–150 · business action phrases
    ['work','phrase','降低成本','jiàngdī chéngběn','ลดต้นทุน','lot tonthun','say'],
    ['work','phrase','提高效率','tígāo xiàolǜ','เพิ่มประสิทธิภาพ','phoem prasitthiphap','say'],
    ['work','phrase','扩大市场','kuòdà shìchǎng','ขยายตลาด','khayai talat','say'],
    ['work','phrase','改善服务','gǎishàn fúwù','พัฒนาการบริการ','phatthana kan borikan','say'],
    ['work','phrase','满足需求','mǎnzú xūqiú','ตอบสนองความต้องการ','topsanong khwam tongkan','say'],
    ['work','phrase','完成目标','wánchéng mùbiāo','บรรลุเป้าหมาย','banlu paomai','say'],
    ['work','phrase','解决冲突','jiějué chōngtū','แก้ไขข้อขัดแย้ง','kaekhai kho khatyaeng','say'],
    ['work','phrase','管理风险','guǎnlǐ fēngxiǎn','บริหารความเสี่ยง','borihan khwam siang','say'],
    ['work','phrase','分配资源','fēnpèi zīyuán','จัดสรรทรัพยากร','chatsan sapphayakon','say'],
    ['work','phrase','制定策略','zhìdìng cèlüè','กำหนดกลยุทธ์','kamnot konlayut','say'],
    ['work','phrase','收集信息','shōují xìnxī','รวบรวมข้อมูลข่าวสาร','ruapruam khomun khaosan','say'],
    ['work','phrase','研究市场','yánjiū shìchǎng','ศึกษาตลาด','sueksa talat','say'],
    ['work','phrase','测试产品','cèshì chǎnpǐn','ทดสอบผลิตภัณฑ์','thotsop phalittaphan','say'],
    ['work','phrase','发布产品','fābù chǎnpǐn','เปิดตัวผลิตภัณฑ์','poettua phalittaphan','say'],
    ['work','phrase','维护系统','wéihù xìtǒng','บำรุงรักษาระบบ','bamrung raksa rabop','say'],
    ['work','phrase','培养人才','péiyǎng réncái','พัฒนาบุคลากร','phatthana bukhlakon','say'],
    ['work','phrase','留住客户','liúzhù kèhù','รักษาฐานลูกค้า','raksa than lukkha','say'],
    ['work','phrase','赢得信任','yíngdé xìnrèn','ได้รับความไว้วางใจ','dai rap khwam waiwangchai','say'],
    ['work','phrase','创造价值','chuàngzào jiàzhí','สร้างคุณค่า','sang khunkha','say'],
    ['work','phrase','承担责任','chéngdān zérèn','รับผิดชอบหน้าที่','rapphitchop nathi','say'],
    ['work','phrase','遵守规定','zūnshǒu guīdìng','ปฏิบัติตามข้อบังคับ','patibat tam kho bangkhap','say'],
    ['work','phrase','保护信息','bǎohù xìnxī','ปกป้องสารสนเทศ','pokpong sarasonthet','say'],
    ['work','phrase','控制预算','kòngzhì yùsuàn','ควบคุมงบประมาณ','khuapkhum ngoppraman','say'],
    ['work','phrase','监控进度','jiānkòng jìndù','เฝ้าติดตามความคืบหน้า','fao tittam khwam khuepna','say'],
    ['work','phrase','评估效果','pínggū xiàoguǒ','ประเมินผลสัมฤทธิ์','pramoen phon samrit','say'],

    // 151–175 · professional abilities and qualities
    ['work','n','沟通能力','gōutōng nénglì','ทักษะการสื่อสาร','thaksa kan suesan','important'],
    ['work','n','领导力','lǐngdǎolì','ภาวะผู้นำ','phawa phunam','important'],
    ['work','n','执行力','zhíxínglì','ความสามารถในการลงมือทำ','khwam samat nai kan longmue tham','important'],
    ['work','n','创造力','chuàngzàolì','ความคิดสร้างสรรค์','khwam khit sangsan','important'],
    ['work','n','适应能力','shìyìng nénglì','ความสามารถในการปรับตัว','khwam samat nai kan praptua','important'],
    ['work','n','学习能力','xuéxí nénglì','ความสามารถในการเรียนรู้','khwam samat nai kan rianru','important'],
    ['work','n','判断力','pànduànlì','วิจารณญาณ','wicharanayan','important'],
    ['work','n','解决问题能力','jiějué wèntí nénglì','ทักษะการแก้ปัญหา','thaksa kan kae panha','important'],
    ['work','n','时间管理','shíjiān guǎnlǐ','การบริหารเวลา','kan borihan wela','important'],
    ['work','n','团队精神','tuánduì jīngshén','จิตวิญญาณทีม','chitwinyan thim','important'],
    ['work','n','工作态度','gōngzuò tàidu','ทัศนคติในการทำงาน','thatsanakhati nai kan thamngan','important'],
    ['work','adj','可靠','kěkào','น่าเชื่อถือ','na chueathue','personquality'],
    ['work','adj','自信','zìxìn','มั่นใจ','manchai','confidentPerson'],
    ['work','adj','开放','kāifàng','เปิดรับความคิดเห็น','poet rap khwam khithen','personquality'],
    ['work','adj','谨慎','jǐnshèn','รอบคอบระมัดระวัง','ropkhop ramatrawang','personquality'],
    ['work','adj','积极','jījí','กระตือรือร้น','kratuerueron','personquality'],
    ['work','adj','消极','xiāojí','ขาดความกระตือรือร้น','khat khwam kratuerueron','personquality'],
    ['work','adj','合理','hélǐ','สมเหตุสมผล','somhet somphon','quality'],
    ['work','adj','不合理','bù hélǐ','ไม่สมเหตุสมผล','mai somhet somphon','quality'],
    ['work','adj','可接受','kě jiēshòu','ยอมรับได้','yomrap dai','quality'],
    ['work','adj','不可接受','bù kě jiēshòu','ยอมรับไม่ได้','yomrap mai dai','quality'],
    ['work','adj','有帮助','yǒu bāngzhù','เป็นประโยชน์','pen prayot','quality'],
    ['work','adj','有价值','yǒu jiàzhí','มีคุณค่า','mi khunkha','quality'],
    ['work','adj','有竞争力','yǒu jìngzhēnglì','มีศักยภาพแข่งขัน','mi sakkayaphap khaengkhan','quality'],
    ['work','adj','可持续','kě chíxù','ดำรงต่อเนื่องได้','damrong tonueang dai','quality'],

    // 176–200 · career and hiring
    ['work','n','工作经验','gōngzuò jīngyàn','ประสบการณ์ทำงาน','prasopkan thamngan','career'],
    ['study','n','教育背景','jiàoyù bèijǐng','ประวัติการศึกษา','prawat kansueksa','career'],
    ['work','n','核心能力','héxīn nénglì','สมรรถนะหลัก','samatthana lak','career'],
    ['work','n','职业目标','zhíyè mùbiāo','เป้าหมายอาชีพ','paomai achip','career'],
    ['work','n','期望薪资','qīwàng xīnzī','เงินเดือนที่คาดหวัง','ngoen duean thi khatwang','career'],
    ['work','n','工作地点','gōngzuò dìdiǎn','สถานที่ทำงาน','sathanthi thamngan','career'],
    ['time','n','到岗时间','dàogǎng shíjiān','วันที่พร้อมเริ่มงาน','wanthi phrom roem ngan','career'],
    ['work','n','全职','quánzhí','งานประจำเต็มเวลา','ngan pracham tem wela','career'],
    ['work','n','兼职','jiānzhí','งานนอกเวลา','ngan nok wela','career'],
    ['work','n','自由职业','zìyóu zhíyè','งานอิสระ','ngan itsara','career'],
    ['work','n','晋升','jìnshēng','การเลื่อนตำแหน่ง','kan luean tamnaeng','career'],
    ['work','n','调职','diàozhí','การย้ายตำแหน่ง','kan yai tamnaeng','career'],
    ['work','n','辞职','cízhí','การลาออก','kan la ok','career'],
    ['work','n','解雇','jiěgù','การเลิกจ้าง','kan loek chang','career'],
    ['work','n','绩效','jìxiào','ผลการปฏิบัติงาน','phon kan patibat ngan','career'],
    ['work','n','考核','kǎohé','การประเมินผลงาน','kan pramoen phonngan','career'],
    ['work','n','试岗','shìgǎng','การทดลองปฏิบัติงาน','kan thotlong patibat ngan','career'],
    ['work','n','岗位','gǎngwèi','ตำแหน่งงาน','tamnaeng ngan','career'],
    ['work','n','职位描述','zhíwèi miáoshù','รายละเอียดตำแหน่งงาน','ra-iat tamnaeng ngan','career'],
    ['work','n','工作职责','gōngzuò zhízé','ขอบข่ายหน้าที่งาน','khopkhai nathi ngan','career'],
    ['culture','n','企业文化','qǐyè wénhuà','วัฒนธรรมองค์กร','watthanatham ongkon','career'],
    ['work','n','发展空间','fāzhǎn kōngjiān','โอกาสเติบโตในงาน','okat toepto nai ngan','career'],
    ['work','n','个人成长','gèrén chéngzhǎng','การเติบโตส่วนบุคคล','kan toepto suan bukkhon','career'],
    ['work','n','工作平衡','gōngzuò pínghéng','สมดุลด้านการทำงาน','somdun dan kan thamngan','career'],
    ['work','n','职业规划','zhíyè guīhuà','แผนอาชีพระยะยาว','phaen achip raya yao','career'],

    // 201–225 · polite workplace phrases
    ['work','phrase','烦请确认','fán qǐng quèrèn','รบกวนช่วยยืนยัน','ropkuan chuai yuenyan','say','“烦请”较正式，多用于书面商务沟通。','烦请 ค่อนข้างเป็นทางการ ใช้บ่อยในข้อความธุรกิจ'],
    ['work','phrase','请您过目','qǐng nín guòmù','กรุณาช่วยตรวจดู','karuna chuai truat du','say'],
    ['work','phrase','供您参考','gōng nín cānkǎo','ส่งไว้เพื่อประกอบการพิจารณา','song wai phuea prakop kan phicharana','say'],
    ['work','phrase','收到请回复','shōudào qǐng huífù','เมื่อได้รับแล้วกรุณาตอบกลับ','muea dai rap laeo karuna top klap','say'],
    ['work','phrase','给您添麻烦了','gěi nín tiān máfan le','ต้องขออภัยที่รบกวน','tong kho aphai thi ropkuan','say'],
    ['work','phrase','感谢您的理解','gǎnxiè nín de lǐjiě','ขอบคุณที่เข้าใจ','khopkhun thi khaochai','say'],
    ['work','phrase','感谢您的配合','gǎnxiè nín de pèihé','ขอบคุณสำหรับความร่วมมือ','khopkhun samrap khwam ruammue','say'],
    ['work','phrase','抱歉让您久等了','bàoqiàn ràng nín jiǔ děng le','ขออภัยที่ให้รอนาน','kho aphai thi hai ro nan','say'],
    ['work','phrase','如有问题请联系我','rú yǒu wèntí qǐng liánxì wǒ','หากมีข้อสงสัยกรุณาติดต่อฉัน','hak mi kho songsai karuna titto chan','say'],
    ['work','phrase','我会尽快处理','wǒ huì jǐnkuài chǔlǐ','ฉันจะดำเนินการโดยเร็ว','chan cha damnoenkan doi reo','say'],
    ['work','phrase','我马上核实','wǒ mǎshàng héshí','ฉันจะตรวจยืนยันทันที','chan cha truat yuenyan thanthi','say'],
    ['work','phrase','我再确认一下','wǒ zài quèrèn yíxià','ขอฉันยืนยันอีกครั้ง','kho chan yuenyan ik khrang','say'],
    ['work','phrase','方便的时候请回复','fāngbiàn de shíhou qǐng huífù','สะดวกเมื่อไรกรุณาตอบกลับ','saduak muearai karuna top klap','say'],
    ['work','phrase','请告诉我您的想法','qǐng gàosu wǒ nín de xiǎngfǎ','กรุณาบอกความคิดของคุณ','karuna bok khwam khit khong khun','say'],
    ['work','phrase','我们再商量一下','wǒmen zài shāngliang yíxià','เรามาปรึกษากันอีกครั้ง','rao ma prueksa kan ik khrang','say'],
    ['work','phrase','这件事由我负责','zhè jiàn shì yóu wǒ fùzé','เรื่องนี้ฉันเป็นผู้ดูแล','rueang ni chan pen phudulae','say'],
    ['work','phrase','我需要一点时间','wǒ xūyào yìdiǎn shíjiān','ฉันขอเวลาเล็กน้อย','chan kho wela lek noi','say'],
    ['time','phrase','今天之内给您答复','jīntiān zhī nèi gěi nín dáfù','จะตอบกลับภายในวันนี้','cha top klap phainai wan ni','say'],
    ['time','phrase','能否提前一天','néngfǒu tíqián yì tiān','เลื่อนให้เร็วขึ้นหนึ่งวันได้ไหม','luean hai reo khuen nueng wan dai mai','say'],
    ['time','phrase','时间需要调整','shíjiān xūyào tiáozhěng','จำเป็นต้องปรับเวลา','champen tong prap wela','say'],
    ['work','phrase','这个方案可以接受',"zhège fāng'àn kěyǐ jiēshòu",'แนวทางนี้ยอมรับได้','naeo thang ni yomrap dai','say'],
    ['work','phrase','这个条件需要考虑','zhège tiáojiàn xūyào kǎolǜ','เงื่อนไขนี้ต้องพิจารณา','ngueankhai ni tong phicharana','say'],
    ['work','phrase','目前没有异议','mùqián méiyǒu yìyì','ขณะนี้ไม่มีข้อคัดค้าน','khana ni maimi kho khatkhan','say'],
    ['work','phrase','我们保持沟通','wǒmen bǎochí gōutōng','เราจะสื่อสารกันต่อเนื่อง','rao cha suesan kan tonueang','say'],
    ['work','phrase','期待您的回复','qīdài nín de huífù','รอรับคำตอบจากคุณ','ro rap khamtop chak khun','say'],

    // 226–250 · everyday workplace technology
    ['work','v','登录','dēnglù','เข้าสู่ระบบ','khao su rabop','techdo'],
    ['work','v','退出登录','tuìchū dēnglù','ออกจากระบบ','ok chak rabop','techdo'],
    ['work','n','账号','zhànghào','บัญชีผู้ใช้','banchi phuchai','techcheck'],
    ['work','n','验证码','yànzhèngmǎ','รหัสยืนยัน','rahat yuenyan','techcheck'],
    ['work','phrase','权限申请','quánxiàn shēnqǐng','คำขอสิทธิ์เข้าถึง','khamkho sit khaothueng','system'],
    ['work','n','云端','yúnduān','ระบบคลาวด์','rabop khlao','techcheck'],
    ['work','n','数据库','shùjùkù','ฐานข้อมูล','than khomun','techcheck'],
    ['work','n','服务器','fúwùqì','เซิร์ฟเวอร์','soefoe','techcheck'],
    ['work','n','软件','ruǎnjiàn','ซอฟต์แวร์','sopwae','techcheck'],
    ['work','n','硬件','yìngjiàn','ฮาร์ดแวร์','hatwae','techcheck'],
    ['work','n','故障','gùzhàng','ความขัดข้อง','khwam khatkhong','techissue'],
    ['work','n','错误','cuòwù','ข้อผิดพลาด','kho phitphlat','techissue'],
    ['work','v','备份','bèifèn','สำรองข้อมูล','samrong khomun','techdo'],
    ['work','v','恢复','huīfù','กู้คืน','ku khuen','techdo'],
    ['work','v','安装','ānzhuāng','ติดตั้ง','tittang','techdo'],
    ['work','v','升级','shēngjí','อัปเกรด','ap kret','techdo'],
    ['work','v','下载','xiàzài','ดาวน์โหลด','daolot','techdo'],
    ['work','v','上传','shàngchuán','อัปโหลด','aplot','techdo'],
    ['work','n','链接','liànjiē','ลิงก์','ling','techcheck'],
    ['work','n','页面','yèmiàn','หน้าเว็บ','na wep','techcheck'],
    ['work','n','设置','shèzhì','การตั้งค่า','kan tangkha','techcheck'],
    ['work','v','搜索','sōusuǒ','ค้นหา','khonha','techdo'],
    ['work','v','筛选','shāixuǎn','กรองรายการ','krong raikan','techdo'],
    ['work','v','排序','páixù','เรียงลำดับ','riang lamdap','techdo'],
    ['work','v','保存','bǎocún','บันทึกไว้','banthuek wai','techdo'],
  ];

  const L6 = [
    // 001–025 · society and public institutions
    ['social','n','社会','shèhuì','สังคม','sangkhom','abstract'],
    ['social','n','政府','zhèngfǔ','รัฐบาล','ratthaban','public'],
    ['people','n','公民','gōngmín','พลเมือง','phonlamueang','society'],
    ['social','n','人口','rénkǒu','ประชากร','prachakon','trend'],
    ['social','n','城市化','chéngshìhuà','ความเป็นเมือง','khwam pen mueang','trend'],
    ['social','n','社区发展','shèqū fāzhǎn','การพัฒนาชุมชน','kan phatthana chumchon','public'],
    ['social','n','公共服务','gōnggòng fúwù','บริการสาธารณะ','borikan satharana','important'],
    ['study','n','教育制度','jiàoyù zhìdù','ระบบการศึกษา','rabop kansueksa','society'],
    ['health','n','医疗制度','yīliáo zhìdù','ระบบสาธารณสุข','rabop satharanasuk','society'],
    ['social','n','法律','fǎlǜ','กฎหมาย','kotmai','important'],
    ['social','n','政策','zhèngcè','นโยบาย','nayobai','affect'],
    ['social','n','制度','zhìdù','ระบบ','rabop','abstract'],
    ['social','n','规定','guīdìng','ข้อบังคับ','kho bangkhap','important'],
    ['social','n','权利','quánlì','สิทธิ','sitthi','important'],
    ['social','n','义务','yìwù','หน้าที่พลเมือง','nathi phonlamueang','important'],
    ['social','n','平等','píngděng','ความเท่าเทียม','khwam thaothiam','society'],
    ['social','n','公正','gōngzhèng','ความยุติธรรม','khwam yuttitham','society'],
    ['social','n','自由','zìyóu','เสรีภาพ','seriphap','society'],
    ['social','n','安全感','ānquángǎn','ความรู้สึกมั่นคงปลอดภัย','khwam rusuek mankhong plotphai','society'],
    ['social','n','社会责任','shèhuì zérèn','ความรับผิดชอบต่อสังคม','khwam rapphitchop to sangkhom','important'],
    ['social','n','公共利益','gōnggòng lìyì','ประโยชน์ส่วนรวม','prayot suanruam','important'],
    ['social','n','私人利益','sīrén lìyì','ผลประโยชน์ส่วนบุคคล','phonprayot suan bukkhon','consider'],
    ['social','n','民意','mínyì','ความคิดเห็นของประชาชน','khwam khithen khong prachachon','society'],
    ['social','n','选举','xuǎnjǔ','การเลือกตั้ง','kan lueaktang','society'],
    ['social','n','经济','jīngjì','เศรษฐกิจ','setthakit','trend'],

    // 026–050 · culture and identity
    ['culture','n','身份','shēnfèn','อัตลักษณ์บุคคล','attalak bukkhon','culture'],
    ['culture','n','认同','rèntóng','ความรู้สึกร่วมเป็นส่วนหนึ่ง','khwam rusuek ruam pen suan nueng','culture'],
    ['culture','n','价值观','jiàzhíguān','ค่านิยม','khaniyom','culture'],
    ['culture','n','信仰','xìnyǎng','ความเชื่อศรัทธา','khwam chuea sattha','culture'],
    ['culture','n','宗教','zōngjiào','ศาสนา','satsana','culture'],
    ['culture','n','语言','yǔyán','ภาษา','phasa','culture'],
    ['culture','n','方言','fāngyán','ภาษาถิ่น','phasa thin','culture'],
    ['culture','n','历史','lìshǐ','ประวัติศาสตร์','prawattisat','culture'],
    ['culture','n','记忆','jìyì','ความทรงจำ','khwam songcham','culture'],
    ['culture','n','传统文化','chuántǒng wénhuà','วัฒนธรรมดั้งเดิม','watthanatham dangdoem','culture'],
    ['culture','n','现代文化','xiàndài wénhuà','วัฒนธรรมสมัยใหม่','watthanatham samai mai','culture'],
    ['culture','n','流行文化','liúxíng wénhuà','วัฒนธรรมสมัยนิยม','watthanatham samainiyom','culture'],
    ['culture','n','生活方式','shēnghuó fāngshì','วิถีชีวิต','withi chiwit','culture'],
    ['culture','n','礼仪','lǐyí','ธรรมเนียมมารยาท','thamnian marayat','culture'],
    ['culture','n','审美','shěnměi','รสนิยมความงาม','rotniyom khwam ngam','culture'],
    ['culture','n','艺术','yìshù','ศิลปะ','sinlapa','culture'],
    ['culture','n','音乐','yīnyuè','ดนตรี','dontri','culture'],
    ['culture','n','电影','diànyǐng','ภาพยนตร์','phapphayon','culture'],
    ['culture','n','文学','wénxué','วรรณกรรม','wannakam','culture'],
    ['culture','n','媒体','méitǐ','สื่อมวลชน','suemuan chon','culture'],
    ['culture','n','新闻','xīnwén','ข่าวสาร','khaosan','culture'],
    ['culture','n','广告','guǎnggào','โฆษณา','khosana','culture'],
    ['culture','n','网络文化','wǎngluò wénhuà','วัฒนธรรมออนไลน์','watthanatham onlai','culture'],
    ['culture','n','代际差异','dàijì chāyì','ความแตกต่างระหว่างวัย','khwam taektang rawang wai','culture'],
    ['culture','n','多元文化','duōyuán wénhuà','พหุวัฒนธรรม','phahu watthanatham','culture'],

    // 051–075 · economy and livelihoods
    ['social','n','就业','jiùyè','การมีงานทำ','kan mi ngan tham','society'],
    ['social','n','失业','shīyè','การว่างงาน','kan wangngan','society'],
    ['social','n','收入差距','shōurù chājù','ความเหลื่อมล้ำด้านรายได้','khwam lueamlam dan raidai','society'],
    ['daily','n','生活成本','shēnghuó chéngběn','ค่าครองชีพ','kha khrongchip','society'],
    ['shopping','n','消费','xiāofèi','การบริโภค','kan boriphok','trend'],
    ['shopping','n','储蓄','chǔxù','การออม','kan om','important'],
    ['shopping','n','投资','tóuzī','การลงทุน','kan longthun','consider'],
    ['daily','n','房价','fángjià','ราคาที่อยู่อาศัย','rakha thi yu asai','trend'],
    ['shopping','n','物价','wùjià','ราคาสินค้าทั่วไป','rakha sinkha thuapai','trend'],
    ['social','n','税收','shuìshōu','รายได้จากภาษี','raidai chak phasi','society'],
    ['social','n','贸易','màoyì','การค้าระหว่างประเทศ','kan kha rawang prathet','trend'],
    ['social','n','工业','gōngyè','ภาคอุตสาหกรรม','phak utsahakam','trend'],
    ['social','n','农业','nóngyè','ภาคเกษตรกรรม','phak kasettakam','trend'],
    ['travel','n','旅游业','lǚyóuyè','อุตสาหกรรมท่องเที่ยว','utsahakam thongthiao','trend'],
    ['work','n','科技产业','kējì chǎnyè','อุตสาหกรรมเทคโนโลยี','utsahakam theknoloyi','trend'],
    ['work','n','创业','chuàngyè','การเริ่มธุรกิจ','kan roem thurakit','society'],
    ['work','n','中小企业','zhōngxiǎo qǐyè','วิสาหกิจขนาดกลางและเล็ก','wisahakit khanat klang lae lek','society'],
    ['people','n','劳动力','láodònglì','กำลังแรงงาน','kamlang raengngan','trend'],
    ['study','n','技能','jìnéng','ทักษะอาชีพ','thaksa achip','important'],
    ['work','n','生产力','shēngchǎnlì','ผลิตภาพ','phalittaphap','trend'],
    ['social','n','经济增长','jīngjì zēngzhǎng','การเติบโตทางเศรษฐกิจ','kan toepto thang setthakit','trend'],
    ['social','n','经济衰退','jīngjì shuāituì','ภาวะเศรษฐกิจถดถอย','phawa setthakit thotthoi','trend'],
    ['social','n','贫困','pínkùn','ความยากจน','khwam yakchon','society'],
    ['social','n','财富','cáifù','ความมั่งคั่ง','khwam mangkhang','society'],
    ['social','n','社会保障','shèhuì bǎozhàng','หลักประกันทางสังคม','lak prakan thang sangkhom','important'],

    // 076–100 · environment and resilience
    ['social','n','气候变化','qìhòu biànhuà','การเปลี่ยนแปลงสภาพภูมิอากาศ','kan plianplaeng saphap phumiakat','public'],
    ['social','n','全球变暖','quánqiú biànnuǎn','ภาวะโลกร้อน','phawa lok ron','public'],
    ['social','n','污染','wūrǎn','มลพิษ','monlaphit','public'],
    ['health','n','空气质量','kōngqì zhìliàng','คุณภาพอากาศ','khunnaphap akat','public'],
    ['social','n','水资源','shuǐ zīyuán','ทรัพยากรน้ำ','sapphayakon nam','public'],
    ['social','n','能源','néngyuán','พลังงาน','phalangngan','public'],
    ['social','n','可再生能源','kě zàishēng néngyuán','พลังงานหมุนเวียน','phalangngan munwian','public'],
    ['social','n','塑料垃圾','sùliào lājī','ขยะพลาสติก','khaya phlatsatik','public'],
    ['social','n','回收利用','huíshōu lìyòng','การนำกลับมาใช้ใหม่','kan nam klap ma chai mai','public'],
    ['social','phrase','节约能源','jiéyuē néngyuán','ประหยัดพลังงาน','prayat phalangngan','say'],
    ['social','n','生态','shēngtài','ระบบนิเวศ','rabop niwet','public'],
    ['social','n','生物多样性','shēngwù duōyàngxìng','ความหลากหลายทางชีวภาพ','khwam laklai thang chiwaphap','public'],
    ['social','n','森林','sēnlín','ผืนป่า','phuen pa','public'],
    ['social','n','海洋','hǎiyáng','มหาสมุทร','mahasamut','public'],
    ['emergency','n','自然灾害','zìrán zāihài','ภัยธรรมชาติ','phai thammachat','public'],
    ['emergency','n','洪水','hóngshuǐ','อุทกภัย','uthokkaphai','public'],
    ['emergency','n','干旱','gānhàn','ภัยแล้ง','phai laeng','public'],
    ['emergency','n','地震','dìzhèn','แผ่นดินไหว','phaendin wai','public'],
    ['emergency','n','防灾','fángzāi','การป้องกันภัยพิบัติ','kan pongkan phai phibat','important'],
    ['social','n','碳排放','tàn páifàng','การปล่อยคาร์บอน','kan ploi khabon','public'],
    ['daily','n','绿色生活','lǜsè shēnghuó','วิถีชีวิตเป็นมิตรต่อสิ่งแวดล้อม','withi chiwit pen mit to singwaetlom','culture'],
    ['social','n','环境保护','huánjìng bǎohù','การอนุรักษ์สิ่งแวดล้อม','kan anurak singwaetlom','public'],
    ['travel','n','公共交通','gōnggòng jiāotōng','ระบบขนส่งสาธารณะ','rabop khonsong satharana','public'],
    ['social','n','城市规划','chéngshì guīhuà','การวางผังเมือง','kan wang phang mueang','public'],
    ['social','n','可持续发展','kě chíxù fāzhǎn','การพัฒนาอย่างยั่งยืน','kan phatthana yang yangyuen','public'],

    // 101–125 · digital society
    ['work','n','人工智能','réngōng zhìnéng','ปัญญาประดิษฐ์','panya pradit','culture'],
    ['work','n','自动化','zìdònghuà','ระบบอัตโนมัติ','rabop attanomat','trend'],
    ['work','n','数字化','shùzìhuà','การเปลี่ยนผ่านสู่ดิจิทัล','kan plian phan su dichithan','trend'],
    ['social','n','社交媒体','shèjiāo méitǐ','สื่อสังคมออนไลน์','sue sangkhom onlai','culture'],
    ['social','n','信息来源','xìnxī láiyuán','แหล่งข้อมูล','laeng khomun','important'],
    ['social','n','假新闻','jiǎ xīnwén','ข่าวปลอม','khao plom','public'],
    ['emergency','n','网络诈骗','wǎngluò zhàpiàn','การฉ้อโกงออนไลน์','kan choko ng onlai','public'],
    ['social','n','数据隐私','shùjù yǐnsī','ความเป็นส่วนตัวของข้อมูล','khwam pen suantua khong khomun','important'],
    ['social','n','信息安全','xìnxī ānquán','ความมั่นคงปลอดภัยสารสนเทศ','khwam mankhong plotphai sarasonthet','important'],
    ['shopping','n','数字支付','shùzì zhīfù','การชำระเงินดิจิทัล','kan chamra ngoen dichithan','trend'],
    ['study','n','远程学习','yuǎnchéng xuéxí','การเรียนทางไกล','kan rian thang klai','trend'],
    ['daily','n','在线服务','zàixiàn fúwù','บริการออนไลน์','borikan onlai','trend'],
    ['work','n','技术进步','jìshù jìnbù','ความก้าวหน้าทางเทคโนโลยี','khwam kaona thang theknoloyi','trend'],
    ['social','n','数字鸿沟','shùzì hónggōu','ความเหลื่อมล้ำทางดิจิทัล','khwam lueamlam thang dichithan','society'],
    ['health','n','屏幕时间','píngmù shíjiān','เวลาหน้าจอ','wela nacho','public'],
    ['health','n','网络成瘾','wǎngluò chéngyǐn','การเสพติดอินเทอร์เน็ต','kan seaptit inthanoet','public'],
    ['work','n','算法','suànfǎ','อัลกอริทึม','ankorisuem','abstract'],
    ['work','n','平台','píngtái','แพลตฟอร์ม','phlaetfom','abstract'],
    ['culture','n','内容','nèiróng','เนื้อหา','nueaha','abstract'],
    ['culture','n','版权','bǎnquán','ลิขสิทธิ์','likkhasit','important'],
    ['people','n','创作者','chuàngzuòzhě','ผู้สร้างสรรค์เนื้อหา','phusangsan nueaha','person'],
    ['social','n','影响力','yǐngxiǎnglì','อิทธิพลต่อสังคม','itthiphon to sangkhom','affect'],
    ['social','n','线上社区','xiànshàng shèqū','ชุมชนบนอินเทอร์เน็ต','chumchon bon inthanoet','culture'],
    ['social','n','虚拟空间','xūnǐ kōngjiān','พื้นที่เสมือน','phuenthi samuean','culture'],
    ['culture','n','科技伦理','kējì lúnlǐ','จริยธรรมเทคโนโลยี','chariyatham theknoloyi','culture'],

    // 126–150 · families, groups, and social relations
    ['social','n','家庭结构','jiātíng jiégòu','โครงสร้างครอบครัว','khrongsang khropkhrua','society'],
    ['social','n','婚姻','hūnyīn','การสมรส','kan somrot','society'],
    ['social','n','离婚','líhūn','การหย่าร้าง','kan yarang','society'],
    ['social','n','亲子关系','qīnzǐ guānxi','ความสัมพันธ์พ่อแม่ลูก','khwam samphan pho mae luk','society'],
    ['social','n','性别角色','xìngbié juésè','บทบาททางเพศ','botbat thang phet','society'],
    ['social','n','老龄化','lǎolínghuà','การเข้าสู่สังคมสูงวัย','kan khao su sangkhom sungwai','trend'],
    ['people','n','青年','qīngnián','คนหนุ่มสาว','khon num sao','youthGroup'],
    ['people','n','儿童','értóng','เด็ก','dek','person'],
    ['people','n','老年人','lǎoniánrén','ผู้สูงอายุ','phusung ayu','person'],
    ['people','n','残障人士','cánzhàng rénshì','ผู้มีความพิการ','phu mi khwam phikan','person'],
    ['people','n','外来人口','wàilái rénkǒu','ประชากรย้ายถิ่น','prachakon yaithin','society'],
    ['people','n','游客','yóukè','นักท่องเที่ยว','nak thongthiao','person'],
    ['people','n','志愿者','zhìyuànzhě','อาสาสมัคร','asamak','person'],
    ['social','n','非营利组织','fēi yínglì zǔzhī','องค์กรไม่แสวงหากำไร','ongkon mai sawaeng ha kamrai','society'],
    ['social','n','邻里关系','línlǐ guānxi','ความสัมพันธ์ในละแวกบ้าน','khwam samphan nai lawaek ban','society'],
    ['social','n','社会支持','shèhuì zhīchí','การเกื้อหนุนทางสังคม','kan kueanun thang sangkhom','important'],
    ['health','n','心理健康','xīnlǐ jiànkāng','สุขภาพจิต','sukkhaphap chit','public'],
    ['health','n','孤独','gūdú','ความโดดเดี่ยว','khwam dotdiao','society'],
    ['social','n','归属感','guīshǔgǎn','ความรู้สึกเป็นส่วนหนึ่ง','khwam rusuek pen suan nueng','society'],
    ['social','n','同理心','tónglǐxīn','ความเข้าอกเข้าใจ','khwam khao-ok khaochai','important'],
    ['social','n','偏见','piānjiàn','อคติ','akhati','society'],
    ['social','n','歧视','qíshì','การเลือกปฏิบัติ','kan lueak patibat','society'],
    ['social','n','包容','bāoróng','การยอมรับความแตกต่าง','kan yomrap khwam taektang','important'],
    ['social','n','冲突','chōngtū','ความขัดแย้ง','khwam khatyaeng','society'],
    ['social','n','和解','héjiě','การปรองดอง','kan prongdong','society'],

    // 151–175 · abstract ideas used in real discussion
    ['social','n','事实','shìshí','ข้อเท็จจริง','kho thetching','abstract'],
    ['social','n','真相','zhēnxiàng','ความจริงเบื้องหลัง','khwam ching bueanglang','abstract'],
    ['social','n','信息','xìnxī','สารสนเทศ','sarasonthet','abstract'],
    ['study','n','知识','zhīshi','ความรู้','khwam ru','abstract'],
    ['work','n','经验','jīngyàn','ประสบการณ์','prasopkan','abstract'],
    ['social','n','理解','lǐjiě','ความเข้าใจ','khwam khaochai','abstract'],
    ['social','n','意义','yìyì','ความหมายเชิงคุณค่า','khwam mai choeng khunkha','abstract'],
    ['social','n','目的','mùdì','จุดประสงค์','chutprasong','abstract'],
    ['social','n','动机','dòngjī','แรงจูงใจ','raeng chungchai','abstract'],
    ['work','n','决策','juécè','การตัดสินเชิงนโยบาย','kan tatsin choeng nayobai','abstract'],
    ['social','n','变化','biànhuà','การเปลี่ยนแปลง','kan plianplaeng','abstract'],
    ['social','n','发展','fāzhǎn','พัฒนาการ','phatthanakan','abstract'],
    ['social','n','过程','guòchéng','กระบวนการ','krabuan kan','abstract'],
    ['social','n','结构','jiégòu','โครงสร้าง','khrongsang','abstract'],
    ['social','n','模式','móshì','รูปแบบ','rupbaep','abstract'],
    ['social','n','现象','xiànxiàng','ปรากฏการณ์','prakatkan','abstract'],
    ['social','n','背景','bèijǐng','ภูมิหลัง','phumlang','abstract'],
    ['social','n','语境','yǔjìng','บริบทการสื่อสาร','boribot kan suesan','abstract','“语境”是语言出现的上下文和场合。','语境 คือบริบทและสถานการณ์ที่ภาษาเกิดขึ้น'],
    ['study','n','假设','jiǎshè','สมมติฐาน','sommutithan','abstract'],
    ['study','n','证据','zhèngjù','หลักฐาน','lakthan','important'],
    ['study','n','结论','jiélùn','ข้อสรุป','kho sarup','abstract'],
    ['study','n','逻辑','luójí','ตรรกะ','takka','abstract'],
    ['study','n','相关性','xiāngguānxìng','ความเกี่ยวข้อง','khwam kiaokhong','abstract'],
    ['social','n','不确定性','bù quèdìngxìng','ความไม่แน่นอน','khwam mai naenon','abstract'],
    ['social','n','复杂性','fùzáxìng','ความซับซ้อน','khwam sapsorn','abstract'],

    // 176–200 · nuanced adjectives
    ['study','adj','客观','kèguān','เป็นกลางตามข้อเท็จจริง','penklang tam kho thetching','view'],
    ['study','adj','主观','zhǔguān','ขึ้นกับความเห็นส่วนบุคคล','khuen kap khwam hen suan bukkhon','view'],
    ['study','adj','具体','jùtǐ','เป็นรูปธรรม','pen ruptham','view'],
    ['study','adj','抽象','chōuxiàng','เป็นนามธรรม','pen namtham','view'],
    ['social','adj','普遍','pǔbiàn','พบได้ทั่วไป','phop dai thuapai','view'],
    ['social','adj','特殊','tèshū','มีลักษณะเฉพาะ','mi laksana cho pho','view'],
    ['study','adj','相对','xiāngduì','เป็นสัมพัทธ์','pen samphat','view'],
    ['study','adj','绝对','juéduì','เด็ดขาดโดยไม่มีเงื่อนไข','detkhat doi maimi ngueankhai','view'],
    ['social','adj','真实','zhēnshí','ตรงกับความเป็นจริง','trong kap khwam pen ching','view'],
    ['social','adj','虚假','xūjiǎ','เป็นเท็จ','pen thet','view'],
    ['social','adj','公开','gōngkāi','เปิดเผยต่อสาธารณะ','poetphoei to satharana','view'],
    ['social','adj','私密','sīmì','เป็นเรื่องส่วนบุคคล','pen rueang suan bukkhon','view'],
    ['social','adj','独立','dúlì','เป็นอิสระ','pen itsara','view'],
    ['social','adj','共同','gòngtóng','มีร่วมกัน','mi ruam kan','view'],
    ['social','adj','个人','gèrén','เฉพาะบุคคล','cho pho bukkhon','view'],
    ['social','adj','集体','jítǐ','เป็นส่วนรวม','pen suanruam','view'],
    ['social','adj','多样','duōyàng','หลากหลาย','laklai','view'],
    ['social','adj','一致','yízhì','สอดคล้องกัน','sotkhlong kan','view'],
    ['social','adj','矛盾','máodùn','ขัดแย้งกัน','khatyaeng kan','view'],
    ['social','adj','平衡','pínghéng','สมดุล','somdun','view'],
    ['time','adj','长期','chángqī','เป็นระยะยาว','pen raya yao','view'],
    ['time','adj','短期','duǎnqī','เป็นระยะสั้น','pen raya san','view'],
    ['social','v','直接影响','zhíjiē yǐngxiǎng','ส่งผลโดยตรง','song phon doi trong','directAffect'],
    ['social','adj','潜在','qiánzài','แฝงอยู่','faeng yu','view'],
    ['social','adj','典型','diǎnxíng','เป็นตัวอย่างชัดเจน','pen tuayang chatchen','view'],

    // 201–225 · high-frequency discussion phrases
    ['social','phrase','我不完全同意','wǒ bù wánquán tóngyì','ฉันไม่ได้เห็นด้วยทั้งหมด','chan mai dai hen duai thangmot','say'],
    ['social','phrase','这取决于情况','zhè qǔjué yú qíngkuàng','เรื่องนี้ขึ้นอยู่กับสถานการณ์','rueang ni khuen yu kap sathanakan','say'],
    ['social','phrase','不能一概而论','bù néng yígài ér lùn','เหมารวมทั้งหมดไม่ได้','mao ruam thangmot mai dai','say'],
    ['social','phrase','值得进一步讨论','zhídé jìnyíbù tǎolùn','ควรหารือต่อให้ลึกขึ้น','khuan harue to hai luek khuen','say'],
    ['study','phrase','需要更多证据','xūyào gèng duō zhèngjù','จำเป็นต้องมีหลักฐานเพิ่ม','champen tong mi lakthan phoem','say'],
    ['time','phrase','从长远来看','cóng chángyuǎn lái kàn','หากมองในระยะยาว','hak mong nai raya yao','say'],
    ['social','phrase','从社会角度看','cóng shèhuì jiǎodù kàn','หากมองจากมุมสังคม','hak mong chak mum sangkhom','say'],
    ['social','phrase','关键在于','guānjiàn zài yú','หัวใจสำคัญอยู่ที่','huachai samkhan yu thi','say'],
    ['social','phrase','问题不只如此','wèntí bù zhǐ rúcǐ','ปัญหาไม่ได้มีเพียงเท่านี้','panha mai dai mi phiang thao ni','say'],
    ['social','phrase','这可能带来影响','zhè kěnéng dàilái yǐngxiǎng','สิ่งนี้อาจก่อให้เกิดผลตามมา','sing ni at ko hai koet phon tam ma','say'],
    ['social','phrase','好处和坏处并存','hǎochù hé huàichù bìngcún','มีทั้งข้อดีและข้อเสีย','mi thang kho di lae kho sia','say'],
    ['social','phrase','每个人看法不同','měi ge rén kànfǎ bùtóng','แต่ละคนมีมุมมองต่างกัน','tae la khon mi mum mong tang kan','say'],
    ['culture','phrase','我们应该尊重差异','wǒmen yīnggāi zūnzhòng chāyì','เราควรเคารพความแตกต่าง','rao khuan khaorop khwam taektang','say'],
    ['social','phrase','事实可能更复杂','shìshí kěnéng gèng fùzá','ข้อเท็จจริงอาจซับซ้อนกว่านั้น','kho thetching at sapsorn kwa nan','say'],
    ['social','phrase','暂时没有定论','zànshí méiyǒu dìnglùn','ขณะนี้ยังไม่มีข้อยุติ','khana ni yang maimi kho yuti','say'],
    ['social','phrase','这是一种趋势','zhè shì yì zhǒng qūshì','นี่เป็นแนวโน้มอย่างหนึ่ง','ni pen naewnom yang nueng','say'],
    ['social','phrase','这个现象很常见','zhège xiànxiàng hěn chángjiàn','ปรากฏการณ์นี้พบได้บ่อย','prakatkan ni phop dai boi','say'],
    ['social','phrase','原因不止一个','yuányīn bù zhǐ yí ge','สาเหตุมีมากกว่าหนึ่งอย่าง','sahet mi mak kwa nueng yang','say'],
    ['social','phrase','结果需要观察','jiéguǒ xūyào guānchá','ต้องติดตามผลลัพธ์ต่อไป','tong tittam phonlap to pai','say'],
    ['social','phrase','不能忽视这个问题','bù néng hūshì zhège wèntí','ละเลยปัญหานี้ไม่ได้','laloei panha ni mai dai','say'],
    ['social','phrase','我对此保持开放','wǒ duì cǐ bǎochí kāifàng','ฉันยังเปิดรับเรื่องนี้','chan yang poet rap rueang ni','say'],
    ['social','phrase','我理解你的立场','wǒ lǐjiě nǐ de lìchǎng','ฉันเข้าใจจุดยืนของคุณ','chan khaochai chutyuen khong khun','say'],
    ['social','phrase','让我们看具体例子','ràng wǒmen kàn jùtǐ lìzi','มาดูตัวอย่างที่เป็นรูปธรรมกัน','ma du tuayang thi pen ruptham kan','say'],
    ['social','phrase','需要考虑不同群体','xūyào kǎolǜ bùtóng qúntǐ','ต้องคำนึงถึงคนหลายกลุ่ม','tong khamnueng thueng khon lai klum','say'],
    ['social','phrase','重点是找到平衡','zhòngdiǎn shì zhǎodào pínghéng','สิ่งสำคัญคือหาจุดสมดุล','sing samkhan khue ha chut somdun','say'],

    // 226–250 · civic action and shared life
    ['social','phrase','遵守法律','zūnshǒu fǎlǜ','ปฏิบัติตามกฎหมาย','patibat tam kotmai','say'],
    ['social','phrase','尊重他人','zūnzhòng tārén','ให้เกียรติผู้อื่น','hai kiat phu uen','say'],
    ['social','phrase','保护环境','bǎohù huánjìng','รักษาสิ่งแวดล้อม','raksa singwaetlom','say'],
    ['social','phrase','参与社区','cānyù shèqū','มีส่วนร่วมในชุมชน','mi suanruam nai chumchon','say'],
    ['social','phrase','帮助弱势群体','bāngzhù ruòshì qúntǐ','ช่วยเหลือกลุ่มเปราะบาง','chuailuea klum pro bang','say'],
    ['social','phrase','维护公共秩序','wéihù gōnggòng zhìxù','รักษาความสงบเรียบร้อยสาธารณะ','raksa khwam sangop riaproi satharana','say'],
    ['social','phrase','表达个人意见','biǎodá gèrén yìjiàn','แสดงความเห็นส่วนตัว','sadaeng khwam hen suantua','say'],
    ['culture','phrase','接受文化差异','jiēshòu wénhuà chāyì','ยอมรับความต่างทางวัฒนธรรม','yomrap khwam tang thang watthanatham','say'],
    ['social','phrase','关注社会问题','guānzhù shèhuì wèntí','ใส่ใจปัญหาสังคม','saichai panha sangkhom','say'],
    ['social','phrase','核实信息来源','héshí xìnxī láiyuán','ตรวจสอบแหล่งข่าว','truatsop laeng khao','say'],
    ['study','phrase','独立思考','dúlì sīkǎo','คิดอย่างอิสระ','khit yang itsara','say'],
    ['social','phrase','公开讨论','gōngkāi tǎolùn','อภิปรายอย่างเปิดเผย','aphiprai yang poetphoei','say'],
    ['social','phrase','理性沟通','lǐxìng gōutōng','สื่อสารด้วยเหตุผล','suesan duai hetphon','say'],
    ['social','phrase','和平解决','hépíng jiějué','แก้ไขโดยสันติ','kaekhai doi santi','say'],
    ['social','phrase','承担社会责任','chéngdān shèhuì zérèn','รับผิดชอบต่อส่วนรวม','rapphitchop to suanruam','say'],
    ['social','phrase','保障基本权利','bǎozhàng jīběn quánlì','คุ้มครองสิทธิขั้นพื้นฐาน','khumkhrong sitthi khan phuenthan','say'],
    ['social','phrase','提供公共服务','tígōng gōnggòng fúwù','จัดบริการสาธารณะ','chat borikan satharana','say'],
    ['social','phrase','减少社会差距','jiǎnshǎo shèhuì chājù','ลดความเหลื่อมล้ำทางสังคม','lot khwam lueamlam thang sangkhom','say'],
    ['social','phrase','提高生活质量','tígāo shēnghuó zhìliàng','ยกระดับคุณภาพชีวิต','yok radap khunnaphap chiwit','say'],
    ['study','phrase','推动教育公平','tuīdòng jiàoyù gōngpíng','ส่งเสริมความเป็นธรรมทางการศึกษา','songsoem khwam pen tham thang kansueksa','say'],
    ['culture','phrase','支持本地文化','zhīchí běndì wénhuà','สนับสนุนวัฒนธรรมท้องถิ่น','sanapsanun watthanatham thongthin','say'],
    ['culture','phrase','保存历史记忆','bǎocún lìshǐ jìyì','เก็บรักษาความทรงจำทางประวัติศาสตร์','kep raksa khwam songcham thang prawattisat','say'],
    ['social','phrase','鼓励公民参与','gǔlì gōngmín cānyù','ส่งเสริมการมีส่วนร่วมของพลเมือง','songsoem kan mi suanruam khong phonlamueang','say'],
    ['social','phrase','建立互信','jiànlì hùxìn','สร้างความเชื่อใจกัน','sang khwam chueachai kan','say'],
    ['social','phrase','寻求共同利益','xúnqiú gòngtóng lìyì','แสวงหาประโยชน์ร่วมกัน','sawaeng ha prayot ruam kan','say'],
  ];

  function expand(rows, level) {
    return rows.map((row, index) => {
      const [cat, pos, zh, py, th, ro, pattern, noteZh = '', noteTh = ''] = row;
      if (typeof patterns[pattern] !== 'function') throw new Error(`Unknown example pattern at L${level}-${index + 1}: ${pattern}`);
      const [exZh, exPy, exTh, exRo] = patterns[pattern]({ zh, py, th, ro });
      return { id: `l${level}-${String(index + 1).padStart(3, '0')}`, level, cat, pos, zh, py, th, ro, exZh, exPy, exTh, exRo, noteZh, noteTh };
    });
  }

  window.HUILAISHI_VOCAB_L56 = [...expand(L5, 5), ...expand(L6, 6)];
})();
