// Generated from explicit roster and existing authored lore; old files stay untouched.
export default [
  {
    "id": "tuk-gecko",
    "world": "th",
    "rank": 0,
    "zh": "嘟嘟快递蜥",
    "th": "ตุ๊กแกส่งพัสดุ",
    "sheet": "gecko-actions-v3.png",
    "designSource": "monster-tuk-gecko-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它把一张褪色的路线图藏在帽檐里",
    "traitTh": "ตุ๊กแกส่งพัสดุ",
    "loreZh": "它把一张褪色的路线图藏在帽檐里。每次送信走错路，就在地图背面画下一朵小花。现在整张地图开满了花，它却依然记得答应送到的那个地址。",
    "loreTh": "มันเก็บแผนที่เก่าไว้ในหมวก ทุกครั้งที่ส่งจดหมายผิดทางจะวาดดอกไม้เพิ่มหนึ่งดอก แม้แผนที่จะเต็มไปด้วยดอกไม้ มันก็ยังจำที่อยู่ที่สัญญาว่าจะส่งให้ถึง",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "wok-crab",
    "world": "th",
    "rank": 2,
    "zh": "锅盔掌勺蟹",
    "th": "ปูพ่อครัวกระทะ",
    "sheet": "wok-actions-v3.png",
    "designSource": "monster-wok-crab-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "收摊后，它总会留下两碗热饭",
    "traitTh": "ปูพ่อครัวกระทะ",
    "loreZh": "收摊后，它总会留下两碗热饭。城里的人以为它爱找人比试，其实它只想听懂客人要的口味，把那顿迟来的晚饭做好。",
    "loreTh": "หลังปิดร้านมันจะเก็บข้าวร้อนไว้สองชาม คนในเมืองคิดว่ามันชอบท้าสู้ แต่จริง ๆ แค่อยากเข้าใจรสชาติที่ลูกค้าต้องการ",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "ferry-otter",
    "world": "th",
    "rank": 1,
    "zh": "摆渡信獭",
    "th": "นากส่งจดหมาย",
    "sheet": "otter-actions-v3.png",
    "designSource": "monster-ferry-otter-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它曾在河上捡回一本进水的手册，从此总想赶在纸页沉没前划到岸边",
    "traitTh": "นากส่งจดหมาย",
    "loreZh": "它曾在河上捡回一本进水的手册，从此总想赶在纸页沉没前划到岸边。",
    "loreTh": "มันเคยเก็บสมุดเปียกน้ำจากแม่น้ำ ตั้งแต่นั้นก็พยายามพายถึงฝั่งก่อนกระดาษจะจม",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "laundry-frog",
    "world": "th",
    "rank": 0,
    "zh": "泡沫围裙蛙",
    "th": "กบผ้ากันเปื้อน",
    "sheet": "renewed-laundry-frog-v2.png",
    "designSource": "monster-laundry-frog-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它把洗衣店遗落的围裙缝成了披风",
    "traitTh": "กบผ้ากันเปื้อน",
    "loreZh": "它把洗衣店遗落的围裙缝成了披风。每次紧张就吐出泡泡，连自己的破口也一起洗好了。",
    "loreTh": "มันเย็บผ้ากันเปื้อนที่ร้านซักผ้าลืมไว้เป็นผ้าคลุม พอประหม่าก็เป่าฟอง ซักจนรอยขาดของตัวเองกลับมาดี",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "alarm-rooster",
    "world": "th",
    "rank": 0,
    "zh": "报晓闹铃鸡",
    "th": "ไก่นาฬิกาปลุก",
    "sheet": "renewed-alarm-rooster-v2.png",
    "designSource": "monster-alarm-rooster-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它以前负责叫醒早市摊主",
    "traitTh": "ไก่นาฬิกาปลุก",
    "loreZh": "它以前负责叫醒早市摊主。散页让它忘了时间，它只好一直打铃，生怕有人错过早餐。",
    "loreTh": "มันเคยปลุกพ่อค้าตลาดเช้า หน้ากระดาษทำให้ลืมเวลา จึงส่งเสียงตลอดเพราะกลัวใครพลาดอาหารเช้า",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "market-elephant",
    "world": "th",
    "rank": 1,
    "zh": "菜篮护市象",
    "th": "ช้างตะกร้าตลาด",
    "sheet": "renewed-market-elephant-v2.png",
    "designSource": "monster-market-elephant-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它并不是想挡路，只是不愿让大家辛苦买来的菜篮被风吹散",
    "traitTh": "ช้างตะกร้าตลาด",
    "loreZh": "它并不是想挡路，只是不愿让大家辛苦买来的菜篮被风吹散。它把每只篮子都当作一面盾。",
    "loreTh": "มันไม่ได้อยากขวางทาง แค่ไม่อยากให้ตะกร้าผักที่ทุกคนซื้อมาถูกลมพัด จึงใช้ทุกใบเป็นโล่",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "bus-lizard",
    "world": "th",
    "rank": 1,
    "zh": "站牌长尾蜥",
    "th": "กิ้งก่าป้ายรถเมล์",
    "sheet": "renewed-bus-lizard-v2.png",
    "designSource": "monster-bus-lizard-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它从旧巴士的路线图里醒来，尾巴每甩一次就报一个站",
    "traitTh": "กิ้งก่าป้ายรถเมล์",
    "loreZh": "它从旧巴士的路线图里醒来，尾巴每甩一次就报一个站。等它报完，才轮到你回答。",
    "loreTh": "มันตื่นจากแผนที่รถเมล์เก่า สะบัดหางครั้งหนึ่งก็ประกาศหนึ่งป้าย รอมันพูดจบแล้วค่อยตอบ",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "karaoke-myna",
    "world": "th",
    "rank": 2,
    "zh": "返场八哥",
    "th": "นกเอี้ยงร้องเพลง",
    "sheet": "renewed-karaoke-myna-v2.png",
    "designSource": "monster-karaoke-myna-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "它记得校园节所有副歌，却分不清独唱与合唱",
    "traitTh": "นกเอี้ยงร้องเพลง",
    "loreZh": "它记得校园节所有副歌，却分不清独唱与合唱。隔一回合，它就忍不住再接一句。",
    "loreTh": "มันจำท่อนร้องเทศกาลได้หมด แต่แยกไม่ออกว่าร้องเดี่ยวหรือหมู่ ทุกเว้นเทิร์นจึงอดร้องต่อไม่ได้",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "station-macaque",
    "world": "th",
    "rank": 1,
    "zh": "末班信号猕猴",
    "th": "ลิงสัญญาณเที่ยวสุดท้าย",
    "sheet": "renewed-station-macaque-v2.png",
    "designSource": "monster-station-macaque-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它的信号灯永远指着末班车",
    "traitTh": "ลิงสัญญาณเที่ยวสุดท้าย",
    "loreZh": "它的信号灯永远指着末班车。生命过半时，它会更着急；越到这时候，越要稳住节拍。",
    "loreTh": "ไฟสัญญาณของมันชี้ไปเที่ยวสุดท้ายเสมอ พลังต่ำกว่าครึ่งจะยิ่งรีบ ช่วงนั้นยิ่งต้องรักษาจังหวะ",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "thunder-elephant",
    "world": "th",
    "rank": 2,
    "zh": "雷鼓报时象",
    "th": "ช้างกลองบอกเวลา",
    "sheet": "renewed-thunder-elephant-v2.png",
    "designSource": "monster-thunder-elephant-v4.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "雷鼓象的鼓皮来自旧舞台幕布",
    "traitTh": "ช้างกลองบอกเวลา",
    "loreZh": "雷鼓象的鼓皮来自旧舞台幕布。工坊停转后，它靠敲鼓给所有还在干活的小纸怪报时。",
    "loreTh": "หนังกลองมาจากม่านเวทีเก่า หลังโรงงานหยุด มันตีกลองบอกเวลาให้มอนสเตอร์ที่ยังทำงาน",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "backpack-buffalo",
    "world": "th",
    "rank": 1,
    "zh": "守包水牛",
    "th": "ควายเฝ้ากระเป๋า",
    "sheet": "renewed-backpack-buffalo-v2.png",
    "designSource": "monster-backpack-buffalo-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "学生把书包留在渡口后再也没有回来",
    "traitTh": "ควายเฝ้ากระเป๋า",
    "loreZh": "学生把书包留在渡口后再也没有回来。它替主人守着里面那封未寄的信。听到熟悉的问候，它就会把沉重的包轻轻放下。",
    "loreTh": "นักเรียนทิ้งกระเป๋าไว้ที่ท่าเรือแล้วไม่กลับมา มันเฝ้าจดหมายที่ยังไม่ได้ส่ง เมื่อได้ยินคำทักทายที่คุ้นเคยก็จะวางกระเป๋าลง",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "debate-hornbill",
    "world": "th",
    "rank": 2,
    "zh": "书街辩词鸟",
    "th": "นกเงือกนักโต้วาที",
    "sheet": "renewed-debate-hornbill-v2.png",
    "designSource": "monster-debate-hornbill-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "它在书街听了太多讨论，开始把每一句话都当成辩论",
    "traitTh": "นกเงือกนักโต้วาที",
    "loreZh": "它在书街听了太多讨论，开始把每一句话都当成辩论。先听完它的论点，不必急着抢话。",
    "loreTh": "มันฟังการสนทนาในถนนหนังสือมากเกินไป จนมองทุกประโยคเป็นการโต้วาที ฟังเหตุผลให้จบก่อน",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "passport-fox",
    "world": "cn",
    "rank": 0,
    "zh": "通行证信狐",
    "th": "จิ้งจอกบัตรผ่าน",
    "sheet": "renewed-passport-fox-v2.png",
    "designSource": "monster-passport-fox-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它把通行证一张张折成护甲，生怕再有人走丢",
    "traitTh": "จิ้งจอกบัตรผ่าน",
    "loreZh": "它把通行证一张张折成护甲，生怕再有人走丢。先拆开它的纸盾，才能让它重新信任路线。",
    "loreTh": "มันพับเอกสารผ่านทางเป็นเกราะทีละใบ กลัวมีใครหลงอีก ต้องเปิดโล่กระดาษก่อนจึงจะเชื่อเส้นทางอีกครั้ง",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "printer-squid",
    "world": "cn",
    "rank": 1,
    "zh": "卷纸印刷鱿",
    "th": "หมึกเครื่องพิมพ์",
    "sheet": "renewed-printer-squid-v2.png",
    "designSource": "monster-printer-squid-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它的触手藏着打印机的纸带",
    "traitTh": "หมึกเครื่องพิมพ์",
    "loreZh": "它的触手藏着打印机的纸带。每当有人说错一个词，它便想再印一张，直到整个房间都塞满。",
    "loreTh": "หนวดซ่อนแถบกระดาษเครื่องพิมพ์ ทุกครั้งที่ใครพูดผิด มันอยากพิมพ์ใหม่จนเต็มห้อง",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "traffic-crane",
    "world": "cn",
    "rank": 0,
    "zh": "木作指路鹤",
    "th": "นกกระเรียนบอกทาง",
    "sheet": "renewed-traffic-crane-v2.png",
    "designSource": "monster-traffic-crane-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它站在工坊门口指挥运料的小车",
    "traitTh": "นกกระเรียนบอกทาง",
    "loreZh": "它站在工坊门口指挥运料的小车。红绿灯片掉了之后，只能用翅膀代替交通信号。",
    "loreTh": "มันยืนหน้าโรงงานนำรถขนของ เมื่อแผ่นไฟแดงเขียวหลุด จึงใช้ปีกแทนสัญญาณ",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "monitor-rabbit",
    "world": "cn",
    "rank": 0,
    "zh": "便签闪屏兔",
    "th": "กระต่ายจอโน้ต",
    "sheet": "renewed-monitor-rabbit-v2.png",
    "designSource": "monster-monitor-rabbit-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它从一台报废显示器的便签里跳了出来",
    "traitTh": "กระต่ายจอโน้ต",
    "loreZh": "它从一台报废显示器的便签里跳了出来。屏幕越闪，它跳得越快，其实只是想把故障告诉你。",
    "loreTh": "มันกระโดดจากกระดาษโน้ตบนจอเก่า ยิ่งจอกะพริบก็ยิ่งกระโดดเร็ว แค่พยายามบอกว่ามีปัญหา",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "seal-panda",
    "world": "cn",
    "rank": 1,
    "zh": "藏印熊猫",
    "th": "แพนด้าตรากระดาษ",
    "sheet": "renewed-seal-panda-v2.png",
    "designSource": "monster-seal-panda-elite-v103.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它把大家的优秀作业背在身上，想把每一页都保存完好",
    "traitTh": "แพนด้าตรากระดาษ",
    "loreZh": "它把大家的优秀作业背在身上，想把每一页都保存完好。纸印叠起来，成了沉甸甸的护甲。",
    "loreTh": "มันแบกผลงานดี ๆ ของทุกคนไว้ อยากเก็บทุกหน้าให้สมบูรณ์ ตรากระดาษซ้อนกันกลายเป็นเกราะหนัก",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "rumor-moth",
    "world": "cn",
    "rank": 0,
    "zh": "流言墨蛾",
    "th": "ผีเสื้อข่าวลือ",
    "sheet": "renewed-rumor-moth-v2.png",
    "designSource": "monster-rumor-moth-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "echo",
    "traitZh": "它爱追逐书页上闪亮的句子，却常常漏掉前后文",
    "traitTh": "ผีเสื้อข่าวลือ",
    "loreZh": "它爱追逐书页上闪亮的句子，却常常漏掉前后文。翅膀上每一个墨点，都是被传错的消息。",
    "loreTh": "มันตามประโยคที่สะดุดตา แต่ชอบลืมบริบท จุดหมึกบนปีกคือข่าวที่ส่งต่อผิด",
    "tellZh": "侧耳听完，再向前试探",
    "tellTh": "เอียงหูฟังแล้วก้าวเข้ามา",
    "counterZh": "连续答对三次，挡住下一次失误",
    "counterTh": "ตอบถูกสามครั้งติดเพื่อกันพลาดครั้งถัดไป"
  },
  {
    "id": "logic-pangolin",
    "world": "cn",
    "rank": 1,
    "zh": "书签穿山甲",
    "th": "ตัวนิ่มที่คั่นหนังสือ",
    "sheet": "pangolin-actions-v3.png",
    "designSource": "monster-logic-pangolin-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它把散落的论证卡片按顺序叠成鳞片",
    "traitTh": "ตัวนิ่มที่คั่นหนังสือ",
    "loreZh": "它把散落的论证卡片按顺序叠成鳞片。顺序一乱就缩成一团，需要你用稳定的回答帮它理清。",
    "loreTh": "มันเรียงบัตรเหตุผลเป็นเกล็ด พอลำดับสับสนก็ม้วนตัว ต้องใช้คำตอบที่มั่นคงช่วยจัดให้ชัด",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "ink-peacock",
    "world": "cn",
    "rank": 2,
    "zh": "未言墨孔雀",
    "th": "นกยูงหมึก",
    "sheet": "renewed-ink-peacock-v2.png",
    "designSource": "monster-ink-peacock-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "它的尾羽记录着书街所有被划掉的草稿",
    "traitTh": "นกยูงหมึก",
    "loreZh": "它的尾羽记录着书街所有被划掉的草稿。展开时很张扬，合起来却小心藏着别人不敢说的话。",
    "loreTh": "ขนหางเก็บร่างที่ถูกขีดทิ้งจากถนนหนังสือ กางแล้วดูเด่น แต่พอพับก็ซ่อนคำที่คนอื่นไม่กล้าพูด",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "puppet-macaque",
    "world": "cn",
    "rank": 1,
    "zh": "后台牵线猴",
    "th": "ลิงหุ่นหลังเวที",
    "sheet": "renewed-puppet-macaque-v2.png",
    "designSource": "monster-puppet-macaque-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "shield",
    "traitZh": "它在后台练习了很久，却从未真正上台",
    "traitTh": "ลิงหุ่นหลังเวที",
    "loreZh": "它在后台练习了很久，却从未真正上台。线团缠住手脚时，它只是在拼命找回原来的舞步。",
    "loreTh": "มันซ้อมหลังเวทีมานานแต่ยังไม่เคยแสดง เมื่อด้ายพันแขนขา มันแค่พยายามหาท่าเต้นเดิมคืน",
    "tellZh": "收紧护具，准备迎接回应",
    "tellTh": "ปิดเกราะเตรียมรับคำตอบ",
    "counterZh": "连续答对两次拆开护甲；失误会重置破甲节奏",
    "counterTh": "ตอบถูกสองครั้งติดเพื่อเปิดเกราะ หากพลาดต้องเริ่มใหม่"
  },
  {
    "id": "porcelain-lion",
    "world": "cn",
    "rank": 2,
    "zh": "青花踏鼓狮",
    "th": "สิงโตลายคราม",
    "sheet": "renewed-porcelain-lion-v2.png",
    "designSource": "monster-porcelain-lion-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "青花醒狮由学生收集的瓷纹纸拼成",
    "traitTh": "สิงโตลายคราม",
    "loreZh": "青花醒狮由学生收集的瓷纹纸拼成。它每一次重踏，都在替即将开场的伙伴壮胆。",
    "loreTh": "สิงโตทำจากกระดาษลายเครื่องลายครามที่นักเรียนเก็บมา ทุกครั้งที่ย่ำพื้นคือการให้กำลังใจเพื่อนก่อนขึ้นเวที",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "clock-bear",
    "world": "cn",
    "rank": 2,
    "zh": "幕前钟表熊",
    "th": "หมีนาฬิกาหน้าม่าน",
    "sheet": "renewed-clock-bear-v2.png",
    "designSource": "monster-clock-bear-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "钟表棕熊负责准时拉开幕布",
    "traitTh": "หมีนาฬิกาหน้าม่าน",
    "loreZh": "钟表棕熊负责准时拉开幕布。它把每个迟到的道歉都藏在钟壳里，难怪走起路来叮当响。",
    "loreTh": "หมีนาฬิกามีหน้าที่เปิดม่านตรงเวลา มันเก็บคำขอโทษที่มาสายในเรือนนาฬิกา จึงเดินเสียงกรุ๊งกริ๊ง",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  },
  {
    "id": "twin-bell",
    "world": "cn",
    "rank": 2,
    "zh": "双城回响兽",
    "th": "อสูรเสียงสองเมือง",
    "sheet": "renewed-twin-bell-v2.png",
    "designSource": "monster-twin-bell-v1.webp",
    "animation": null,
    "single": false,
    "artVersion": "adventure-2",
    "mechanic": "sequence",
    "traitZh": "双城钟兽身上挂着两座校园的铃",
    "traitTh": "อสูรเสียงสองเมือง",
    "loreZh": "双城钟兽身上挂着两座校园的铃。它曾听不懂另一边的问候，而你们走过的每一关，都在替它把声音接回来。",
    "loreTh": "อสูรระฆังสองเมืองมีระฆังจากสองโรงเรียน มันเคยไม่เข้าใจคำทักทายอีกฝั่ง ทุกด่านที่ผ่านช่วยเชื่อมเสียงกลับมา",
    "tellZh": "动作突然停顿，准备展开第二幕",
    "tellTh": "หยุดชั่วครู่ก่อนเริ่มช่วงที่สอง",
    "counterZh": "句子章节中，半血后按语义重组词序",
    "counterTh": "ในบทฝึกประโยค เมื่อพลังเหลือครึ่งให้เรียงประโยค"
  }
];
